### ISSUE TITLE
Facing issue while starting

### ISSUE THREAD

**Issue by marypriyanka** [casbin/node-casbin#1]
Hi,

While I execute the below command
**npm run-script build** 

I am getting this error 

```
(node:56412) UnhandledPromiseRejectionWarning: Error: Could not resolve entry (/home/saranya/node-casbin-master/lib/es6/casbin.js)
    at error (/home/saranya/node-casbin-master/node_modules/rollup/dist/rollup.js:3356:15)
    at /home/saranya/node-casbin-master/node_modules/rollup/dist/rollup.js:20724:17 
```

**Comment by nodece** [comment]
Sorry, The project  in the development stage, Because we deleted the entry file, we will fix it immediately.

**Comment by hsluoyz** [comment]
Hi @marypriyanka , the project has hit its 1.0.0 version several days ago. We believe it's ready for use now. Can you try again about the issue you encountered? Thanks.

**Comment by hsluoyz** [comment]
Closed as stale.
