### ISSUE TITLE
policy work on online editor but fail with api

### ISSUE THREAD

**Issue by Chellhooo** [casbin/node-casbin#100]
hi~ 
I test my model online and it works. 
<img width="1206" alt="屏幕快照 2019-11-29 下午6 30 40" src="https://user-images.githubusercontent.com/30390409/69862922-7f85d500-12d6-11ea-95eb-b4adde7c88aa.png">

But when i fetch permissions with node api `getImplicitPermissionsForUser`, it got empty array:
```
enforcer.getImplicitPermissionsForUser('bob', 'p2') //  []
enforcer.getImplicitPermissionsForUser('system_admin', 'p2') // [ 'system_admin', '*', '*', '*' ]

enforcer.getImplicitPermissionsForUser('alice', 'p1') //  []
enforcer.getImplicitPermissionsForUser('app_viewer', 'p1') //  [ ... ] 
```

And I also can't use `hasPermissionForUser` to judge whether a user has a permission
```
enforcer.hasPermissionForUser('bob',  'p2', '/app', 'find') //  false
enforcer.hasPermissionForUser('alice',  'p1', '/app', 'find') //  false
```

Here is my data store in database

<img width="896" alt="屏幕快照 2019-11-29 下午6 50 40" src="https://user-images.githubusercontent.com/30390409/69864149-4e5ad400-12d9-11ea-995d-a9e230d7b384.png">

Do I misunderstand something or do something wrong? Thanks for your help.

**Comment by nodece** [comment]
Can you provide model and policy in text format？

**Comment by Chellhooo** [comment]
> Can you provide model and policy in text format？

sorry to forget that ...
[casbin.txt](https://github.com/casbin/node-casbin/files/3905905/casbin.txt)

**Comment by nodece** [comment]
@Chellhooo Please check the consistency of g and p in the model and policy.

**Comment by nodece** [comment]
@Chellhooo Thank you for your report! Casbin does not support the feature. We team need to discuss it.

**Comment by nodece** [comment]
In Casbin, RBAC API doesn't care matcher.

**Comment by Chellhooo** [comment]
@nodece Thanks~  Looking forward to new support in casbin.
