### ISSUE TITLE
GitHub Release for 3.0.8

### ISSUE THREAD

**Issue by austince** [casbin/node-casbin#103]
Hi, can you please make a GitHub release for 3.0.8? Would you accept a PR that integrates [`semantic-release`](https://github.com/semantic-release/semantic-release), which would eliminate these types of issues?

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@austince Thanks, I'm already doing it.

**Comment by hsluoyz** [comment]
@nodece What about `semantic-release`?

**Comment by nodece** [comment]
@hsluoyz See: https://github.com/semantic-release/semantic-release.

**Comment by nodece** [comment]
Hi guys, `semantic-release` is integrated in node-casbin!
