### ISSUE TITLE
Undefined Columns v3, v4, v5 when deleting role with a domain

### ISSUE THREAD

**Issue by Sir-Kyle-Richardson** [casbin/node-casbin#110]
Using casbin in node with casbin-knex-adapter (https://github.com/sarneeh/casbin-knex-adapter)

Role and policy in db
![image](https://user-images.githubusercontent.com/8643571/72356772-ce859f00-36b7-11ea-8200-568c4640dfe6.png)

Code snippet being ran:
![image](https://user-images.githubusercontent.com/8643571/72356596-7f3f6e80-36b7-11ea-83f4-bcb95ba16a7f.png)

Invoked with:
```js
{
    userId: 'userId4',
    policyName: 'Delete a role',
    domain: 'organization_1234',
}
```

Error Thrown:
![image](https://user-images.githubusercontent.com/8643571/72356570-75b60680-36b7-11ea-8c57-cbaba5a75d5d.png)

casbin.model.conf:
![image](https://user-images.githubusercontent.com/8643571/72356915-19071b80-36b8-11ea-87f5-05ef87864a33.png)

**Comment by hsluoyz** [comment]
Hi @Sir-Kyle-Richardson , I think you should send the issue to the adapter repo: https://github.com/sarneeh/casbin-knex-adapter
