### ISSUE TITLE
Am using casbin-sequelize-adapter to load the policy from database

### ISSUE THREAD

**Issue by kowthalganesh** [casbin/node-casbin#112]
By default, the adapter is creating id, ptype, v0, v1, v2, v3, v4 columns if not exist
Can I add more columns to handle the application policies
Like application_id as v5, group_id as v6,... etc

I tried to add the columns but during the retrieval, it's returning only the columns which is created by the adapter.

**Comment by hsluoyz** [comment]
You need to modify the adapter code, then publish a new NPM package.

**Comment by kowthalganesh** [comment]
Then I cant able to get the upgrades from the actual adapter, isn't it?

**Comment by hsluoyz** [comment]
I don't understand what you meant.

**Comment by kowthalganesh** [comment]
I mean, if I change the adapter settings to add more columns and publish the adapter as a new package in npm. same time when you release some features in your adapter, how do I consume the updates, since I was completely using the different packages, how can I get your updates in my packages

**Comment by hsluoyz** [comment]
You have to rebase or cherry-pick the official updates to your fork.

Or if you can figure out a way to dynamically determine v5, v6,.. with parameters. I think this way works as Javascript is a scripting language. You can send a PR about it.

**Comment by kowthalganesh** [comment]
Actually this is what my tech stack was front end **angular/react** back end **nodejs,** using node-casbin, I can configure the rules and casbin-sequelize-adapter was used to store and retrive the policy and permission dataset from the database, How to handle the access control for the front end, Do we have any docs for that, i mean if i want to show a button based on the permission in UI, How casbin can support here

**Comment by hsluoyz** [comment]
@kowthalganesh , see: https://dashboard.casbin.org/

**Comment by nodece** [comment]
@kowthalganesh Get user permission through the manager_api then pass them to the frontend.

**Comment by kowthalganesh** [comment]
@hsluoyz yes when I do analyze i found the dasboard page, but it was always blank

![image](https://user-images.githubusercontent.com/5681640/73426592-c3d73500-435a-11ea-8fe3-2405b9ef6d1d.png)

**Comment by hsluoyz** [comment]
@kowthalganesh can you access this URL? https://dashboard.casbin.org:8001/api/get-models

**Comment by kowthalganesh** [comment]
> @kowthalganesh Get user permission through the manager_api then pass them to the frontend.

Thats what i was thinking then too, casbin_rule is a table which is created by casbin-sequelize-adapter, its an adapter which is having 8 columns, id, ptype, v0 to v5

id   | ptype |     v0          |       v1               |            v2     |        v3         |

1    |  p       |  admin       |    POST              |     /project   |   appname  |   
2    |  p       |  admin       |   CreateProject  |                     |   appname  |
3    |  g       |  kowthal    |   admin              |    write         |   appname  |


My sample data model,  
id - > 1 refers api access control
id - > 2 refers ui access control

v3 -> columns refers to application name, am planning to maintain all the different application in one database and table

![image](https://user-images.githubusercontent.com/5681640/73427499-e8341100-435c-11ea-91c7-925f096322df.png)

we have the policy config file[refer above image] in node js API to validate the access control permission using our data model from the casbin_rule table.

 whereas in ui to hide the button in a page how it work

**Comment by kowthalganesh** [comment]
> @kowthalganesh can you access this URL? https://dashboard.casbin.org:8001/api/get-models
> 
> It should be:
> 
> ![image](https://user-images.githubusercontent.com/3787410/73427398-a5c8ff00-4371-11ea-8ce9-3b8a28335c24.png)

No @hsluoyz 

![image](https://user-images.githubusercontent.com/5681640/73427831-b0799900-435d-11ea-8148-f11209acc3c0.png)

**Comment by hsluoyz** [comment]
Try it again: https://dashboard.casbin.org/

**Comment by hsluoyz** [comment]
For UI authz, please see: https://github.com/casbin/casbin-editor

**Comment by kowthalganesh** [comment]
Cool Thank you @hsluoyz, It's working now https://dashboard.casbin.org/. let me explore things once again, thanks for your support, it's awesome guys..

**Comment by kowthalganesh** [comment]
> For UI authz, please see: https://github.com/casbin/casbin-editor

I was trying to understand the casbin-editor, its a react based code, i have gone through all the packages, validation, syntax,..etc everything makes sense to me, now am trying the same in angular
application, i was facing so many packages and dependency related issues, do you have any repo for angular application

![image](https://user-images.githubusercontent.com/5681640/73532483-c90faf00-4442-11ea-831d-8ae8ea3194bd.png)

**Comment by hsluoyz** [comment]
@nodece

**Comment by kowthalganesh** [comment]
After my analyze, did two things to solve the errors 

1. package.json - added this configuration in package.json
"browser": {
    "fs": false,
    "path": false,
    "os": false
  }

2. Polyfill.ts - added this below line in polyfill.ts 

(window as any).global = window;

**Comment by hsluoyz** [comment]
Good to hear you solved it !

**Comment by nodece** [comment]
> > @kowthalganesh Get user permission through the manager_api then pass them to the frontend.
> 
> That's what I was thinking then too, casbin_rule is a table which is created by casbin-sequelize-adapter, its an adapter which is having 8 columns, id, ptype, v0 to v5
> 
> ```
> id   | ptype |     v0       |       v1           |         v2     |        v3         |
> 
> 1    |  p       |  admin       |    POST              |     /project   |   appname  | 
> 2    |  p       |  admin       |   CreateProject  |                     |   appname  |
> 3    |  g       |  kowthal    |   admin              |    write         |   appname  |
> ```
> 
> My sample data model,
> id - > 1 refers api access control
> id - > 2 refers ui access control
> 
> v3 -> columns refer to application name, am planning to maintain all the different application iaccess control n one database and table [casbin_rule]
> 
> ![image](https://user-images.githubusercontent.com/5681640/73427499-e8341100-435c-11ea-91c7-925f096322df.png)
> 
> we have the policy config file[refer above image] in node js API to validate the access control permission using our data model from the casbin_rule table.
> 
> whereas in UI to hide the button on a page how it works?

In my application, I combine v1 and v2 as keyword to pass to the frontend. 

Response text: 
```json
{
  "user": "admin",
  "permission": ["POST$$/project"]
}
```

frontend with jsx
```tsx
const response = {
    user: "admin",
    permission: ["POST$$/project"]
}

function hasPermission(action)  {
    return response.permission.some(n => n === action);
} 

// check permission
{hasPermission("POST&&/project") && <div>hello</div>}
```

**Comment by kowthalganesh** [comment]
I got an idea, how you guys handled in reactjs after cloning the repo - https://github.com/casbin/casbin-editor, Dependency, packages, compiling mechanism, everything is different from react to angular, thought of if you build something on angular it will be great, else, am working on the base setup, once it's done we can publish this as an angular reference

**Comment by kowthalganesh** [comment]
Done, Implementation for angular is up and running without an issue.

**Comment by hsluoyz** [comment]
Good. Is it open source?

**Comment by kowthalganesh** [comment]
Yes, it's an open-source similar like https://github.com/casbin/casbin-editor in angular version

**Comment by hsluoyz** [comment]
Is there a GitHub link?

**Comment by kowthalganesh** [comment]
https://github.com/kowthalganesh/casbin-angular

**Comment by kowthalganesh** [comment]
I have a thought process on casbin-adapter to retrieve the dataset from the database.

Casbin adapter automatically created a table called **casbin_rule**, 
inserting a set of columns **id, ptype, v0,...v5**

In case, if we want more we can modify in the table, but casbin will always return the columns which are created by casbin-adapter, not manually modified. why we made like this, is there any limitation behind this? 

we can return all the columns which are there in casbin_rule, instead of looking/retrieving  for the default columns
