### ISSUE TITLE
rbac api deleteRolesForUser

### ISSUE THREAD

**Issue by helibin** [casbin/node-casbin#113]
The following code doesn't work:

```js
e.addRoleForUser('alice', 'data1_admin')
e.addRoleForUser('alice', 'data2_admin')

e.deleteRolesForUser('alice')
```

DB:
![image](https://user-images.githubusercontent.com/14595752/74078552-c6c2db80-4a66-11ea-91c3-1120cfa631ab.png)

model.conf:
![image](https://user-images.githubusercontent.com/14595752/74078561-db9f6f00-4a66-11ea-9c14-4c58d47381e5.png)

**Comment by hsluoyz** [comment]
@helibin Hi, please use English.

**Comment by helibin** [comment]
e.deleteRolesForUser('alice') it doesn't work
e.enforce('tester', '/test/1') it doesn't work

**Comment by hsluoyz** [comment]
Please call `savePolicy()`

**Comment by helibin** [comment]
OK, it works~ thank

Hope that can be added to documents

**Comment by hsluoyz** [comment]
@helibin can you make a PR to fix the docs?

**Comment by nodece** [comment]
@helibin Can you provide the Casbin version and adapter? 
@hsluoyz The Casbin user should not call `savePolicy` manually. When the policy changes, Casbin can automatically save the policy to the DB.

**Comment by helibin** [comment]
"casbin": "^3.1.0"
"casbin-sequelize-adapter": "^2.0.0"

**Comment by hsluoyz** [comment]
@helibin is this issue fixed?

**Comment by helibin** [comment]
Yes! It works when I used the 'e.savePolicy()' after e.deleteRolesForUser('alice')

**Comment by nodece** [comment]
It is working :)

```typescript
    const a = await SequelizeAdapter.newAdapter({
        username: 'root',
        password: '',
        database: 'casbin',
        dialect: 'mysql'
    });
    let e = await newEnforcer('examples/rbac_model.conf', a);
    await e.deleteRolesForUser("alice");
```
