### ISSUE TITLE
Lock is missing while pulling changes of policies

### ISSUE THREAD

**Issue by GopherJ** [casbin/node-casbin#114]
While using `koa`, `redis-watcher`, `cluster`, `typeorm-adapter`, I found that sometimes the behavior can be very strange.

So I checked https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts and found this line: https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts#L137
```js
 /**
   * loadPolicy reloads the policy from file/database.
   */
  public async loadPolicy(): Promise<void> {
    this.model.clearPolicy();
    await this.adapter.loadPolicy(this.model);

    this.model.printPolicy();
    if (this.autoBuildRoleLinks) {
      await this.buildRoleLinks();
    }
  }
```

I think here a mutex lock is missing. If we are pulling policies, we shouldn't let `Enforcer` to authorize/deny request until the lock has been released.

 `this.model.clearPolicy` is synchrnous, but `await this.adapter.loadPolicy(this.model);` is asynchronous.

Image that `await this.adapter.loadPolicy(this.model);` will take 10 minutes to finish. But in this case the policies in memory have been cleared....so casbin will return false to the coming request.

Any idea on how to fix this?

**Comment by GopherJ** [comment]
This can be useful: https://www.npmjs.com/package/mutexify

**Comment by hsluoyz** [comment]
@GopherJ can you see how Golang's Casbin handle it?

**Comment by nodece** [comment]
@hsluoyz I will implement a synchronous enforcer.

**Comment by nodece** [comment]
@GopherJ feat a synchronous enforcer in #117.
