### ISSUE TITLE
enforcer.load_policy() must be atomic

### ISSUE THREAD

**Issue by GopherJ** [casbin/node-casbin#115]
Following #114, another potential issue is also located in `load_policy` function:

https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts
https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts#L137

```js
 /**
   * loadPolicy reloads the policy from file/database.
   */
  public async loadPolicy(): Promise<void> {
    this.model.clearPolicy();
    await this.adapter.loadPolicy(this.model);

    this.model.printPolicy();
    if (this.autoBuildRoleLinks) {
      await this.buildRoleLinks();
    }
  }
```

Image that we did two quick changes but ` await this.adapter.loadPolicy(this.model)` will take time (10 minutes) to finish.

So here what actually happens is:

we will execute two times:
```js
 this.model.clearPolicy();
 this.model.clearPolicy();
```

then two times:
```js
await this.adapter.loadPolicy(this.model);
await this.adapter.loadPolicy(this.model);
```

So in the model we wil have two times policies like:

```js
alice, domain1, /data1, read
alice, domain1, /data1, read
bob, domain2, /data2, write
bob, domain2, /data2, write
```

**Comment by GopherJ** [comment]
This one may be false because I just wrote simple code to simulate the situation and it seems that I can get correct result.

```js
var EventEmitter = require('events')

async function load_policy() {
    console.log("clearing model's policy");
    await load_adapter_policy();
}

async function load_adapter_policy() {
    console.log("loading adapter's policy");
    return new Promise(resolve => setTimeout(resolve, 2000)); 
}

var ee = new EventEmitter()
ee.on('message', async function (text) {
    await load_policy();
})

ee.emit("message", 1)
ee.emit("message", 1)
```

result
```js
clearing model's policy
loading adapter's policy
clearing model's policy
loading adapter's policy
```

**Comment by GopherJ** [comment]
But it's really strange because different enforcer instances have different policies in model.

Any one has any idea? I'm using `koa` with `cluster`, `redis-watcher`, `casbin@3.1.0`

You can see from here, while refreshing pages, a new request has been made to a different `koa` process but they have different policies in model....

![Peek 2020-02-10 20-44](https://user-images.githubusercontent.com/33961674/74151279-c97c2700-4c46-11ea-844a-af50e451f4fb.gif)

**Comment by hsluoyz** [comment]
@nodece @chalince

**Comment by nodece** [comment]
@hsluoyz @GopherJ 
For atomic, node-Casbin will use https://github.com/ide/await-lock to implement a synchronous enforcer. 

For asynchronous programming, we can only use `async` or `callback` in Node.js.

In order to use https://github.com/ide/await-lock, we need to convert synchronous functions in Manager API to `async` functions. 

It is breaking changes :( 
Very sorry!

**Comment by nodece** [comment]
> But it's really strange because different enforcer instances have different policies in model.
> 
> Any one has any idea? I'm using `koa` with `cluster`, `redis-watcher`, `casbin@3.1.0`
> 
> You can see from here, while refreshing pages, a new request has been made to a different `koa` process but they have different policies in model....
> 
> ![Peek 2020-02-10 20-44](https://user-images.githubusercontent.com/33961674/74151279-c97c2700-4c46-11ea-844a-af50e451f4fb.gif)

You can try upgrade `node-casbin` to the latest version！

**Comment by GopherJ** [comment]
Hello @nodece I found some problems of redis-watcher:

The first problem is: When I launch the server, it will trigger one time `update`:

![image](https://user-images.githubusercontent.com/33961674/74218272-b15ae500-4ce4-11ea-807b-3a6baf0106c0.png)

The second problem is: Somewhere it calls two times `this.adapter.loadPolicy(this.model)` instead of continuos:

```js
this.model.clearPolicy()
this.adapter.loadPolicy(this.model)
this.model.clearPolicy()
this.adapter.loadPolicy(this.model)
....

It's doing:
```
this.adapter.loadPolicy(this.model)
this.adapter.loadPolicy(this.model)
```

![untitled](https://user-images.githubusercontent.com/33961674/74218897-2b3f9e00-4ce6-11ea-9cea-3149e32ac1b4.png)

**Comment by nodece** [comment]
@GopherJ  Hi guys, please try node-casbin@4.1.0 and use `newSyncedEnforcer` creates a synchronized enforcer via file or DB.

**Comment by nodece** [comment]
related issues: #114 .
