### ISSUE TITLE
RBAC deleteUser does not work correctly and is not tested

### ISSUE THREAD

**Issue by Sefriol** [casbin/node-casbin#118]
[Coveralls](https://coveralls.io/builds/28711628/source?filename=src/enforcer.ts#L187)
[Source](https://github.com/casbin/node-casbin/blob/master/src/enforcer.ts#L187)

I think deleteUser should follow similar idea as deleteRole:

```typescript
public async deleteUser(user: string): Promise<boolean> {
    const res1 = await this.removeFilteredGroupingPolicy(0, user);
    const res2 = await this.removeFilteredPolicy(0, user);
    return res1 || res2;
}
```

Since we want to remove assigned grouping policy and policies assigned to that user. Now when using `mongoose-adapter`, it will just remove user grouping policies, leaving normal policies still into the database. With code above, I was able to fix this.

**Comment by Sefriol** [comment]
[Created related tests for mongoose-adapter](https://travis-ci.org/Sefriol/casbin-mongoose-adapter/builds/652400079?utm_source=github_status&utm_medium=notification)

**Comment by nodece** [comment]
@hsluoyz  what do you think?

**Comment by Sefriol** [comment]
I'll create a pull request with RBAC tests and required changes.

**Comment by hsluoyz** [comment]
@nodece @Sefriol can you check how Golang's Casbin handle it? I want all Casbin implementations to follow the same behavior on this.

**Comment by Sefriol** [comment]
https://github.com/casbin/node-casbin/pull/119

**Comment by Sefriol** [comment]
@hsluoyz Is the function properly tested in Golang? Since implementation looks the same, so issue should be the same. Unless the implementation of `removeFilteredGroupingPolicy()` is different in golang.

However, in [golang tests](https://github.com/casbin/casbin/blob/master/rbac_api_test.go#L99) it does not seem like user permission tests are correct.

[In line 107](https://github.com/casbin/casbin/blob/master/rbac_api_test.go#L107) I think alice should have no rights for data1 after she was deleted.

**Comment by hsluoyz** [comment]
Hi @Sefriol , I think you are right. Both Golang and Node.js Casbin have wrong implementation. Can you make a PR for Golang too to fix the code and test?

**Comment by Sefriol** [comment]
I'll update the PR later on today. Golang does not seem to be that complicated either, but it has been awhile since I worked on Golang-project.
