### ISSUE TITLE
PostgreSQL adapter

### ISSUE THREAD

**Issue by Marvin9** [casbin/node-casbin#120]
I am willing to work on PostgreSQL adapter.

**Comment by nodece** [comment]
@Marvin9  
1. import  { Adapter  } from 'casbin'
2. all methods to implement the adapter

You can get some adapter code in https://github.com/node-casbin.

**Comment by Marvin9** [comment]
I will drop comment as soon as I start working on it. Before that I will understand the codebase first.

**Comment by Marvin9** [comment]
I have started working on it.
https://github.com/Marvin9/casbin-postgre-adapter

@hsluoyz whom should I connect for any query?

**Comment by hsluoyz** [comment]
@Marvin9 contact @nodece

**Comment by GinaMaronov** [comment]
What's wrong with the casbin sequelize adapter? 

https://github.com/node-casbin/sequelize-adapter

**Comment by Marvin9** [comment]
Nothing wrong with sequelize. There are organizations and individuals who clearly [don't want to include ORMs](https://www.yegor256.com/2014/12/01/orm-offensive-anti-pattern.html) to their system. 

Advantage of ORM is to make development process easy. However while you use casbin you don't write any query yourself, it is managed by adapters. Eventually if the advantage fades away then why to add extra layer?

[Reference to sequelize using postgres driver (pg)](https://github.com/sequelize/sequelize/blob/b2a2134697eb983545f5e717df7d14705a67df33/lib/dialects/postgres/connection-manager.js#L18)

**Comment by hsluoyz** [comment]
@nodece I also have this question: why we use a PostgreSQL adapter instead of the ORM adapter?

**Comment by nodece** [comment]
@hsluoyz I agree with @Marvin9, we should support pure database drivers.

**Comment by hsluoyz** [comment]
@Marvin9 @nodece is this issue still active?

**Comment by Marvin9** [comment]
Yes @hsluoyz I will resolve it soon. Due to internship It is delayed.

**Comment by hsluoyz** [comment]
Closed for now.

**Comment by Marvin9** [comment]
@hsluoyz Can you please check this repo https://github.com/Marvin9/casbin-postgre-adapter, except few tests and documentation everything is complete.

**Comment by hsluoyz** [comment]
@Marvin9 no README, no badges like CI, coverage.. No npm download.

**Comment by zhmushan** [comment]
@Marvin9 Now we can use https://github.com/node-casbin/basic-adapter

**Comment by Marvin9** [comment]
@hsluoyz I mentioned that few test cases & documentation work is pending. 

Now there is already ```basic-adapter```, Should I complete it or abandon?

**Comment by hsluoyz** [comment]
Why not complete it?

**Comment by hsluoyz** [comment]
We already have a lot of ORM adapters that support PostgreSQL besides basic adapter. But we still think an adapter specifically for PostgreSQL would be useful.

**Comment by hsluoyz** [comment]
@zhmushan please also add basic adapter to docs.

**Comment by Marvin9** [comment]
@hsluoyz Great. I will complete it soon.
