### ISSUE TITLE
Docs Shortage

### ISSUE THREAD

**Issue by NitinBhasneria** [casbin/node-casbin#121]
There is no contributing doc, which is making it difficult for newcomers to run node-casbin in their server.

**Comment by hsluoyz** [comment]
See middlewares: https://casbin.org/docs/en/middlewares

Tutorials: https://casbin.org/docs/en/tutorials

**Comment by NitinBhasneria** [comment]
Actually I am talking about how to run this node-casbin in my pc server? I can't get any tutorial for this.
In every open-source org it is written in readme itself.

**Comment by hsluoyz** [comment]
Node-Casbin is a library. You cannot directly "run" a library. But you can write an application, which invokes Casbin. Or run our test cases:

https://github.com/casbin/node-casbin/blob/cd2bb542d1f76d6e9dfc81df1f6be4ed975dfc4c/test/model.test.ts#L30-L41

The middleware link I gave will show how to use Casbin in a web application (via web frameworks lik e Express.js, Nest.js, etc.)

**Comment by Marvin9** [comment]
I know you are talking about experimenting to get familiar with APIs. Here is the basic template I used following README.md.

```javascript
const casbin = require('casbin');

(async() => {
    const enforcer = await casbin.newEnforcer('./example/basic_modal.conf', './example/basic_policy.csv');
// get basic_modal.conf & basic_policy.csv from examples folder : 
// https://github.com/casbin/node-casbin/tree/master/examples

    const sub = 'alice';
    const obj = 'data1';
    const act = 'read';

    const res = await enforcer.enforce(sub, obj, act);
    if (res) {
        console.log(`${sub} can ${act} ${obj}`);
    } else {
        console.log(`${sub} cannot ${act} ${obj}`);
    }
})();
```

Now you can change conf or csv files accordingly & try different cases. Follow test cases for that as @hsluoyz  told.
Refer [PERM metamodal](https://vicarie.in/posts/generalized-authz.html) to understand how .conf works

**Comment by NitinBhasneria** [comment]
@hsluoyz Can you tell me when will be the casbin cpp, casbin js repo will be updated, as this is the projects.
