### ISSUE TITLE
Implementation docs for Node-casbin 

### ISSUE THREAD

**Issue by valshrih** [casbin/node-casbin#123]
hi everyone:smiley:, I am beginner with casbin(node+ casbin). I wanted **node-casbin** as  Authz in  my project so it can handle all my rule & permission and user will authorize first for every Action done but i'm not able to find proper **documentation** with which i can start Authz( node+casbin) implementation. Any help will be appreciable.

**Comment by nodece** [comment]
See: https://casbin.org/docs/en/get-started.

**Comment by valshrih** [comment]
thanks for your reply @nodece ,  i have gone through [docs ](https://casbin.org/docs/en/get-started.),
at the basic level i can implement.i wanted to create a hybrid conf model file so i can control ACL, RBAC and RBAC with tetants.

**Comment by nodece** [comment]
Casbin can support it.
Select `RBAC with domains/tenants` in https://casbin.org/docs/en/supported-models

**Comment by nodece** [comment]
closed as resolved.
