### ISSUE TITLE
Session based RBAC Support for node-Casbin

### ISSUE THREAD

**Issue by brt-srini-rama** [casbin/node-casbin#127]
Hi All,
  I Just come across Session based RBAC in casbin, and unfortunately I could not able to see the node-casbin support for session, "https://casbin.org/docs/en/role-managers", is there any possibility that team can provide support for this?

**Comment by hsluoyz** [comment]
Can you elaborate on what session-based RBAC is?

**Comment by brt-srini-rama** [comment]
I was exploring your suggestion for the old closed issue [43](https://github.com/casbin/casbin/issues/43) , in the issue analysis you were recommending to use the SetRoleManager() instead of defining the "S" rule in model.config.  My  current requirement is exactly the same as requested by user "Julian Schmidt". Eventually this issue was closed with the fork of new repo for "[Session Role Manager](https://github.com/casbin/session-role-manager)" but I could not see the nodeJS implementation on this repo.

My use case is, I need to create a policy engine node server that should impose different role in the Role-hierarchy to the user during different times of the day.

**Comment by gr4yha7** [comment]
@hsluoyz i can jump on this if it's up for grabs

**Comment by hsluoyz** [comment]
Yes. Please implement.

@nodece

**Comment by nodece** [comment]
Could anyone working on the issue?

**Comment by DivyPatel9881** [comment]
Yes, I can work on this issue.

**Comment by DivyPatel9881** [comment]
@nodece can you make a new repository for ```node-session-role-manager``` for node-casbin, and if possible give me the commit access to the repository.

**Comment by nodece** [comment]
@DivyPatel9881 https://github.com/node-casbin/session-role-manager has been created.

**Comment by DivyPatel9881** [comment]
@nodece you can review my code of session-role-manager and can add travis-ci to it.

**Comment by nodece** [comment]
Thank you, @DivyPatel9881 ,  Let me make adjustments.

**Comment by nodece** [comment]
@brt-srini-rama  [session-role-manager](https://github.com/node-casbin/session-role-manager) has been released.

**Comment by hsluoyz** [comment]
Added: https://github.com/casbin/casbin-website/commit/cc88bfceefaf65ebd2902b4a7bb59eb5a3f5f177
