### ISSUE TITLE
GSoC: adapters 

### ISSUE THREAD

**Issue by nodece** [casbin/node-casbin#128]
Adapter is the bridge between Casbin and policy storage container.

Recommended to use TypeScript to build Casbin ecosystem.

- [x] PosgreSQL adapter via [pg](https://www.npmjs.com/package/pg)
- [x] MySQL adapter via [mysql](https://www.npmjs.com/package/mysql)
- [x] MySQL adapter via [mysql2](https://www.npmjs.com/package/mysql2) 
- [x] Microsoft SQL Server adapter via [mssql](https://www.npmjs.com/package/mssql) 
- [ ] Oracle adapter via [oracledb](https://www.npmjs.com/package/oracledb) 
- [x] SQLite adapter via [sqlite3](https://www.npmjs.com/package/sqlite3)
- [ ] IBM Db2 adapter via [ibm_db](https://www.npmjs.com/package/ibm_db)

**Comment by Marvin9** [comment]
Any reason on supporting both, mysql & mysql2 ?

**Comment by nodece** [comment]
We should consider all users.

**Comment by zhmushan** [comment]
Consider supporting both mysql and mysql2 in mysql-adapter

**Comment by ogabek96** [comment]
I would like to contribute on adding oracledb adapter.Where I can check already done adapters Postgres, mysql etc. ?

**Comment by hsluoyz** [comment]
@ogabek96 see: https://casbin.org/docs/en/adapters
