### ISSUE TITLE
GSoC:  middlewares for web frameworks

### ISSUE THREAD

**Issue by nodece** [casbin/node-casbin#129]
### Supported 
- [x] https://github.com/koajs/koa
- [x] https://github.com/eggjs/egg/
- [x] https://github.com/expressjs/express

### Things to do
- [x] https://github.com/nestjs/nest
- [x] https://github.com/hapijs/hapi
- [ ] https://github.com/meteor/meteor

**Comment by Marvin9** [comment]
Description?

**Comment by romitkarmakar** [comment]
@nodece I have been working on hapijs authorization middleware for casbin. Could you create a hapi-authz repository so, I could send my PR to it..

**Comment by dweep612** [comment]
Can I work on this?

**Comment by hsluoyz** [comment]
@dweep612 

TODO:

1. https://github.com/node-casbin/blitz-authz
2. https://github.com/node-casbin/meteor-authz
3. https://github.com/node-casbin/nest-authz

**Comment by dweep612** [comment]
Ok @hsluoyz, I will.

**Comment by hsluoyz** [comment]
@dweep612 plz ask @nodece

**Comment by dweep612** [comment]
@nodece can you please guide me how can I go ahead in this?

**Comment by nodece** [comment]
@dweep612 you can make a meteor-authz plugins, please refer the plugins from https://github.com/search?q=org%3Anode-casbin+authz.

**Comment by anik31** [comment]
@nodece @hsluoyz I am working on the meteor-authz plugin but the repo cannot be forked or cloned - https://github.com/node-casbin/meteor-authz.

**Comment by hsluoyz** [comment]
@anik31 try this: https://github.com/node-casbin/meteor-authz

**Comment by anik31** [comment]
@hsluoyz Thanks. I Will make a PR to this repo.
