### ISSUE TITLE
ABAC model request_definition length required.

### ISSUE THREAD

**Issue by surgentt** [casbin/node-casbin#133]
Hello,
I have the following model setup for abac authorization
```ini
# The Request Definition for the access request.
# Defines the arguments for the e.Enforce(...) function
[request_definition]
r = subject, target, action

# The Policy Definition for the policy file. Not required for Abac.
[policy_definition]
p = subject, target, action

# The Policy Effect defines whether the access request should be approved if multiple policy rules match the request.
# The below states if any policy has effect of allow we will allow.
[policy_effect]
e = some(where (p.eft == allow))

# Matchers are the definition for policy matchers and are expressions.
# The below allows access to the owner of a target or if the target is public and we are reading.
[matchers]
m = (r.target.public == true && r.action == "read") || r.subject.id == r.target.ownerId 
```

In the matcher section, I noticed that I am required to pass an ownerId to the matcher with a length greater than one. 

For example if I pass a target with an ownerId of null or an empty string, this model will always fails even if that target is public and the action is "read"

Is there a way to fix my model or is this a bug?

**Comment by nodece** [comment]
@surgentt Could you provide the test cases?

**Comment by hsluoyz** [comment]
@surgentt can you give a minimal working example?

**Comment by surgentt** [comment]
Sorry for the delay. I am hoping to write a test and submit a PR, but COVID-19 caused some cut backs at work this week. 

The following target request the above matcher, but I would expect this to pass since public is true and action is read. 

```
const subject = {
  id: 'auth0|123'
};

const target = {
  public: true, 
  ownerId: null,
};

const  action = 'react';
```

Thank you for the additional follow up

**Comment by hsluoyz** [comment]
@nodece can you help test this one?

**Comment by nodece** [comment]
env:
```
nodejs: v13.11.0
```
The following is my test: 
```js
const e = await newEnforcer('examples/abac_model.conf');

let subject = {
  id: 'auth0|123'
};

let target = {
  public: true,
  ownerId: 'anyStringWithLengthAbove1'
};

const action = 'read';

let ok = await e.enforce(subject, target, action);
console.log(ok); //=> true

subject = {
  id: 'auth0|123'
};

target = {
  public: true,
  ownerId: 'anyStringWithLengthAbove1'
};

ok = await e.enforce(subject, target, action);
console.log(ok); //=> true
```

It works fine.

**Comment by surgentt** [comment]
Yes, but what does the following return? I would expect this to pass, but it fails. Not all of my tables support an owner, but just have a public attribute. 

``` JS
const e = await newEnforcer('examples/abac_model.conf');

let subject = {
  id: 'auth0|123'
};

let target = {
  public: true,
  ownerId: null
};

const action = 'read';

let ok = await e.enforce(subject, target, action);
```
There for I would expect the first half of this statement to return true. 
```JS
[matchers]
m = (r.target.public == true && r.action == "read") || r.subject.id == r.target.ownerId 
```
Thank you for looking into this and it possible there is a bug somewhere in my code.

**Comment by surgentt** [comment]
@hsluoyz I just found out the bug is on our end. We had the following check in our code. 
```
    if (!action || !(target && target.ownerId)) {
      return false;
    }
```
After removing this our tests are passing. I apologize for filing a false bug. We are enjoying the package and thank you for your timely responses. Please close this bug.

**Comment by nodece** [comment]
@surgentt Thanks for your support!
