### ISSUE TITLE
Help at modeling a user/role combined with resource/role model/policy/requests

### ISSUE THREAD

**Issue by somq** [casbin/node-casbin#140]
I'm trying to understand how to model our scenario considering:

- Users have roles
- Roles have permissions
- Users lands in groups
- Resources lands in groups
- Groups can be inherited

In our use case 
- Users are humans in client apps
- Roles are a group of permissions
- Groups _hierarchically speaking_ are superadmin (us), tenants or sub-entities of the tenant.
- Resources are IoT devices **or** more "classical" services (let's say API endpoints with CRUD permissions) 
- Users and devices will both be assigned to groups to identify what user is allowed to perform and action on what device.

So, we want to be matching
1) Does the user's role contain the permission to access the resource
2) Does the user belong to the same group of the resource

For instance:
Request to get the status of an IoT device could be: 
```csv
User1, device1234, get_status
```
- Is `User1` in a group (role) which contains `operation` `get_status`?
- Is `User1` in a group which is either the same, or one of the parent group of `device1234`

If both conditions succeed, matcher should return `True`.

Hopefully I'm clear in the description of the question.
I have to admit I'm having a hard time to figure out how to perform this using a single model.  
I made a ton of try outs but I was not able to find a way to match both conditions in the same model.

Any help would be greatly appreciated!

**Comment by somq** [comment]
Thanks for your answers, I have finally succeed to write a policy that works regarding our requirements.

I was trying to do it using only one enforcer (enforcer is equivalent to a request right?).  

Instead I did:
1) Check if user has the explicit permission through its (g) roles
2) Check if user has access to the resource (device) through (g2) groups

**Model**: RBAC with resource roles

**Policy**

```ini
# Assign user to child_group
p, User1, child_group, access

# Declare permission ("device_operation") named "get_status" for role "operator"
p, role:operator, device_operation, get_status

# assign user to role "operator"
g, User1, role:operator

# Assign device to child group, and child_group to parent_group
g2, device1234, child_group
g2, child_group, parent_group
```

**Requests**

Does User1 have the permission to perform a "device_operation" of type "get_status"

```ini
User1, device_operation, get_status
```

Does User1 is allowed to access (therfore perform any action if he has permissions) on "device1234"

```ini
User1, device1234, access
```

Does this looks good to you? Any recommendations?
Thanks for your help.

**Comment by nodece** [comment]
When use `RBAC with domain/tenants` looks simple.

```
p, role:operator, device1234, device_operation, get_status

g, User1, role:operator, device1234
```

**Comment by nodece** [comment]
When use `RBAC with domain/tenants` looks simple.

```
p, role:operator, device1234, device_operation, get_status

g, User1, role:operator, device1234
```

**Comment by somq** [comment]
> When use `RBAC with domain/tenants` looks simple.
> 
> ```
> p, role:operator, device1234, device_operation, get_status
> 
> g, User1, role:operator, device1234
> ```
> 
> What do you think?

So in your example, the `device1234` is bound to `role:operator`, so I will have to create as many roles duplicates as there are devices, right ? (`n` roles for  for `n` devices)

I need roles & permissions to be generic, this way I can assign them directly to users.

Thus, I guess there are no other way than doing it using 2 enforcers?

1) User => role => permission = OK?
2) User => device = OK?

Also, about the hierarchy, I'm forced in any case to have a `g2` to manage it (if I understand the model properly)?

---

In your example that would be:

Model
```ini
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && g2(r.dom, p.dom) && r.obj == p.obj && r.act == p.act
```

Policy

> Note that in this example I'd need `role:operator` to be generic and `User1` to be assigned to `parent_group`

```ini
p, role:operator, parent_group, device_operation, get_status
g, User1, role:operator, device1234

g2, device1234, child_group
g2, child_group, parent_group
```

Many thanks for your help

**Comment by hsluoyz** [comment]
@zhmushan

**Comment by nodece** [comment]
Closed: not active for too long.

**Comment by hsluoyz** [comment]
@nodece I think for this issue it's our side that is not active..

**Comment by somq** [comment]
I've finally used the rbac_with_resource_roles_model implementation @nodece because I wasn't sure of the RBAC with domain/tenant, just a confirmation or advice of an alternate way to solve this issue would still help!
Thanks for your time

**Comment by hsluoyz** [comment]
Great!
