### ISSUE TITLE
using both grouping and keyMatch2 in a matcher 

### ISSUE THREAD

**Issue by ghaedi93** [casbin/node-casbin#141]
im new to casbin and recently using it with nodejs and came across this probably frequent need to use both grouping and keyMatching on a policy , wraping a keyMatch func with g identifier or viseversa doesnt seem to be valid syntax for serving those policies containing resource with pattern 

![Screenshot from 2020-04-25 11-02-29](https://user-images.githubusercontent.com/32374993/80273071-731a7280-86e4-11ea-989a-82ea7e8eb711.png)

**Comment by hsluoyz** [comment]
See: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

@nodece

**Comment by ghaedi93** [comment]
yeah i used it but im not sure if * is valid syntax in nodejs then i used 

  await enforcer.rm.defaultrolemanager.RoleManager.AddMatchingFunc(
    "KeyMatch2",
    util.KeyMatch2
  );
but is this error saying 
_TypeError: Cannot read property 'RoleManager' of undefined_

**Comment by nodece** [comment]
Node.js doesn't support  `AddMatchingFunc`, I will work on this issue.

**Comment by ghaedi93** [comment]
thanks im looking forward ... is that possibly anytime soon ?

**Comment by nodece** [comment]
okey, as soon.

**Comment by nodece** [comment]
@ghaedi93 I submitted a PR: #142

**Comment by hsluoyz** [comment]
Merged.

**Comment by ghaedi93** [comment]
thanks so much ... but i dont know how to make it work , im still getting the same Undefined error . is it sth wronge with how im adding MatchFun ?
also shouldnt g2 in matcher changes? otherwise how to tell it applying keyMatch on objects .  
![Screenshot from 2020-04-25 21-44-35](https://user-images.githubusercontent.com/32374993/80286081-983bcf00-873e-11ea-8833-e6a7d3adedf4.png)

**Comment by nodece** [comment]
@ghaedi93 Upgrade `casbin` to v4.4.0.

**Comment by ghaedi93** [comment]
I have it but sth is possibly wronge with defaultrolemanager it is not defined  . 

![Screenshot from 2020-04-25 21-44-35](https://user-images.githubusercontent.com/32374993/80306012-c91b1300-87d5-11ea-8e8f-246b5c998bb1.png)

**Comment by nodece** [comment]
```js
const rm = enforcer.getRoleManager();
await rm.addMatchingFunc('KeyMatch2', util.keyMatch2Func);
await enforcer.buildRoleLinks();
```

**Comment by ghaedi93** [comment]
util was not defined so i had to find that keyMatch2Func from inside following path 
casbin/lib/util/builtinOperators
but the functionality was not as it should be . 

p, alice, data1, read
p, bob, data2, write
p, data_group_admin, data_group, write
g, alice, data_group_admin
g2, /articles/:id, data_group
this was the model but following policies did not authorized as expected . 
alice", "data1", "read" > permitted 
alice", "data1", "write" > permitted 
alice", "/articles/123", "write" > not permitted .

the second and thrid polices were not right . i mean data1 is not a part of data_group why should it has write access and /articles/123 is inside data_group why does it refuse to grant access . 

![Screenshot from 2020-04-25 21-44-35](https://user-images.githubusercontent.com/32374993/80308127-61b79000-87e2-11ea-8a6a-a000504be5b3.png)

**Comment by nodece** [comment]
The follow is my test:

`"alice", "data1", "read"` -> `true`
allow:  `p, alice, data1, read`

`"alice", "data1", "write"` -> `false`
deny:  cannot found `data1` in `g2`

`"alice", "/articles/123", "write"`  -> `true`
allow: `p, data_group_admin, data_group, write` + `g2, /articles/:id, data_group`

**Comment by ghaedi93** [comment]
yeah my bad i had tampered a few policies in database , its all working fine with simple .csv strategy, 
thanks . 
im not that good in JS but i like opensource projects, idk know how it works but i would like to contribute to casbin . if possible let me know to discuss over it . thanks 
ghaedi1993@gmail.com

**Comment by nodece** [comment]
Thanks @ghaedi93 , [Casbin](https://casbin.org/) welcomes your contribution.

contact: 
- https://gitter.im/casbin/gsoc

**Comment by nodece** [comment]
Thanks @ghaedi93 , [Casbin](https://casbin.org/) welcomes your contribution.

contact: 
- https://gitter.im/casbin/gsoc

**Comment by ghaedi93** [comment]
thanks ... i joined but it doesnt seem to be active
