### ISSUE TITLE
Loading using Adaptor gives different results

### ISSUE THREAD

**Issue by shlomiv** [casbin/node-casbin#145]
Hi, it must be a silly mistake I am making:

```js
 const enforcer = await newEnforcer('default_model.txt', 'default_policy.txt', true);
 const sub = ...
 const obj = ...
 const act = "read"
 const a = await enforcer.enforce(sub, obj, act); // returns true
```
Succeeds, while loading the adapter separately fails:

```js
 const enforcer = await newEnforcer('default_model.txt', true);

 enforcer.setAdapter(new FileAdapter("default_policy.txt"))
 enforcer.loadPolicy()

 const sub = ...
 const obj = ...
 const act = "read"
 const a = await enforcer.enforce(sub, obj, act); // returns false
```

Any clues?

**Comment by hsluoyz** [comment]
@shlomiv can you provide a full minimized working example? model, policy, no ...

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Hi @shlomiv , I submitted a #146 to fix it.

**Comment by shlomiv** [comment]
Thank you @nodece and @hsluoyz for you very fast response! I did not get the chance to provide a minimized working example :)

I will check the fix and update you.

**Comment by shlomiv** [comment]
Hi, thanks for the fix, but it does not seem to work in my env.

I tested the following using the [basic model](https://github.com/casbin/casbin/blob/master/examples/basic_model.conf) and [basic policy](https://github.com/casbin/casbin/blob/master/examples/basic_policy.csv) from:

```typescript
import { newEnforcer, FileAdapter } from 'casbin'

async function test() {
const enforcer = await newEnforcer('basic_model.conf', 'basic_policy.csv', true);

const sub = 'alice'
const obj = 'data1'
const act = 'read'

const res = await enforcer.enforce(sub, obj, act);
console.log(res) // false
}

test().then().catch(err => {
  console.error(err)
})
```

```typescript
import { newEnforcer, FileAdapter } from 'casbin'

async function test() {
const enforcer = await newEnforcer('basic_model.conf', true);
enforcer.setAdapter(new FileAdapter('basic_policy.csv'))
enforcer.loadPolicy()

const sub = 'alice'
const obj = 'data1'
const act = 'read'

const res = await enforcer.enforce(sub, obj, act);
console.log(res) // true
}

test().then().catch(err => {
  console.error(err)
})
```

**Comment by nodece** [comment]
@shlomiv We will merge #146  as soon. It works fine.

**Comment by shlomiv** [comment]
Sounds good! Please let me know when it is pushed so I could `npm install` it and give it a shot. Thanks!

**Comment by nodece** [comment]
@shlomiv I publish a pre-release version.

You can `npm install casbin@4.5.0-0 --save` to get it.

**Comment by shlomiv** [comment]
I don't know what to say :| 
I deleted node_modules, ran the command above followed by `npm install`, and ran the test again. With adapter I get `false`, with policy in enforcer constructor function I get `true`..

Perhaps tomorrow I will make a repo with this problem, and link it here so you could see..

**Comment by nodece** [comment]
@shlomiv I got it.  `enforcer.loadPolicy()` returns `Promise<void>`, you lost `await`.

**Comment by shlomiv** [comment]
Oh, of course! 🤦‍♂️ 

Yep, it works, thanks @nodece

**Comment by hsluoyz** [comment]
Merged: https://github.com/casbin/node-casbin/pull/146

**Comment by nodece** [comment]
@shlomiv `v4.5.0` has been published.

Thanks for your report.
