### ISSUE TITLE
enforceSync & loadPolicySync for non async sources.

### ISSUE THREAD

**Issue by georgiee** [casbin/node-casbin#152]
Hello,
thank you very much for this powerful piece of software. I read the PML paper with pleasure. It does describe the concept very clear and by doing that even helps to explain the main differences of ABAC/RBAC/ACL. I'm impressed, thank you! 💪

I would like to use the core parts (Enforcer & Model) for a frontend project. For this I don't need any async handling yet. The model is defined in code and the policy is loaded from a string. That's it. I expected to find sync variations for `enforcer.enforce` or for `enforcer.loadPolicy`. This would reduce the runtime complexity as I don't have any async sources involved.

The underlying `fs` supports sync file access, so a generalized `loadPolicySync` and `enforceSync` should be possible. The DB adapters could have the same but I don't have the bigger picture to judge this. 

What do you think?

**Comment by nodece** [comment]
Sounds good, I also consider the question, but have many async action like fetch policy from database, so can only provide an async method.

**Comment by georgiee** [comment]
Yes a network connection like the database can't ever be sync. You could throw an explaining error for unsupported adapters. The sync method implementation would throw an error in unsupported methods, something like this:

> This database adapter doesn't support sync calls, please use the asynchronous invocation. 

Honestly, I  did not see software that would bail out like this. But a clear documentation combined with a responsible API consuming developer would make this still a nice addition.

**Comment by nodece** [comment]
I don't think it's a good idea to support both sync and async method.

We can't avoid `callback` or `promise` in JavaScript.

**Comment by georgiee** [comment]
Alright & understood. Works of course with async, I just wondered about this variation. Thanks! Closing this issue.

**Comment by hsluoyz** [comment]
For front-end, you can use: https://github.com/casbin/casbin.js

**Comment by georgiee** [comment]
Hello @hsluoyz,
I'm already using casbin successfully. I wondered about a sync access not because of using JavaScript in the browser which can handle async requests without any problems. It's just that the async introduces a complexity that is not trivial in some edge cases where it could be easier with sync (provided that all involved models & policies are sync too).

In my concrete case I integrate it in Angular. The built-in Angular Change Detection requires a stable value coming back from `enforcer.enforce` otherwise you end up in an infinite refresh loop as the microtask queue will never drain. enforcer.nforce always returns a new Promise so it can't be used directly.

My solution for this is to memoize the enforce call through observables which works — but I always imagine that this could be replaced with a sync method from the enforcer instead.

---

I leave this for people that might run into the same issue:

```ts
/** In a Service or Component */
enforcerCache: Map<string, Observable<boolean>> = new Map();

memoizedEnforceCall(...args) {
    const cacheKey = args.join('-');
    if (!this.enforcerCache.has(cacheKey)) {
      const result$ = fromPromise(this.enforcer.enforce(...args)).pipe(shareReplay(1));
      this.enforcerCache.set(cacheKey, result$);
    }
    return this.enforcerCache.get(cacheKey);
}

// access it like this
canFoo$(attribute) {
    return this.memoizedEnforceCall('some-role', attribute, 'foo');
 }
```

In the template I can now resolve the value without any loop as the cache and the replace makes sure always the same value is returned.

```html
// In the template you can then use the async pipe
{{canFoo$('myAttribute') | async}}
```

**Comment by fgblomqvist** [comment]
I'm also interested in this and curious about the decision-making around this. I can understand that there's an overhead to maintaining both a sync and async API but without a sync API the workflow for Casbin in the browser becomes significantly more cumbersome. The most common usage would most likely be conditional rendering, but with frameworks like React, it's not as simple as just saying `await enforcer.enforce(...)`. You'll need to add extra state/hooks etc. anywhere you want to use the enforcer (which is most likely in a lot of places).

Now, it seems like things were made async just because there's a chance you might use either 1. an adapter/role manager that is async or 2. a matcher function that is async.

When running Casbin in the browser for a web app, I'd guess that the most common use case does not involve any of those. You'll probably get a part of the policy along with the model from the back-end and then initialize an enforcer with those (as strings).

It's obviously not as simple as a one-liner to add the ability to support both sync and async, but I'd argue that it would still be worth the work. Perhaps a starting point would be to expose a `SyncRoleManager` and allow the CoreEnforcer to have either a `RoleManager` or a `SyncRoleManager`. Then a `enforceSync` could be added (that would throw an error if the role manager isn't sync). And so forth.

**Comment by hsluoyz** [comment]
@fgblomqvist why not use: https://github.com/casbin/node-casbin/blob/master/src/syncedEnforcer.ts ?

**Comment by fgblomqvist** [comment]
Because all of its methods are still async. It's not a synchronous enforcer, it's one that ensures that the operations are happening in a serialized fashion (using a murex).

**Comment by hsluoyz** [comment]
@fgblomqvist what about add a new `SyncEnforcer` class to wrap all methods with sync API (like await and promise) ?

**Comment by fgblomqvist** [comment]
No unfortunately not. In JavaScript, once you use async/await every single caller and their callers will have to also be async. Which means that if you want a non-async API, every function you call needs to be non-async. Therefore, as I mentioned you'd need a RoleManager interface that's synchronous (like it used to be a little more than a year ago) and then support that. Once that gets done, you might as well switch the DefaultRoleManager to implement the synchronous interface instead and then that solves the bulk of the problem.

**Comment by georgiee** [comment]
I just wanted to give a perspective how we proceeded as our business needs did not magically disappear with the knowledge that casbin will not work as a sync library. I also see and respect the maintainers decision not to support real sync usage. We are currently not able to opensource our solution but we want to go that direction with our client. Until then this is maybe a motivation to build your own engine. Yes it was a lot of work and a lot of reading but it was a fun journey with great success. Trust your cherry picking skills to extract the parts from casbin you need to get started pretty quickly into a sync world of policy evaluation before being stuck 💪 

I'm still very thankful to casbin that they opened up the world of ABAC, ACL & friends to me with the code base being open source and very readable.

---

Here our story so far:

1. We cherry picked the crucial parts from casbin and build our own minimal engine with it but being sync in the core (parser, enforcer) and expose (optional) async capabilities only in the querying API (for sync or async canShow, canEdit etc, see https://github.com/casbin/node-casbin/issues/152#issuecomment-625063934). I wrote this myself within a few days. I could not find any valid alternative to casbin. I encourage you to go this route if you feel being stuck with some async/sync workaround or searching for too long for another solution.

2.  We relied on the enforcer, the policy parsing and we cherry picked only those parts from the flexible casbin model/policy building we needed. We have no interest in changing our policy model frequently. This solution worked good enough to validate that we are going into the right direction of having a ABAC-like policy in the frontend to orchestrate our business needs (mostly view & edit capabilities).

3. Fast forward 6 months. People happily adapted our small library. We improved it on the API/consuming side and also offered some great policy editing UI to modify the policy during development like add/remove or disable/enable rules, change actions & resources or change the order of rules.

4. The casbin legacy code begun to stand in our way. We decided to ditch it entirely and use our gained knowledge to provide a proper rewrite without any leftovers from casbin. We did that on the basis of the XACML standard outlined here: http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html.

It's such a great document. It's very readable and it helped us to shape our library with a naming system people can following just by understanding the written standard. 
+ We have incoming "Decision Requests" from anywhere in the applications. 
+ We introduced a central `PDP` (Policy Decision Points)  which holds our policy and is the central point to evaluate those requests and transform it into `Decisions`
+ We have an `expression engine` (as defined in XACML) to define expressions in the policy that are evaluated during runtime. This opened up the world for conditional rules depending on some application context values or state changes ( to offer ABAC-like capabilities)

Keep in mind: 
We are shaping the policy usage to use it in the frontend exclusively. This means our policy is not about security (never trust the client) but more about shaping the frontend based on a fixed set of rules in a policy. This also means we can omit many abstractions and generalizations. No policy in policy (like in XACML) or static evaluation model (not semi-configurable as in casbin or as defined in the XACML standard). No XML-based configuration of properties as we can expose what we need directly in code to our developers or even hard-code some decisions.

I hope that helps & motivates you 🙏

**Comment by fgblomqvist** [comment]
@georgiee Wow thank you for the detailed write-up, sounds like quite the adventure! I do feel quite motivated to do something about the situation, but I'm leaning towards aiding Casbin in offering support for a sync API alongside their async API. Doing that in the proper fashion should be a fun little project that I hope to have time for sometime in the near future. Unfortunately we don't have the capacity or big enough need to where we'd build a custom engine completely from scratch just yet, but I'm sure your post and its references will be found useful by many more people that end up here 😄
