### ISSUE TITLE
getPermissionsForUser  will always return repeated once array

### ISSUE THREAD

**Issue by xianjiezh** [casbin/node-casbin#154]
I want to get all permissions for one role

here is the datas I set in mysql casbin_rule table

![image](https://user-images.githubusercontent.com/23073197/81396674-68d28c80-9158-11ea-8da4-a3cb0cdbf8b2.png)

I want to get all permissions from 'role:1'

then vscode auto prompted methd `getPermissionsForUser `

I use it like 

```
    const rolePermissions = await this.enforcer.getPermissionsForUser('role:1');
```
It returns a repeated once array
```
[
  [ 'role:1', 'SUBMIT_TRAINING_JOB' ],
  [ 'role:1', 'CREATE_VC' ],
  [ 'role:1', 'EDIT_VC' ],
  [ 'role:1', 'DELETE_VC' ],
  [ 'role:1', 'USE_VC' ],
  [ 'role:1', 'VIEW_ALL_USER_JOB' ],
  [ 'role:1', 'MANAGE_ALL_USERS_JOB' ],
  [ 'role:1', 'VIEW_CLUSTER_STATUS' ],
  [ 'role:1', 'MAGAGE_USER' ],
  [ 'role:1', 'SUBMIT_TRAINING_JOB' ],
  [ 'role:1', 'CREATE_VC' ],
  [ 'role:1', 'EDIT_VC' ],
  [ 'role:1', 'DELETE_VC' ],
  [ 'role:1', 'USE_VC' ],
  [ 'role:1', 'VIEW_ALL_USER_JOB' ],
  [ 'role:1', 'MANAGE_ALL_USERS_JOB' ],
  [ 'role:1', 'VIEW_CLUSTER_STATUS' ],
  [ 'role:1', 'MAGAGE_USER' ]
]
```
it is repeated since 'SUBMIT_TRAINING_JOB'

I dont find api `getPermissionsForUser  ` in documentation, so I click to the souce code and find it was implement by getFilteredPolicy in row 257:
https://github.com/casbin/node-casbin/blob/cce5354731f0b709ee4d96009363392574a80059/src/enforcer.ts

I try api `getFilteredPolicy ` but get a same result

here is my model.conf

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

**Comment by GopherJ** [comment]
Could you describe also which enforcer are you using and do you have couster(multiple process)

**Comment by xianjiezh** [comment]
thanks  @椰子

it was because before loadpolicy, 

```
enforcer.initWithAdapter(casbinModelPath, (adapter as any) as Adapter);
await enforcer.loadPolicy();
```

I dont wait in initWithAdapter 
it was correct when  await initWithAdapter

``` 
await enforcer.initWithAdapter(casbinModelPath, (adapter as any) as Adapter);
await enforcer.loadPolicy();
```

**Comment by xianjiezh** [comment]
> Could you describe also which enforcer are you using and do you have cluster(multiple process)
@GopherJ 
Thank you, I just solved the problem.
