### ISSUE TITLE
getImplicitRolesForUser returns duplicates

### ISSUE THREAD

**Issue by somq** [casbin/node-casbin#156]
Hi there,

It's missing the `arrayRemoveDuplicates` in [getImplicitRolesForUser](https://github.com/casbin/node-casbin/blob/master/src/enforcer.ts#L282) like it is in `getImplicitUsersForPermission`

**Repro steps**:

1) Add roleA to roleB
2) Add roleB to user
3) Add roleA to user

> getImplicitRolesForUser will return `[ 'roleA', 'roleA', 'roleB' ]  

is it an intended behaviour?

Thanks for your answers

**Comment by GopherJ** [comment]
ok seems like it's because that the last time I would like to have

g, *, book_admin

getImplicitRolesForUser("*") to return back

["*",  "book_admin"]

;)

I'm confused here

**Comment by GopherJ** [comment]
To fix we can change:
 const res = new Set<string>();
to
 const res = new Set<string>();
res.add(name)

I'm a little bit about the behavior here;) can someone point out the correct behavior?

**Comment by GopherJ** [comment]
are u  using the latest version?

If it's https://github.com/casbin/node-casbin/blob/master/src/enforcer.ts#L282,
it seems the output will only be:

[RoleA, RoleB]

**Comment by GopherJ** [comment]
The previous version:


const res: string[] = [];
    const roles = await this.rm.getRoles(name, ...domain);
    res.push(...roles); // Role A, RoleB

    for (const n of roles) {
      const role = await this.getImplicitRolesForUser(n, ...domain);
      res.push(...role); // RoleA, RoleB, RoleA
    }

    return res;

**Comment by somq** [comment]
Hi @GopherJ , I tested with v4.7.2 and you are right, I was running v4.2.1 for some reason.
My apologies, closing this one.
