### ISSUE TITLE
Support Node, Deno, Browser in the same repo

### ISSUE THREAD

**Issue by zhmushan** [casbin/node-casbin#163]
### Motivation
- **Share most of the code**: We don’t need to update the same code multiple times.
- **Concentrated community**: The same problem may occur on different platforms (because they almost use the same code). It is more convenient to discuss in the same repo.

### Design
First, we should strip out code that only uses `javascript`. (no dom API, no node API...)
Then write platform-specific code in their respective folders.
Finally, use a unified entry to dynamically load module according to the user's platform. (For Deno, we can export esmodule and then import it through pika's cdn)

To do all of the above, we can rename the repo to casbin.js

**Comment by hsluoyz** [comment]
I agree with this idea, we don't keep multiple copies of the same code. The only issue here is that the casbin.js name is taken by the "Casbin frontend" project for now: https://github.com/casbin/casbin.js

**Comment by zhmushan** [comment]
We can move it to the browser directory of this repo (because this repo has more stars

**Comment by nodece** [comment]
Fantastic! But because casbin.js repository used, so I suggest use the node-casbin repository to support deno, node and web.

**Comment by hsluoyz** [comment]
There's no need to enforce the full functionalities of Casbin in browser except Casbin editor. So the name of "Node-Casbin" is still not that bad. This repo already took the "casbin" name in NPM, so the GitHub repo name is actually not important. We will keep it this way for now, until things change a lot in future.

For Deno, we can still keep the Deno-Casbin repo but inside it we import Node-Casbin as dependency. So Deno-Casbin is just a wrapper of Node-Casbin.

**Comment by fgblomqvist** [comment]
Does node-casbin work in the browser? Or does it rely on node-specific APIs?

**Comment by hsluoyz** [comment]
@fgblomqvist yes, we use Node-Casbin to power the online editor: https://github.com/casbin/casbin-editor

**Comment by transtone** [comment]
> @fgblomqvist yes, we use Node-Casbin to power the online editor: https://github.com/casbin/casbin-editor

@hsluoyz 你认真的吗？https://github.com/casbin/casbin-editor/blob/master/package.json#L9 明明依赖的是 `casbin.js`

**Comment by nodece** [comment]
@transtone node-casbin and casbin.js can be used in browser, you can check out this PR: https://github.com/casbin/casbin-editor/commit/56211377d010705b214182af04b64e94888e3165.

**Comment by transtone** [comment]
> @transtone node-casbin and casbin.js can be used in browser, you can check out this PR: [casbin/casbin-editor@5621137](https://github.com/casbin/casbin-editor/commit/56211377d010705b214182af04b64e94888e3165).

感谢回复。上文特别指出 casbin.js 库，是发现官方对js前后端支持的方案有了些许变化，从一个库适配多端，变成了多端分别适配，这是往后对 js 支持的发展思路吗？

**Comment by hsluoyz** [comment]
Hi @transtone we are an international open-source community. Please change all your text into English to make everyone read the text easily.

**Comment by nodece** [comment]
@transtone casbin.js doesn't include node API, it can be used in any javascript platform.

**Comment by transtone** [comment]
> Hi @transtone we are an international open-source community. Please change all your text into English to make everyone read the text easily.

罗杨博士，很感谢您的这个项目对开源的贡献。语言这个事这个见仁见智吧，用中文的人基数可能更大一些，对那些英文不流畅的开发者，是否可读性更高？

**Comment by hsluoyz** [comment]
@transtone sorry but this is the rule for our community (at GitHub). Anyone can write articles, can host the docs, can make tutorial videos and can fork the code anywhere with any language. But at our GitHub, we officially only use English. If a second language is allowed here, people will want a 3rd language, 4th one, 5th, there's no end. People won't want to use our code any more when he sees 20+ languages mixed in our repo.

**Comment by nodece** [comment]
@transtone I made a PR for casbin.js: https://github.com/casbin/casbin.js/pull/227, this PR for deno prepare, could you review this PR?
