### ISSUE TITLE
Don't load policy on enforcer creation

### ISSUE THREAD

**Issue by vinverdy** [casbin/node-casbin#168]
what a great library for authorization. 

but i wanna ask what is the reason behind automatically load policy on [enforcer creation](https://github.com/casbin/node-casbin/blob/1a6cf5e8f6e620d13bfb211362100c79db5e0dfc/src/enforcer.ts#L71)? because when our saved policy count increasing, it will slow down continually. thanks

https://github.com/casbin/node-casbin/blob/1a6cf5e8f6e620d13bfb211362100c79db5e0dfc/src/enforcer.ts#L57-L73

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by nodece** [comment]
@vinverdy I don't understand your mean.  When you call newEnforcer, it will automatically load policy from adapter.

**Comment by vinverdy** [comment]
sorry for late response, can i change that behaviour? i dont want load policy on newEnforcer creation. because i want to create newEnforcer every user request.

my concern is if there is many concurrent request, my memory will be used too much.

**Comment by nodece** [comment]
I recommend to use factory with mutex lock to create newEnforcer. It can limit the concurrent request.

**Comment by vinverdy** [comment]
I see. So, cmiiw, i cant lazily load my policy?

**Comment by vinverdy** [comment]
maybe another use case. I just want to use loadFilteredPolicy instead of loadPolicy for my enforcer?

**Comment by nodece** [comment]
Hi @vinverdy , I have a good idea, you can call newEnforcer without adapter then to set adapter and load policy.

**Comment by vinverdy** [comment]
thanks @nodece , I have tried your idea and its working. But I think, its a hackish way to do that and adapter on enforcer is protected. But, if its working as intended, I will close this issue. Thanks a lot for your help

**Comment by ccatterina** [comment]
> But I think, its a hackish way to do that and adapter on enforcer is protected.

I think the same way as @vinverdy. +1 for an option to skip policy load on enforcer creation.

**Comment by hsluoyz** [comment]
@ccatterina why do you want to skip policy load?

**Comment by ccatterina** [comment]
Hi @hsluoyz , mainly because I want to load only a subset of the policy with `loadFilteredPolicy` and I don't like the idea of waste time/resources loading the entire policy uselessly.

Note: I'm planning to use casbin with AWS serverless lambda so I need to reload the policy in every call and I wanna load only a subset of the policy to reduce memory usage and time spent.

**Comment by hsluoyz** [comment]
@vinverdy we can add the optional 3rd arg `bool lazyLoad = false` to:

https://github.com/casbin/node-casbin/blob/1a6cf5e8f6e620d13bfb211362100c79db5e0dfc/src/enforcer.ts#L57-L73

Default value would be false, but you can set it to true. Does this sound OK?

**Comment by ccatterina** [comment]
It's ok for me! Thanks

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403 @MRGUOKING
