### ISSUE TITLE
Enforcer `enforceWithSyncCompile` method does not work with `g` model definition value

### ISSUE THREAD

**Issue by StefanoPastore** [casbin/node-casbin#170]
## Cause
I encountered this problem during an investigation about performance problems.

## Problem
I noticed that if i put inside a `Promise.all` list of enforce it took more time than one alone, so i tried to use `enforceWithSyncCompile` method, but it doesn't work properly when there is `g` definition value in model.

## Solution
After some research i found the problem: `DefaultRoleManager.hasLink` is defined as async function, but it doesn't do any async operations (maybe i lost something), the only one that i found as async is `generateGFunction` but it doesn't do any async operations too, this is why `enforceWithSyncCompile` doesn't work only with `g` before `||` operator.
If i change these method as sync always it works properly.

## Example
```js
const casbin = require("casbin");

const casbinModel = new casbin.Model();
casbinModel.addDef('r', 'r', 'subject, object, action');
casbinModel.addDef('p', 'p', 'subject, object, action');
casbinModel.addDef('g', 'g', '_, _');
casbinModel.addDef('e', 'e', 'some(where (p.eft == allow))');
casbinModel.addDef('m', 'm', 'g(r.subject, "root") || (g(r.subject, p.subject) && r.object == p.object && r.action == p.action)');

const policy = `
p, test, example, read
g, user, test
`;

async function test() {
  const adapter = new casbin.StringAdapter(policy);
  const enforcer = await casbin.newEnforcer(casbinModel, adapter);

  try {
    const test = await enforcer.enforceWithSyncCompile('user', 'example', 'read');
    console.log(test);
  } catch (e) {
    console.error('Error during enforceWithSyncCompile', e);
  }

  process.exit(0);
}

test();
```
Result:
```
Error during enforceWithSyncCompile Error: matcher result should be boolean or number
    at Enforcer.<anonymous> (/Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:344:35)
    at Generator.next (<anonymous>)
    at /Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:17:12)
    at Enforcer.privateEnforce (/Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:267:16)
    at Enforcer.<anonymous> (/Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:415:25)
    at Generator.next (<anonymous>)
    at /Users/stefanopastore/git/topconagriculture/ta-platform/ta-profile-manager-service/node_modules/casbin/lib/coreEnforcer.js:21:71
    at new Promise (<anonymous>)
```

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by nodece** [comment]
@StefanoPastore please use `enforce` instead.

**Comment by nodece** [comment]
`enforceWithSyncCompile` can only be used for ACl.

This is `enforceWithSyncCompile` notes: 
>if the matchers does not contain an asynchronous method, call it is faster.

**Comment by StefanoPastore** [comment]
@nodece Thank you a lot for the explination!

I noticed that if i change [defaultRoleManager.hasLink](https://github.com/casbin/node-casbin/blob/master/src/rbac/defaultRoleManager.ts#L199) and [generateGFunction](https://github.com/casbin/node-casbin/blob/master/src/util/builtinOperators.ts#L235) without async annotation it will works properly, them are necessary as async for some reason that i don't know right now?

**Comment by nodece** [comment]
you can checkout https://github.com/casbin/node-casbin/issues/46 for details.
