### ISSUE TITLE
Multiorganization / realm for roles access policies

### ISSUE THREAD

**Issue by hackerunet** [casbin/node-casbin#172]
Hi there, I'm wondering if is possible to have multiple permissions created for multiple organizations or realms?, let's say we have a multiuser multicompany system and I want to create roles and permissions for the ecosystem and for each company separately.
The condition would be I can create different roles and permissions over same activities but for multiple companies:
```
Company A=>
                Role A
                Role B
                Role C: activity 1, 2, 3
Company B=>
                Role A
                Role B: activity 1
                Role C: activity 2, 3
Role name A = Role name B
Company  A != Company B
Users A != User B```

**Comment by nodece** [comment]
Hi @hackerchai , it looks like you need https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf.

**Comment by hackerchai** [comment]
> Hi @hackerchai , it looks like you need https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf.

Maybe you should @hackerunet ?

**Comment by nodece** [comment]
sorry @hackerchai , I should cc @hackerunet .

**Comment by hsluoyz** [comment]
Closed as stale.
