### ISSUE TITLE
batchAdapter.removePolicies is not a function

### ISSUE THREAD

**Issue by EndersonPro** [casbin/node-casbin#177]
I am implementing node-casbin in the company project, I require to be able to remove policies using the removePolicies method, however I present the following error batchAdapter.removePolicies is not a function, any help for this?

reviewing the enforce instance I see that the method is implemented, so I don't know what happens.

I would greatly appreciate your help

**Comment by hsluoyz** [comment]
@nodece @zhmushan please answer it.

**Comment by zhmushan** [comment]
Please provide your minimum recurrence @EndersonPro

**Comment by nodece** [comment]
You are using adapter that not implement batchAdapter, I will fix the check in our codebase.

**Comment by hsluoyz** [comment]
@EndersonPro fixed in: https://github.com/casbin/node-casbin/pull/182
