### ISSUE TITLE
Problems deleting roles

### ISSUE THREAD

**Issue by EndersonPro** [casbin/node-casbin#180]
Greetings, I am currently using node-casbin, when wanting to delete a role I ran into a problem, I need to delete a role per domain, I am using the RBAC model with domains.

But when using the `deleteRole` method, the role is deleted from the database, however when I consult from my api, it seems that it is still there. Can you help me with these points?

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by nodece** [comment]
@EndersonPro Could you provides the example code?

**Comment by EndersonPro** [comment]
I have the following method within a service.

`async deleteRoles (roles = [], company) {
        try {
            if (Array.isArray(roles) && roles.length) {
                let i = 0;
                for (i; i < roles.length; i++) {
                    await this.enforcer.deleteRole(roles[i]);
                }
            } else throw new Error('Roles is not array or is empty');
        } catch (error) {
            this.handleErrorService(error);
        }
    }`
When checking in the db I verify that it has indeed been deleted, but when I consult an endpoint to return all permissions of a role, it still exists.
using `this.enforcer.getFilteredPolicy(0, rol, company);`

and I would like to be able to delete roles from a domain, I could use for example
`this.enforcer.deleteRole(roles[i], domain);`

**Comment by nodece** [comment]
Are you running Casbin in cluster environment?  or do you have multiple Casbin instances?

currently, Node-Casbin doesn't delete role with domain, don't worry, we are going to plan support it.

**Comment by EndersonPro** [comment]
@nodece Yes, I'm using casbin in aws lambda, reading I found that I may have to implement Watcher, however I don't know if there is another solution.

On the other hand, thank you for having the account requested, for the moment solve it by filtering the police by domain and eliminating them with.
`getFilteredPolicy` `removePolicy`

**Comment by nodece** [comment]
When you have multiple Casbin instances,  you must use Watcher to sync other Casbin instances.

**Comment by EndersonPro** [comment]
@nodece thanks for your reply.
