### ISSUE TITLE
pubsub-watcher

### ISSUE THREAD

**Issue by elaijuh** [casbin/node-casbin#183]
Currently there are only redis-watcher and etcd-watcher for NodeJS. Since my project is using pub/sub, I would like to contribute a GCP pub/sub watcher.

**Comment by hsluoyz** [comment]
Hi @elaijuh . We are happy to see the projects from contributors. Where's the code?

**Comment by elaijuh** [comment]
I will share the code once it's been tested working.

**Comment by hsluoyz** [comment]
@elaijuh thanks!

**Comment by elaijuh** [comment]
https://github.com/elaijuh/casbin-pubsub-watcher

Here is the repo

**Comment by hsluoyz** [comment]
Moved to here: https://github.com/node-casbin/pubsub-watcher

Thanks for your contribution!
