### ISSUE TITLE
Hi team, great plugin  I was wondering it's there a way to manage all permissions in a centralized service?

### ISSUE THREAD

**Issue by jordicuevas** [casbin/node-casbin#185]
is it possible to instead having multiple instances of casbin, manage all permissions in a centralized service and force all other foreign services to query permissions in the centralized casbin instance each time a role or permission validation is required? **

**Comment by hsluoyz** [comment]
Hi @jordicuevas , you can use `Casbin as a service`: https://casbin.org/docs/en/service . They are mostly in Go, as it doesn't matter for a standalone service.

For front-end UI, you can also integrate `Casbin Dashboard`: https://github.com/casbin/casbin-dashboard

**Comment by nodece** [comment]
Closed: not active for too long.
