### ISSUE TITLE
Model definitions can degrade performances

### ISSUE THREAD

**Issue by StefanoPastore** [casbin/node-casbin#189]
Hi there!

We had performance issues on enforce policy, after some research i noticed that if i remove a check from my model the enforce improve its performance of ~20ms.

My model is:
```js
const casbin = require("casbin");

const casbinModel = new casbin.Model();

casbinModel.addDef('r', 'r', 'subject, domain, object, action');
casbinModel.addDef('p', 'p', 'subject, domain, object, action');
casbinModel.addDef('g', 'g', '_, _, _');
casbinModel.addDef('e', 'e', 'some(where (p.eft == allow))');
casbinModel.addDef('m', 'm', 'g(r.subject, "root", "tenantId") || (g(r.subject, p.subject, r.domain) && r.domain == p.domain && r.object == p.object && r.action == p.action)');
```

If i replace last def with this:
```js
casbinModel.addDef('m', 'm', 'g(r.subject, p.subject, r.domain) && r.domain == p.domain && r.object == p.object && r.action == p.action');
```

The enforcer will perform enforces in almost half time than first one.

I need the `g(r.subject, "root", "tenantId")` because it allow root in a specific tenant to be allowed to every policy cross tenant, there is a better way to handle this or I have to handle it in my business logic?

**Comment by nodece** [comment]
I don't have better way.

**Comment by nodece** [comment]
I submitted a PR to improve performances: #191.

**Comment by guglielmino** [comment]
Since you are implementing the C/C++ lib, is it possible to use it as binding for the JavaScript module? It should be possible using the Node.js N-API (https://nodejs.org/api/n-api.html)

**Comment by nodece** [comment]
@guglielmino sounds great, but node-casbin can support the any pure JavaScript project, if we are using the Node.js N-API, it just supports Node.js project.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/node-casbin/pull/191
