### ISSUE TITLE
How to query all users in a specific domain by roleId?

### ISSUE THREAD

**Issue by family2hu** [casbin/node-casbin#192]
## background
For data isolation , I want to get all users by roleId in a specific domain

## current method
When I don't care about domain, I just use the 'GetUsersForRole' api to get all users, and I see this api can pass domain params in condition of the domain being a prefix to the users. But in reality, the domain is mostly a separate field.
So I have to use the 'GetAllNamedRoles' api and filter users by myself, which is not elegant and will lead performance problem.

## hope
Provide a direct api to get all users in a specific domain by roleId which can pass the domain keyId(eg.v3) or the index of policy(eg.4) in addition of roleId. 
Thanks!

**Comment by nodece** [comment]
@family2hu could you try to calling `getImplicitPermissionsForUser(user/user, domain)`?

**Comment by nodece** [comment]
Closed: not active for too long.
