### ISSUE TITLE
Policy logging affecting performance

### ISSUE THREAD

**Issue by murzatayev** [casbin/node-casbin#194]
I have noticed a spike in resources usage when policies are first loaded, then after some investigation I found that this is caused by a call to `printModel()` here: https://github.com/casbin/node-casbin/blob/master/src/model/model.ts#L158

This is especially noticeable for a large number of policies.

Unfortunately, using `enableLog(false)` does not help, because the policies list traversal happens regardless of this flag value.

I think this flag needs to be checked before calling `this.model.printPolicy()` in `coreEnforcer.js`

![Screenshot](https://user-images.githubusercontent.com/674183/93088949-6b239500-f6bc-11ea-90ba-d885dc440dcd.jpg)

![Screenshot (1)](https://user-images.githubusercontent.com/674183/93089315-f1d87200-f6bc-11ea-831b-8138410209b0.jpg)

**Comment by nodece** [comment]
I submitted a patch: https://github.com/casbin/node-casbin/pull/195, could you review the PR?

**Comment by murzatayev** [comment]
@nodece thanks, just checked, the bump is gone now.
