### ISSUE TITLE
Module parse failed: Unexpected token (158:32) with create-react-app

### ISSUE THREAD

**Issue by ravikumarjs-foyernet** [casbin/node-casbin#197]
getting this error working in react typescript application. Please fix it

Module parse failed: Unexpected token (158:32)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   async buildIncrementalRoleLinks(rm, op, sec, ptype, rules) {
|     if (sec === 'g') {
>       await this.model.get(sec)?.get(ptype)?.buildIncrementalRoleLinks(rm, op, rules);
|     }
|   } // buildRoleLinks initializes the roles in RBAC.

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by zhmushan** [comment]
Please provide a minimum recurrence

**Comment by nodece** [comment]
Please add https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining babel plugin to your project.

**Comment by ravikumarjs-foyernet** [comment]
not working...

**Comment by ravikumarjs-foyernet** [comment]
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining is working with our code, but not working with node-casbin.

**Comment by hsluoyz** [comment]
@ravikumarjs-foyernet can you provide a minimized reproducible example as a GitHub repo?

**Comment by ravikumarjs-foyernet** [comment]
https://github.com/ravikumarjs-foyernet/rbac.git

**Comment by hsluoyz** [comment]
@zhmushan can you try this? https://github.com/ravikumarjs-foyernet/rbac

**Comment by nodece** [comment]
@hsluoyz I'm working on it.

**Comment by nodece** [comment]
I don't know why your project doesn't work. same code, my project is working.

The following is my command:

```
yarn create react-app my-app --template typescript
cd my-app
yarn add casbin
```

then add the following code to your project:
```ts
import {newEnforcer,newModelFromString,StringAdapter} from 'casbin';

const m = newModelFromString(`
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
`)

const a = new StringAdapter(`
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
g, alice, data2_admin
`)

newEnforcer(m,a).then(async e=>{
  console.log(await e.enforce('alice','data2','read'))
}).catch(console.error)
```

yarn start
```
Compiled successfully!

You can now view my-app in the browser.

  Local:            http://localhost:3001
  On Your Network:  http://192.168.1.92:3001

Note that the development build is not optimized.
To create a production build, use yarn build.
```

**Comment by ravikumarjs-foyernet** [comment]
Your code working fine.

**try this**
```
npm install -g create-react-app
create-react-app my-app
```
add your code then run `npm start`

**Comment by ravikumarjs-foyernet** [comment]
Hi @nodece,

In your project remove the yarn.lock and node-modules then run `yarn` command.

run `yarn start`

then you will get this error
```
./node_modules/casbin/lib/esm/model/model.js 158:32
Module parse failed: Unexpected token (158:32)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   async buildIncrementalRoleLinks(rm, op, sec, ptype, rules) {
|     if (sec === 'g') {
>       await this.model.get(sec)?.get(ptype)?.buildIncrementalRoleLinks(rm, op, rules);
|     }
|   } // buildRoleLinks initializes the roles in RBAC.
```

**Comment by zhmushan** [comment]
@ravikumarjs-foyernet It should be that your nodejs version is too old, I have no problem using v12

**Comment by ravikumarjs-foyernet** [comment]
@zhmushan my nodejs version is 12.18.4

**Comment by ravikumarjs-foyernet** [comment]
@nodece any idea?

**Comment by zhmushan** [comment]
@ravikumarjs-foyernet This is a bug in `cra`, a temporary solution:
```ts
import {newEnforcer} from'casbin/lib/cjs';
```

**Comment by ravikumarjs-foyernet** [comment]
@zhmushan not working

**Comment by hsluoyz** [comment]
@zhmushan great. How to fix it in a permanent way then?

**Comment by nodece** [comment]
@ravikumarjs-foyernet I found https://github.com/facebook/create-react-app/issues/8445#issuecomment-588545858 by google searching, the solution is fine.

**Comment by nodece** [comment]
I created a issue in https://github.com/facebook/create-react-app/issues/9749.
