### ISSUE TITLE
What's the storage?

### ISSUE THREAD

**Issue by veotax** [casbin/node-casbin#20]
> It will store the data in mongodb ?
So, how to set the mongodb connecting configuration?
Can I store the data in mysql ?

@linkypi, Node-Casbin supports to store policy data to MySQL, PostgreSQL, SQLite, Microsoft SQL Server, See: https://github.com/casbin/node-casbin#policy-persistence

**Comment by nodece** [comment]
@veotax See [https://github.com/node-casbin](https://github.com/node-casbin)
