### ISSUE TITLE
Can we target to ES2019 instead of ES6?

### ISSUE THREAD

**Issue by waitingsong** [casbin/node-casbin#202]
tsconfig.json 
```json
compilerOptions": {
    "target": "ES6",
｝
```

nodejs's LTS is v12 now, which supports ES2019. Next week v14 will be LTS, which supports ES2020.

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by hsluoyz** [comment]
@waitingsong what can we gain from updating Node.js version to ES2019?

**Comment by zhmushan** [comment]
We have also provided a version of `esnext`. see https://github.com/casbin/node-casbin/blob/master/tsconfig.esm.json
