### ISSUE TITLE
[Question] Using Enforcer to filter for millions of objects

### ISSUE THREAD

**Issue by cooked-sashimi** [casbin/node-casbin#209]
## Configuration file:
```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

The goal is to allow `user=alice` to have admin access all the capture A* and B1 which I have done via:

```js
await Enforcer.addNamedPolicy(
'p',
`capture:capture=captureA1:admin`,
`capture:capture=captureA1`,
'admin'
);

await Enforcer.addNamedPolicy(
'p',
`capture:capture=captureA2:admin`,
`capture:capture=captureA2`,
'admin'
);

await Enforcer.addNamedPolicy(
'g',
`role:role=captureA-admin`
`capture:capture=captureA1:admin`,
);

await Enforcer.addNamedPolicy(
'g',
`role:role=captureA-admin`
`capture:capture=captureA2:admin`,
);

await Enforcer.addNamedGroupingPolicy(
'g',
`user:user=alice`,
`role:role=captureA-admin`
);

await Enforcer.addNamedPolicy(
'p',
`user:user=alice`,
`capture:capture=captureB1`,
`admin`
);

```
 
The goal is to allow this to scale up to millions of policies without latency issues so that I could do something like this to filter the data for `alice`

```js
const allCaptures = await Captures.find({})
const capturesForAlice = []
await Promise.all(allCaptures.map(capture => {
	const isAdmin = await Enforcer.enforce(user:user=alice, capture:capture=captureName) # e.g captureB1 is a captureName
	if (isAdmin) {
		capturesForAlice.push(capture)
	}
}) 
```

I was wondering if there is a better way to filter the data than what I have above as it doesn't make sense that I would need to access the database every time I need to check the permissions for one object, or is this a standard pattern if I want to enforce access on each individual object? I had a look at this issue here: https://github.com/casbin/casbin/issues/634, but it seems like `batchEnforce()` is enforcing on the user, instead of the object. 

Moreover, it is not implemented, is there a workaround for this? One way that I can think of is to use a `filteredAdapter` and then filter for the relevant policies. Even though there are millions of captures, I would be able to filter them down to 1000s if I were to only retrieve the policies that exist for some account for some user.

Then use`getImplicitRolesForUser` and `getPermissionsForUser` and construct a lookup dictionary first, then iterate through the `captures` to check whether or not the key exists in the dictionary, or is there a better approach as the number of policies create would go by a factor of `n_users * n_captures` which doesn't seem scalable.

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@yyellowsun can you help answer this question?

**Comment by nodece** [comment]
@cooked-sashimi It looks like you want to know what permissions `user=alice` has. You can call `getImplicitPermissionsForUser` to got that.

**Comment by yyellowsun** [comment]
@cooked-sashimi  What is capture?
Maybe filteredAdapter is a better way from your description.

**Comment by hsluoyz** [comment]
Moved conversation to: https://github.com/casbin/casbin/issues/617
