### ISSUE TITLE
[Feature] New DynamoDB adapter for NodeJS

### ISSUE THREAD

**Issue by fospitia** [casbin/node-casbin#213]
Hi.

I made a DynamoDB adapter for NodeJS, https://github.com/fospitia/casbin-dynamodb-adapter, this support Auto-Save.

You can add it to the adapter list, please.

Thank you

**Comment by hsluoyz** [comment]
@fospitia thanks for this contribution! Can you make a PR to: https://github.com/casbin/casbin-website to update the adapter list?

**Comment by fospitia** [comment]
@hsluoyz thanks, I will do it

**Comment by hsluoyz** [comment]
Done by: https://github.com/casbin/casbin-website/commit/5228217af718fbd09d1cef8630c90dff4356a398
