### ISSUE TITLE
function keyMatch3 does not match full string

### ISSUE THREAD

**Issue by abichinger** [casbin/node-casbin#214]
https://github.com/casbin/node-casbin/blob/5253b90d104882bd822416c549f2ceda759ccc8f/src/util/builtinOperators.ts#L91

This line is missing `^` and `$`

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@abichinger does Golang Casbin have the same behavior?

**Comment by hsluoyz** [comment]
@nodece @abichinger  why is the Travis CI failing? https://travis-ci.org/github/casbin/node-casbin/jobs/746189398

![image](https://user-images.githubusercontent.com/3787410/100459733-ec59c800-3100-11eb-986b-c120c5a7613b.png)

**Comment by nodece** [comment]
@hsluoyz the job has been restart.

**Comment by hsluoyz** [comment]
I have restarted once, but it failed again.

Is it because the title of this PR doesn't follow semantic-PR?

**Comment by abichinger** [comment]
```
/home/travis/build/casbin/node-casbin/node_modules/coveralls/bin/coveralls.js:19

      throw err;

      ^

Bad response: 422 {"message":"service_job_id (746189397) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}

(Use `node --trace-uncaught ...` to show where the exception was thrown)

The command "jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage" exited with 1.
```
I think the failure of the latest build was caused by the restart. (see https://github.com/ckeditor/ckeditor5/issues/7244)

The first build did not fail until the release stage.

**Comment by nodece** [comment]
@abichinger thanks, I migrated from Travis to GitHub Actions, and it works fine.
