### ISSUE TITLE
RBAZ get list of roles for adomain

### ISSUE THREAD

**Issue by inamvar** [casbin/node-casbin#217]
I have set up "Role definition with domains tenants" model and it works well. I need to get the list of all roles in a domain. `getAllRoles()` returns all roles for all domains that is not what I need. I used `GetFilteredNamedPolicy("p",1, "myDomain")` but the result is not distinct for role name and the role names are repeated in it. is there a pretty way to get list of roles available in a specific domain?

**Comment by inamvar** [comment]
Sorry it was mistake I'm not in NodeJS environment. my question was in Golang.

**Comment by nguyenpc** [comment]
Hi guys,
Looking for the same one.
Is there any similar function in NodeJS Lib?

Thank you.
