### ISSUE TITLE
Will have js-mongodb-adapter ?

### ISSUE THREAD

**Issue by szy0syz** [casbin/node-casbin#22]
项目纯MongoDB开发，想用MongoDB做storage，会考虑出个 “js-mongodb-adapter ”吗？

**Comment by Chalin-Shi** [comment]
@szy0syz Is it waterline orm acceptable？

**Comment by szy0syz** [comment]
@Chalin-Shi  Yes, acceptable, but i like Mongoose ODM 🌝.

If I really need it, maybe I will write a js-mongoose-adapter in the same way as js-sequelize-adapter.

**Comment by Chalin-Shi** [comment]
@szy0syz Awesome, if you do this good job you also can opensource it on our org.

**Comment by juicycleff** [comment]
@hsluoyz I just wrote this https://github.com/juicycleff/casbin-mongodb-adapter
