### ISSUE TITLE
Add UpdatableAdapter interface to Node-Casbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#229]
UpdatableAdapter inteface and `UpdatePolicy()` is introduced by this PR: https://github.com/casbin/casbin/pull/592

**Comment by hsluoyz** [comment]
@17bit

**Comment by Zxilly** [comment]
I would like to tryout this issue.

**Comment by hsluoyz** [comment]
@Zxilly OK for me. But what surprised me is that you also know how to write Node.js code?

**Comment by Zxilly** [comment]
> @Zxilly OK for me. But what surprised me is that you also know how to write Node.js code?

I really `know` lots of programming languages....

**Comment by hsluoyz** [comment]
Awesome!
