### ISSUE TITLE
[Feature Request] Add support for typeorm

### ISSUE THREAD

**Issue by dreamdevil00** [casbin/node-casbin#23]
Is there a plan to support typeorm for policy persistence？

**Comment by nodece** [comment]
@dreamdevil00 Of course we will as soon as possible

**Comment by nodece** [comment]
Now, you can use ```yarn add typeorm-adapter```.

**Comment by dreamdevil00** [comment]
> Now, you can use `yarn add typeorm-adapter`.

Blazing fast！Nice

**Comment by hsluoyz** [comment]
The README has been updated: https://github.com/casbin/node-casbin#policy-persistence
