### ISSUE TITLE
The semantic-release is broken

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#231]
Our CI is GitHub Actions: https://github.com/casbin/node-casbin/actions

Recently we merged a PR: https://github.com/casbin/node-casbin/pull/230

But the new release on both NPM & Github Releases is never coming out, like the previous one: https://github.com/casbin/node-casbin/releases/tag/v5.2.3

We need to fix it.

**Comment by nodece** [comment]
This task status is `Waiting for pending jobs` in Github Actions, but I cannot cancel this task.

**Comment by hsluoyz** [comment]
@nodece that job is just dead. We can just ignore it.

I merged a new PR: https://github.com/casbin/node-casbin/pull/232, but encountered a new issue about semantic-release: https://github.com/casbin/node-casbin/runs/1783266710?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/106124682-4d9c2700-6196-11eb-91e7-f5fbf4f1c91d.png)

**Comment by hsluoyz** [comment]
@17bit plz also take a look.

**Comment by hsluoyz** [comment]
Issue proposed to the expression-eval community: https://github.com/donmccurdy/expression-eval/issues/49

**Comment by hsluoyz** [comment]
After some investigation, it seems that our auto-release was stopped after v5.2.3: https://github.com/casbin/node-casbin/releases/tag/v5.2.3 , right after this PR merging: https://github.com/casbin/node-casbin/pull/222 . So I doubt updating expression-eval to v4.0.0 causes this bug.

The expression-eval community (https://github.com/donmccurdy/expression-eval/issues/49) doesn't know the cause either. So for now, I will revert the expression-eval version to fix it.
