### ISSUE TITLE
Rename the built-in BatchFileAdapter class back to FileAdapter

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#235]
See my comments here: https://github.com/casbin/node-casbin/pull/234#discussion_r571341592

I think first we need correctify the BatchFileAdapter code: rename BatchFileAdapter back to FileAdapter. From now on, FileAdapter will always be called FileAdapter, no matter how many interfaces it has implemented.

https://github.com/casbin/node-casbin/blob/27005f85829f11193cb4ecfd14be5ed6e64ad63c/src/persist/batchFileAdapter.ts#L8-L28

**Comment by Zxilly** [comment]
So we should move the batch functions and update function to FileAdapter?

**Comment by hsluoyz** [comment]
@Zxilly see Go code.

**Comment by nodece** [comment]
@hsluoyz @Zxilly I don't recommend that rename the BatchFileAdapter to FileAdapter, some users may be using this, so we can copy BatchFileAdapter code to FileAdapter, and add `@deprecated` to BatchFileAdapter.

**Comment by hsluoyz** [comment]
@nodece, @Zxilly, good idea, and it can be better:

We keep `BatchFileAdapter` but it's only an alias to `FileAdapter`, maybe by inheriting `FileAdapter` without any new functions. So we don't need to copy code. And we will add `@deprecated` to BatchFileAdapter. So we will not break backward compatibility.

**Comment by Zxilly** [comment]
@nodece @hsluoyz have implemented, plz review
https://github.com/casbin/node-casbin/pull/236/commits/915eff37f7a35d57e19c32145ab5e9c3e59a8459
