### ISSUE TITLE
Trim inputs when adding policy/role

### ISSUE THREAD

**Issue by EladProject** [casbin/node-casbin#238]
I'm using Casbin with Postgres.
I encountered a situation where I use addPolicy/addRoleForUser with parameters that have a whitespace prefix.
The problem is that when the policy is read, you do trim the values so upon next insertion of the same values (duplicate), Casbin
doesn't identify that it's duplicate, resulting in duplicate lines in the DB.

**Comment by hsluoyz** [comment]
@EladProject can you show the trim code? BTW, it's better to trim the spaces by yourself before interacting with Casbin.

**Comment by EladProject** [comment]
@hsluoyz This is what I do as a workaround, but I think consistency is important.
I didn't look at the Casbin code. My findings are empirical:
1) Callins hasPolicy/hasRoleForUser came out false for duplicates
2) Looking at the DB entries I can see the whitespace prefix
3) Calling getPolicy and printing it shows no whitespaces

My current code looks like this:
```
const isPolicyExist = await this.enforcer.hasPolicy(role.trim(), tenant.trim(), product.trim(), resourceType.trim(), sub.trim(), action.trim());

    if (!isPolicyExist) {
      this.enforcer.addPolicy(role, tenant, product, resourceType, sub, action);
    }
    else
      console.log("duplicate policy");
```
I use sequelize adaptor

**Comment by EladProject** [comment]
Also,
According to the docs, addPolicy/addRoleForUser should identify duplicates on it's own and return false in this case, but for me it's no working.

**Comment by Zxilly** [comment]
working on this

**Comment by hsluoyz** [comment]
@closetool plz see if this issue also exsits for Go Casbin.

**Comment by closetool** [comment]
![image](https://user-images.githubusercontent.com/52988625/109770005-f88c7e80-7c35-11eb-9c9d-a054e9d4e84c.png)
![image](https://user-images.githubusercontent.com/52988625/109770124-1d80f180-7c36-11eb-8485-bb6b52ef27a8.png)
this feature depends on adapter implementation, if the `persist.LoadPolicyLine` is used in method `LoadPolicy` (like Gorm Adapter), then there is no white space prefix at runtime.

**Comment by nodece** [comment]
@closetool Have you started coding yet? I have solved this problem yesterday, but I need to add unit tests for this.

**Comment by closetool** [comment]
@nodece no, I just checked it

**Comment by nodece** [comment]
@EladProject @hsluoyz @closetool I made a [PR](https://github.com/casbin/node-casbin/pull/242), could you review this PR?
