### ISSUE TITLE
Experiencing slow performance with the enforcer with a large amount of policies.

### ISSUE THREAD

**Issue by HridayK97** [casbin/node-casbin#239]
I'm using an RBAC Model:

```js
import { newModel } from 'casbin';

const Model = newModel();
Model.addDef('r', 'r', 'sub, obj, act');
Model.addDef('p', 'p', 'sub, obj, act');
Model.addDef('g', 'g', '_, _');
Model.addDef('e', 'e', 'some(where (p.eft == allow))');
Model.addDef(
    'm',
    'm',
    'g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && (r.act == p.act || p.act == "/*")'
);

export default Model;

```

When I'm enforcing with over 20k policies, it takes around 2000 to 4000 ms. Is this expected? Are there any potential issues with the matcher function I'm using?

**Comment by hsluoyz** [comment]
@HridayK97 please see: https://casbin.org/docs/en/performance , post some example policy rules and example enforcement code if problem still exists.

**Comment by hsluoyz** [comment]
Closed as stale.
