### ISSUE TITLE
`Parse content error` when trying multiline model

### ISSUE THREAD

**Issue by hariprasadiit** [casbin/node-casbin#240]
Hello,

Thank you all for awesome library.

I've been trying to get multiline matchers model with functions working without success.

here is my model

```ini
[request_definition]
r = sub, cid, lid, obj, method

[policy_definition]
p = sub, cid, lid, obj, method

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub, p.sub, r.cid+'::'+r.lid) \
&& r.method == p.method \
&& keyMatch(r.cid, p.cid) \
&& keyMatch(r.lid, p.lid) \
&& keyMatch2(r.obj, p.obj) 
```

Looking at the code, [config.ts#145](https://github.com/casbin/node-casbin/blob/3e1fa9d1c3db7f2f6f2d439d170de41487ee827c/src/config.ts#L145) is where error is being thrown.

https://github.com/casbin/node-casbin/blob/3e1fa9d1c3db7f2f6f2d439d170de41487ee827c/src/config.ts#L142-L150

Code checks for presence of `=` in each line, but is that required in every line?
If so, how can I update my above model to workaround this error?

Code seems to have missed handling of possible presence of only functions

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
Could you provide more log?

**Comment by hsluoyz** [comment]
@Zxilly I think this is because Node-Casbin doesn't support multi-line matcher. It's supported by Go: https://github.com/casbin/casbin/issues/105#issuecomment-413397054

So we need to port this feature to Node.js

**Comment by Zxilly** [comment]
@hsluoyz got it,will working on this

**Comment by hariprasadiit** [comment]
#60 this PR seems to have added multiline matcher support but test cases only include lines with `=`

**Comment by Zxilly** [comment]
> #60 this PR seems to have added multiline matcher support but test cases only include lines with `=`

According to your reply,I add a testcase like
```js
  it('should config.get("multi6::m") to equal xxx', function () {
    expect(config.get('multi6::m')).toEqual(
      "g(r.sub,p.sub,r.cid+'::'+r.lid)&&r.method==p.method&&keyMatch(r.cid,p.cid)&&keyMatch(r.lid,p.lid)&&keyMatch2(r.obj,p.obj)"
    );
  });
```
with ini 
```ini
[multi6]
m = g(r.sub,p.sub,r.cid+'::'+r.lid) \
    &&r.method==p.method \
    &&keyMatch(r.cid,p.cid) \
    &&keyMatch(r.lid,p.lid) \
    &&keyMatch2(r.obj,p.obj)
```
and seems it works fine.
Could you please help to reproduce this?

**Comment by hariprasadiit** [comment]
Please try this https://repl.it/@hariprasadiit/casbin-multiline
