### ISSUE TITLE
Fix the depend alerts

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#243]
![image](https://user-images.githubusercontent.com/3787410/110966079-e1fdca00-838f-11eb-86eb-90d01ea617d5.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@hsluoyz plz use dependent bot to create a PR. I'll later review it.

**Comment by hsluoyz** [comment]
@Zxilly it can't be auto-done. We need to manually update some packages. You can view: https://github.com/casbin/node-casbin/security/dependabot
