### ISSUE TITLE
Use require syntax for docs as an example instead of import

### ISSUE THREAD

**Issue by sourabhmandal** [casbin/node-casbin#245]
I would like to point out that while following the examples I faced following error : -
In server.js
`import { newEnforcer } from 'casbin';`
`const enforcer = await newEnforcer('basic_model.conf', 'basic_policy.csv');`

![image](https://user-images.githubusercontent.com/39632788/111057899-c9390580-84b0-11eb-82c8-4cd3dfff08c4.png)
This is because nodejs natively supports `require syntax` and the index file of the librar is not in form of a module.

Adding  `"type": "module"` in package.json (which parses every js file as a module) solves the issue but then messes with other packages like express.js

Additionally on declaring following
`const enforcer = await newEnforcer('basic_model.conf', 'basic_policy.csv')`
I got this error ;
![image](https://user-images.githubusercontent.com/39632788/111058129-5761bb80-84b2-11eb-9c72-bf2f3fa09577.png)

Since this is casbin implementation for nodejs I would recommend to make example specific to node developers.

**Comment by sourabhmandal** [comment]
This syntax works in nodeJS

![image](https://user-images.githubusercontent.com/39632788/111058183-b293ae00-84b2-11eb-8af3-71b974856dcf.png)

Do I make changes to Readme.md and make PR for same...

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
Maybe `require` should be added as an additional option.

**Comment by hsluoyz** [comment]
@sourabhmandal we can just remove async:

```node.js
const enforcer = newEnforcer('basic_model.conf', 'basic_policy.csv')
```

**Comment by hsluoyz** [comment]
@Zxilly what is `import { newEnforcer } from 'casbin';` for? Browser? We should also provide the code for Node.js definitely.

**Comment by Zxilly** [comment]
@hsluoyz In fact, I believe it should work as expected. I'm resolving problem.

**Comment by sourabhmandal** [comment]
`import { newEnforcer } from 'casbin';` works for browser like in reactJs and other front end libraries. NodeJS has also adding support for `import` syntax. for that we need to wrap newEnforcer into a module or we can just use require syntax for Nodejs example.

**Comment by sourabhmandal** [comment]
@Zxilly I would suggest we stick to **require syntax only** since it would be less confusing for beginners. (People can just copy the code). And It makes sense since this DOC this specifically for NodeJS.

**Comment by Zxilly** [comment]
@sourabhmandal In my opinion, this example is just a short snippet. They are designed as reference, but not production code.

**Comment by sourabhmandal** [comment]
@Zxilly Agreed. But the purpose of doc should be to provide good code snippet that people can follow easily.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/node-casbin/commit/fe3f10f58ce60eb30d2952a0d9d32ebee377dcb6
