### ISSUE TITLE
getFilteredPolicy returns different results after savePolicy

### ISSUE THREAD

**Issue by EladProject** [casbin/node-casbin#252]
Hi,

I'm using with Sequelize adapter and Postgres.
My code adds/removes policies and then does the following:

```node
p1 = await enforcer.getFilteredPolicy(0, role, tenant, product, 'op')
await enforcer.savePolicy();
p2 = await enforcer.getFilteredPolicy(0, role, tenant, product, 'op')
```

I get different values for p1 and p2.
I thought savePolicy only writes back to the DB.
What am I missing?

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
got it, working on this tomorroe

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/113739982-e325db00-9732-11eb-953d-4af0efdb4b9c.png)
@EladProject I failed to reproduce your problem with default FileAdapter.
Inside the enforcer, `savePolicy()` just call the function provided by adapter.
https://github.com/casbin/node-casbin/blob/b8d9c978e19300c2982a4fdcc313abbcf7aa891e/src/coreEnforcer.ts#L227-L239
So, plz produce more infomation about your adapter.

**Comment by EladProject** [comment]
@Zxilly 
1) I'm using Postgres DB with "casbin-sequelize-adapter": "^2.1.0",
2) This test doesn't reflect the issue because there are no policy additions involved (without save).

    The scenario in which I encounter the issue is:
    a) Delete some policies
    b) savePolicy (not sure why this is needed, but without it the behavior is even stranger)
    c) Add some policies
    d) p1 = await enforcer.getFilteredPolicy(0, role, tenant, product, 'op')
    e) await enforcer.savePolicy();
    f) p2 = await enforcer.getFilteredPolicy(0, role, tenant, product, 'op')

p1 is missing some of the policies that were added before
p2 is as expected

**Comment by hsluoyz** [comment]
@EladProject plz provide a minimized fully-reproducible example, better a github repo.

**Comment by EladProject** [comment]
Doesn't reproduce for me on a scaled-down version. Possibly a sync issue in my code. Closing for now.

**Comment by EladProject** [comment]
Doesn't reproduce for me on a scaled-down version.
Possibly a sync issue in my code.
Closing for now
