### ISSUE TITLE
casbinJsGetPermissionForUser is not returning user permission

### ISSUE THREAD

**Issue by Anthony-Michel** [casbin/node-casbin#254]
Hi, I'm using casbin 5.6.1 and wanted to use the function `casbinJsGetPermissionForUser` to retrieve the list of permissions associated to a user on request, but it returns only a string representation of the model.

The code doesn't seem to use the user passed in argument.

I also tried to use `await enforcer.getImplicitPermissionsForUser(user);` but it returns empty

this is my model

```ini
[request_definition]
r = user, domain, path, method

[policy_definition]
p = role, domain, path, method

[role_definition]
# map user, role and domain
g = _, _, _
# mapping id to global resource
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# map user request to correct role, and validte path and method requested are allowed
m = g(r.user, p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)
```

and the policy

```csv
# only correct role can do correct call to these
p, role:owner, workflow_api, /workflow/:id, (get)|(put)
p, role:admin, workflow_api, /workflow/:id, get

# gloabl role hierarchy
g, role:super_admin, role:owner, *

# map user roles to WF ids
g, User1, role:owner, wf1
g, User2, role:admin, wf1
g, User3, role:owner, wf2

# reference the new id to be a valid workflow
g2, wf1, workflow_api
g2, wf2, workflow_api
```
Enforcer itself works fine. 

How can i get the implicit list of roles of my users ?

**Comment by Anthony-Michel** [comment]
Ok actually scratch the above, i do get the policies in the response, issue is that it doesn't take into account the domain and role of the user.

Here is the response for `User2`

```{"m":"[request_definition]\nr = user, domain, path, method\n[policy_definition]\np = role, domain, path,
method\n[role_definition]\ng = _, _, _\n[policy_effect]\ne = some(where (p.eft == allow))\n[matchers]\nm = g(r.user,
p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method) || r.user ==
\"tony\"","p":[["p","role:owner","workflow_api","/workflow/:id","(get)|(put)"],["p","role:admin","workflow_api","/workflow/:id","get"]]}```

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Anthony-Michel** [comment]
Ok so for 
`How can i get the implicit list of roles of my users ?` this is actually working now that i saw i can pass the domain too `enforcer.getImplicitRolesForUser(user, domain);`
but if i'm not mistaking `getImplicitPermissionsForUser` does not have a second parameter for domain on nodejs implementation

**Comment by Zxilly** [comment]
Hello, I'm maintainer of casbin.js.
For now,casbin.js did exactly same thing with node-casbin. You can use node-casbin.

**Comment by Anthony-Michel** [comment]
hi @Zxilly thanks for you answer.
My issue is actually that `casbinJsGetPermissionForUser` cannot take my `domain` to filter the permissions returned.
So it is going to mostly returns all permissions all the time.
I would need it to either take a domain in parameter and filter the result based on this domain, or to add a domain dimension n the result so that i could filter it myself after.

Using node-casbin function `getImplicitPermissionsForUser` the issue i have is that it doesn't work because of my resources grouping g2 it seems. Where enforcing the rules works fine.

Here is a simpler example:

config
```
[request_definition]
r = user, domain, path, method

[policy_definition]
p = role, domain, path, method

[role_definition]
# map user, role and domain
g = _, _, _
# mapping id to global resource
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# map user request to correct role, and validte path and method requested are allowed
m = g(r.user, p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)
```

policies, with an alternate version commented that do work
```
p, role:owner, resource_group, /myapi/:id, put
p, role:admin, resource_group, /myapi/:id, get
# alternative policies not using g2 rules
# p, role:owner, resource1, /myapi/:id, put
# p, role:admin, resource1, /myapi/:id, get

# map user roles to resource group
g, user1, role:owner, resource1
g, user2, role:admin, resource2

# map resource to resource group
g2, resource1, resource_group
g2, resource2, resource_group
```

code for enforcing the rule
```    const enforcer = await getDefaultEnforcer();

    const authorized = await enforcer.enforce(
      userId,
      domain,
      accessedRoute,
      method
    );```
    
    called with this 
    ```{
    "accessedRoute": "/myapi/abc",
    "method": "put",
    "userId": "user1",
    "domain": "resource1"
}```

returns true, for both set policies using my g2 grouping or not

code for testing getImplicitPermissionsForUser and casbinJsGetPermissionForUser
```
const getUserpermissions = async (req, res) => {
  const { user, domain } = req.params;
  try {
    log.info(`Computing user permissions ${user} - ${domain}`);
    const enforcer = await getDefaultEnforcer();

    let permissions = { implicit: {}, casbinJS: {} };
    permissions.implicit = await enforcer.getImplicitPermissionsForUser(
      user,
      domain
    );
    permissions.casbinJS = await casbinJsGetPermissionForUser(enforcer, user);
    res.send(permissions);
  } catch (error) {
    log.error(`Error retrieveing permissions for ${user} - ${domain}`, error);
    res.status(error.httpStatusCode || 400).send(error);
  }
};
```

calling this permission endpoint with `user1` `resource1` using the policies
```p, role:owner, resource_group, /myapi/:id, put
p, role:admin, resource_group, /myapi/:id, get```

returns
```
{
    "implicit": [],
    "casbinJS": "{\"m\":\"[request_definition]\\nr = user, domain, path, method\\n[policy_definition]\\np = role, domain, path, method\\n[role_definition]\\ng = _, _, _\\n[policy_effect]\\ne = some(where (p.eft == allow))\\n[matchers]\\nm = g(r.user, p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)\",\"p\":[[\"p\",\"role:owner\",\"resource_group\",\"/myapi/:id\",\"put\"],[\"p\",\"role:admin\",\"resource_group\",\"/myapi/:id\",\"get\"]]}"
}```

So here you see the implicit result is empty, and the casbinJs actually returns all the policies. Calling with `user2` would also have casbinJS returning all policies

calling this permission endpoint with `user1` `resource1` using the alternate policies
```p, role:owner, resource1, /myapi/:id, put
p, role:admin, resource1, /myapi/:id, get```

returns
```{
    "implicit": [
        [
            "role:owner",
            "resource1",
            "/myapi/:id",
            "put"
        ]
    ],
    "casbinJS": "{\"m\":\"[request_definition]\\nr = user, domain, path, method\\n[policy_definition]\\np = role, domain, path, method\\n[role_definition]\\ng = _, _, _\\n[policy_effect]\\ne = some(where (p.eft == allow))\\n[matchers]\\nm = g(r.user, p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)\",\"p\":[[\"p\",\"role:owner\",\"resource1\",\"/myapi/:id\",\"put\"],[\"p\",\"role:admin\",\"resource1\",\"/myapi/:id\",\"get\"]]}"
}```

so now the implicit result is as expected, but casbinJs one still not, as it returns both policies where `user1` should get only first one

I would really like to avoid having to not use my g2 rules to make that work, as it will mean duplicating my set of policies for each resources that are going to be added, which is going to grow exponentially by the day.

If i misunderstood some concept there please let me know

**Comment by Zxilly** [comment]
Well, this is a historical legacy problem.
As for now, `casbinJsGetPermissionForUser` just sent the whole model and all policies to frontend without any preprocess.
Its name was from the original design of casbin.js. However, the author of that design failed to implement ABAC. So this draft is abandoned and the name of this function is actually wrong.
A refactoring of casbin.js is already being planned. As for now, you can just use node-casbin in the frontend.

**Comment by Anthony-Michel** [comment]
@Zxilly good to know thanks, the name is indeed very confusing. 
Any resource i can check on what is planned for the refactoring and what is the deadline for it ?

Moreover, i still have the issue that the actual `getImplicitPermissionsForUser` casbin function also doesn't work with my use case as it is not able to handle by `g2` group.
Anyone has any idea if that can be fixed or how i could adapt my settings to work, without having to create new policy for each resource i add ?

**Comment by Zxilly** [comment]
I will try to resolve problem about `getImplicitPermissionsForUser`.
Refactoring of casbin.js is a long-term task, it may complete before 2021 Sept. I'm not sure about that.

**Comment by hsluoyz** [comment]
@Anthony-Michel can you retrieve the complete model and all policy rules from backend to frontend, then use Node-Casbin at frontend JS to call all Casbin functions?

**Comment by Anthony-Michel** [comment]
@hsluoyz i technically probably can, but the way it's going to be used is that each domain represent a specific object created by 1 of my users on which he grant permissions to his colleagues.
the number of policies is going to grow exponentially and are highly dynamic, so it doesn't seem great to have to send on every requests to Front End the entire list of policies.
Plus there is some privacy and segregation concerns doing so.

**Comment by Anthony-Michel** [comment]
Any feedback on that @Zxilly ?
Meanwhile if you have any other proposition to work around it, i can have a look at it

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Anthony-Michel** [comment]
Ok so as we validated current way casbinJS for Front end won't match our use case, we wanted to implement our own flow using `getImplicitPermissionsForUser` and i had to re-implement the function to match our use case.
Seems to work fine for what we are doing, but honestly would rather use Casbin directly, so please do advice if I misunderstood some concepts on how the library is used or if some fix are being made to Casbin directly.

For reference here is our current flow: 

Model:
```
[request_definition]
r = user, domain, path, method

[policy_definition]
p = role, domain, path, method

[role_definition]
# map user, role and domain
g = _, _, _
# mapping id to global resource
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# map user request to correct role, and validate path and method requested are allowed
m = g(r.user, p.role, r.domain) && g2(r.domain, p.domain) && keyMatch2(r.path, p.path) && regexMatch(r.method, p.method)
```

Policy example (just a very small test sample)
```
# only correct role can do correct call to these
p, role::owner, group::workflow_api, /workflow/:id, (get)|(put)
p, role::admin, group::workflow_api, /workflow/:id, get

# rules for FE
p, role::owner, group::workflow_ui, reminder, read|write
p, role::owner, group::workflow_ui, deleteMember, read|write
p, role::admin, group::workflow_ui, reminder, read
p, role::admin, group::workflow_ui, deleteMember, read

# exception for user1 that got a specific permission assigned to him
p, user::user1, group::workflow_ui, deleteAll, read|write

# this rule should not be retrieved on permissions for workflow users
p, role::owner, group::not_workflow, shouldNotGetThis, read|write

# map user roles to WF ids
g, user::user1, role::owner, domain::wf123
g, user::user2, role::admin, domain::wf123
g, user::user3, role::owner, domain::wf234

# general inheritance
g2, group::workflow, group::workflow_ui
g2, group::workflow, group::workflow_api

# reference the new id to be a valid workflow
g2, domain::wf123, group::workflow
g2, domain::wf234, group::workflow
```

custum function to get permissions:
```
/**
 * Compute the list of permissions of a user on specific domain and group,
 * using roles and groups inheritence to compute available permissions
 * @param {string} user the user id to recover permissions from
 * @param {string} groupName a specific group name to filter permissions on, like `workflow_api`
 * @param  {string} domain the domain to take into consideration
 * @returns an array of Permissions object
 */
const getImplicitPermissionsForUser = async (
  user,
  groupName, //todo use that as extra filter
  domain
) => {
  const formattedUser = formatUser(user);
  const formattedDomain = formatDomain(domain);
  const enforcer = await getDefaultEnforcer();

  const roles = await enforcer.getImplicitRolesForUser(
    formattedUser,
    formattedDomain
  );
  //adding user in roles list to retrive both policies added to role or directly to user
  roles.unshift(formattedUser);
  log.info(`roles found ${roles}`);

  const inheritsGroups = enforcer.model
    .getValuesForFieldInPolicyAllTypes("g", 1)
    //filter to get only groups, and if specified only the group we are interestedIn
    .filter(v => v.startsWith(`group::${groupName || ""}`));

  log.info(`inherits found for group::${groupName} : ${inheritsGroups}`);

  const rm = enforcer.getRoleManager();
  const res = [];
  for (const group of inheritsGroups) {
    const hasLink = await rm.hasLink(formattedDomain, group);
    log.info(`checking domain ${domain} is linked to ${group} : ${hasLink}`);

    if (hasLink) {
      //domain is link to current group, adding permissions associated to this group and user role
      for (const n of roles) {
        const p = await enforcer.getFilteredPolicy(0, n, group);
        log.info(`Policy found with group ${group} for role ${n}: ${p}`);
        res.push(...p);
      }
    }
  }

  log.debug(`List of permissions found for user ${user} - ${domain}`, res);

  return formatPermissions(res);
};
```

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@Anthony-Michel I read your code. Yes, `use Casbin directly` is a good idea for now.
We are working on a big reafactor of node-casbin to make it a platform-unrelated project. Plz ref to discussion at https://github.com/casbin/node-casbin/issues/270. 
After that, we will remake casbin-browser (aka `casbin.js`).

For your needs, could it dynamic generate policies, and use node-casbin directly in the frontend to judge?

**Comment by Anthony-Michel** [comment]
I would love to use casbin directly, but i can't, as said initially, with my model and policies as shown above, function `getImplicitPermissionsForUser ` does not return anything. 
So i can enforce rules fine, but i cannot send the computed permissions lists to my Backend and front end services.

`For your needs, could it dynamic generate policies, and use node-casbin directly in the frontend to judge?`
so 1. Same issue as said above, node-casbin `getImplicitPermissionsForUser ` does not work with my model. 
2. I cannot send over the network all the policies and model to the front-end, it's too big and would generate privacy concerns

**Comment by Zxilly** [comment]
Thanks for your feedback. I will resolve the problem of `getImplicitPermissionsForUser`

**Comment by Zxilly** [comment]
@Anthony-Michel I have submited a patch at https://github.com/casbin/node-casbin/pull/272, plz confirm whether this fix your problem.
