### ISSUE TITLE
Add EnforceEx() API to Node-Casbin

### ISSUE THREAD

**Issue by Pyav123** [casbin/node-casbin#256]
For ABAC mode suppose If I have multiple policy rules, how can I check which condition failed and returned false

e.g consider my policy contain below rules

```csv
p,(r.requestingUserIdAge > 18 && r.requestingUserIdAge < 60),abc,dataset1,create
p,(r.requestingUserIdAge > 18 && r.requestingUserIdAge < 60),xyz,dataset1,update
p,(r.requestingUserIdAge > 18 && r.requestingUserIdAge < 60),pqr,messages,create
```

My model configuration is

```ini
[request_definition]
r = requestingUserId,loggedInUserId,resourceName,action,requestingUserIdAge

[policy_definition]
p = rquestingUserId_rule1,requestingUserId,resourceName,action

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.rquestingUserId_rule1) && (r.requestingUserId == r.loggedInUserId) &&(r.action == p.action) && (r.requestingUserId == p.requestingUserId)
```

Below are my request parameters

```
abc,abc,messages,delete,34
```

so this returns me as false , so for this given scenario I want to show reason as because of which policy rule my request is denied, is there any API for nodejs to achieve this?

**Comment by hsluoyz** [comment]
@Pyav123 see: https://casbin.org/docs/en/management-api#enforceex

**Comment by Pyav123** [comment]
@hsluoyz This is API is not available in nodejs, syntax is only available for go,php and python

**Comment by Pyav123** [comment]
@hsluoyz Is there any other way to achieve this?

**Comment by hsluoyz** [comment]
@Zxilly plz add this API to Node-Casbin

**Comment by Zxilly** [comment]
working on this

**Comment by Pyav123** [comment]
Hello @Zxilly thank you for adding the API , simultaneously I also tried to implement that looking at go code  and it involves below logic  in casbin/lib/cjs/coreEnforcer.js **single file** inside  *privateEnforce

1) Defined one variable to store index e.g.pIndex
2) once I get result as true, assign that current index to pIndex 
3) now print the policy which is as pIndex

snippet looks like this , I am just sharing the main logic part rest code is also there

for(var i=; i< policyLen; i++){
if(policyLen && policyLen !== 0)
{
   var pIndex = -1;
    var successReason;
   const [res,done] = effectStream.pushEffect(eftRes);

   if(done)
    {
        pIndex = i;
        successReason = p['policy'][pIndex];
         break;
     }
 }
}

and this way I could see the success policy which I was expecting from enforceEx(returning same result)

But when I saw  your commit , **it involves changes in multiple files** ,so what I have done is the right way ? can you guide me why do we need to change other files too?  when changing just coreEnforcer giving me same result ? as for the first time I am changing something to existing published  node module.

**Comment by Zxilly** [comment]
@Pyav123 My implement was inspired by pycasbin. While working on that, I noticed that the performance of the current implementation in golang-casbin can be improved. So I'm working on that.
I will return to finish this task after the optimization is complete.

**Comment by Pyav123** [comment]
Hey @Zxilly no worries, my just concern is, if I can achieve the same result by changing code inside  coreEnforcer just single file , then am I missing anything which isn't affecting my end result but might  impact on other parts ? If yes then what are they  and how can I find out that whatever I have done is right or not ? As for first time I am adding some feature to already published node module

**Comment by Zxilly** [comment]
@Pyav123 It's ok. If you just want to implement enforceEx(), there's no need to modify effector.

**Comment by Zxilly** [comment]
@Pyav123 Could you please make a PR to submit your patch?

**Comment by Pyav123** [comment]
sure
