### ISSUE TITLE
Support for loadIncrementalFilteredPolicy

### ISSUE THREAD

**Issue by murzatayev** [casbin/node-casbin#278]
Hey guys,
are there any plans of introducing `loadIncrementalFilteredPolicy` for node-casbin?

Is the difference with `loadFilteredPolicy` in just clearing existing policies before adding?

**Comment by hsluoyz** [comment]
> Is the difference with loadFilteredPolicy in just clearing existing policies before adding?

Yes, see: https://casbin.org/docs/en/policy-subset-loading

@Zxilly plz support it
