### ISSUE TITLE
Watcher does not wait for updating the policy

### ISSUE THREAD

**Issue by ghaiklor** [casbin/node-casbin#28]
When I'm providing the enforcer with watcher to reload policy on changes, it actually does not wait for it. It leads to the problem, when policy is inconsistent for a some time.

Here is how I am injecting the watcher:

```javascript
const adapter = await Adapter.newAdapter(uri);
const watcher = new Watcher();
const enforcer = await Enforcer.newEnforcer(model, adapter, false);
enforcer.setWatcher(watcher);
```

Surely, watcher has implemented required interface, but, when CoreEnforcer calls an update method in watcher, it actually does not wait for it. `update` method in watcher calls `loadPolicy`, which is async function.

Proposed fix - add `await` here - https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts#L216

**Comment by hsluoyz** [comment]
Hi, it seems to be a bug. Can you make a PR for it?

**Comment by ghaiklor** [comment]
@hsluoyz https://github.com/casbin/node-casbin/pull/29

**Comment by hsluoyz** [comment]
Thanks for the PR! Merged.
