### ISSUE TITLE
[Question] Enforce() returns false but expected true for ABAC & in operator

### ISSUE THREAD

**Issue by Tapas059** [casbin/node-casbin#281]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

------

**What's your scenario? What do you want to achieve?**
 I am trying to check below policy on editor , But in both cases i am getting false. 

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub.Owner == r.obj.Owner && r.sub.Doc in(r.obj.Docs)
```

**Your policy:**

```json
{Owner: 'alice', Doc: 1}, { Owner: 'alice', Docs: [1,2] }
{Owner: 'alice', Doc: 1}, { Owner: 'alice', Docs: [3,4]}
```

**Your request(s):**

```
{Owner: 'alice', Doc: 1}, { Owner: 'alice', Docs: [1,2] } ---> false (expected: true)
```

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Tapas059** [comment]
Hi @Zxilly , Any update on above ? I am trying to find alternate solution as well .

**Comment by MRGUOKING** [comment]
I have saw the saw the source code and ask the person who charge the Node-Casbin. So for ,the node-casbin doesn't support to use "in" in the matchers. but you can write like below to solve this problem.
```
function includes(value: number,vlues: Array<number>) : boolean{
       for(let i = 0;i<values.length;i++){
             if(values[i] === value){
                    return true;
             }
       }
       return false;
}
```

**Comment by Tapas059** [comment]
Ohh Fine @MRGUOKING and @hsluoyz Thank you .

**Comment by hsluoyz** [comment]
Raised an issue here: https://github.com/donmccurdy/expression-eval/issues/58

**Comment by hsluoyz** [comment]
The expression-eval author has replied: https://github.com/donmccurdy/expression-eval/issues/58#issuecomment-860104182

We can add built-in support for "in". Can anyone do this?

**Comment by Zxilly** [comment]
working On this
