### ISSUE TITLE
bug: semantic-released failed

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#286]
See: https://github.com/casbin/node-casbin/runs/2822041154?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/121930569-1ad58280-cd75-11eb-8070-4365d9f4d398.png)

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by hsluoyz** [comment]
@Zxilly don't use your own account to release:

![image](https://user-images.githubusercontent.com/3787410/122050624-38a6f400-ce16-11eb-829a-e8a9788be5e3.png)

**Comment by Zxilly** [comment]
@hsluoyz semantic-release create the tag on the master branch and failed to make a new release. So this commit won't trigger a release process again. I have to manually release it.

**Comment by Zxilly** [comment]
@hsluoyz semantic-release create the tag on the master branch and failed to make a new release. So this commit won't trigger a release process again. I have to manually release it.

**Comment by hsluoyz** [comment]
OK.
