### ISSUE TITLE
enforceSync ignores subject, always returns true if policy exists for object and method.

### ISSUE THREAD

**Issue by FabianSellmann** [casbin/node-casbin#292]
See codesandbox for a simple reproduction:
https://codesandbox.io/s/xenodochial-kapitsa-xhszj

Basically `enforcer.enforceSync` seems to return always true in the example above, no matter what the subject is.

**Comment by nodece** [comment]
@FabianSellmann thanks for your report! `Sync` means that there is no asynchronous function in the matcher, your model includes the asynchronous function - `g()`, so `enforceSync` cannot  be used in this model.

`enforceSync` comment: https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts#L531

**Comment by hsluoyz** [comment]
@nodece is it possible to support a sync version of `g()`?

Also add @Zxilly @Gabriel-403

**Comment by Zxilly** [comment]
@hsluoyz g function relies on `hasLink` of RoleManager, which is an async function.
To implement this, we must create a synced version role manager.

**Comment by nodece** [comment]
> @FabianSellmann thanks for your report! `Sync` means that there is no asynchronous function in the matcher, your model includes the asynchronous function - `g()`, so `enforceSync` cannot be used in this model.
> 
> `enforceSync` comment: https://github.com/casbin/node-casbin/blob/master/src/coreEnforcer.ts#L531

@FabianSellmann Sorry, it's my fault. Casbin doesn't  support the sync API,  but it added to our plan. I think that `enforcer.enforce` should be able to meet your requirements.

**Comment by Shivansh-yadav13** [comment]
do we still plan to support sync API in node-casbin? asking bcoz the above prs were closed.

**Comment by Shivansh-yadav13** [comment]
ok

**Comment by Sefriol** [comment]
@Zxilly `SyncedEnforcer` with `g`-support should still be possible right? I didn't really understand what was the particular problem with https://github.com/casbin/node-casbin/pull/303 implementation.

**Comment by Zxilly** [comment]
@Sefriol It's possible. #303 was gave up because we decided to make a better implementation in the `casbin.js` at that time.
It still works as a trick.

**Comment by Sefriol** [comment]
For me it seems that this would be an efficient improvement for short term. Maybe open the pull request again?

Some more drastic improvements could be done to `casbin-core`?

**Comment by Zxilly** [comment]
@Sefriol  I didn't find it. In the `casbin core` there only async g function available now.

**Comment by Sefriol** [comment]
I meant that more drastic changes can be done to `casbin core` in the future.

**Comment by Sefriol** [comment]
This should be now fixed with release [v5.16.0](https://github.com/casbin/node-casbin/releases/tag/v5.16.0):
https://codesandbox.io/s/serene-solomon-g18wnw
