### ISSUE TITLE
readFileSync import in config.ts

### ISSUE THREAD

**Issue by elvuel** [casbin/node-casbin#295]
Trying casbin.js with svelte(rollup), got `Error: 'readFileSync' is not exported ...`
`fs` import should be the same way as utils/utils.ts(`import * as fs from 'fs';`)

**Comment by nodece** [comment]
@elvuel could you provide a demo for this issue?

**Comment by elvuel** [comment]
@nodece put initial recap to `https://github.com/elvuel/sevlte-casbin-spike`.

![image](https://user-images.githubusercontent.com/161844/124878814-19f3e180-dfff-11eb-9d82-fb40877f16b3.png)

took some partial refs like from [rollup#897](https://github.com/rollup/rollup/issues/897) [rollup#3230](https://github.com/rollup/rollup/issues/3230) etc,with no luck.(could be my bad, not familiar with node/js such rel staffs)

after made the changes to `config.ts` it works, and on the other hand it should be the same style to utils/utils.ts within the repo.

**Comment by hsluoyz** [comment]
@Gabriel-403 @Zxilly

**Comment by Gabriel-403** [comment]
I'll fix it as soon as possible, please give me some time

**Comment by Zxilly** [comment]
@Gabriel-403 I already created a correspond PR at https://github.com/casbin/node-casbin/pull/296, we just need more discussion.

**Comment by nodece** [comment]
Hello @elvuel, I tried to create a sevlte project with codesandbox: https://codesandbox.io/s/sweet-worker-jbu71?file=/Button.svelte

I think it's a rollup problem, so I close this issue, I'm sure webpack is working. If you are interested, you can try it.
