### ISSUE TITLE
matchingForGFunction in nodejs

### ISSUE THREAD

**Issue by fahussain** [casbin/node-casbin#298]
First of all it's a wonderful library and thank you so much for sharing it with us. 

I am trying to implement RBAC with domains and 'all' patterns matching using nodejs but I have not been able to figure out how to tell casbin to use which function for g matching. In the online editor I see that I need to specify:

```
 matchingForGFunction: 'keyMatch2',
 matchingDomainForGFunction: 'keyMatch2'
```
but I don't know how and where I need to pass this config. Any help would be greatly appreciated.

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403 plz add the Node.js code example to: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by Shivansh-yadav13** [comment]
is this issue still up?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 yeah, plz add to docs.
