### ISSUE TITLE
How to implement multi thread.

### ISSUE THREAD

**Issue by tronghm88** [casbin/node-casbin#300]
Hi there.
I'm new with Casbin.
I'm have a Nest.js project and applying Casbin RBAC for my permission management system.
But I am researching for implement multi thread of Casbin.
But I don't understand how i can do it? How my nestjs will connect casbin when it has multi thread.
As document, I only know install casbin nodejs package and use single casbin instance inside my code.

Do you have any samples for this? Thank you so much.
P/s: I'm sorry for my English, It's not good enough.

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by nodece** [comment]
Use a single casbin instance is enough, so like:

```js
// enforcer.js
import { newEnforcer } from 'casbin';

export const e = await newEnforcer('model.conf', 'policy.csv');
```

```js
// test.js
import { e } from './enforcer';

const ok = e.enforce('alice', 'data1', read');
```

**Comment by Gabriel-403** [comment]
You can use singleton mode to solve this problem. Of course, if you have to use multithreading, you can use Web woker.

**Comment by hsluoyz** [comment]
Closed as resolved.
