### ISSUE TITLE
TypeError: b.includes is not a function

### ISSUE THREAD

**Issue by lantu-group** [casbin/node-casbin#309]
At same env, use `m = r.act == 'In' && r.sub in "('root', 'guest')"` matchers is ok, but is i adjust conditions location: `r.sub in "('root', 'guest')"` as first location, eg: `m =  r.sub in "('root', 'guest')" && r.act == 'In'`, and then got error: `TypeError: b.includes is not a function`

The below is my test codes

```js
const fs = require('fs')
const path = require('path')
const Casbin = require('casbin')

const model1Text = `[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.act == 'In' && r.sub in "('root', 'guest')"`


const model2Text = `[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub in "('root', 'guest')" && r.act == 'In'`

;
(async () => {
  // initial models
  const path1 = path.resolve(__dirname, './model1.conf')
  const path2 = path.resolve(__dirname, './model2.conf')
  fs.writeFileSync(path1, model1Text)
  fs.writeFileSync(path2, model2Text)

  // loading enforcer
  const enforcer1 = await Casbin.newEnforcer(path1)
  const enforcer2 = await Casbin.newEnforcer(path2)

  // test
  const result1 = await enforcer1.enforce('root', {}, 'In')
  const result2 = await enforcer2.enforce('root', {}, 'In')
  console.log('result1 : ', result1) // true
  console.log('result2 : ', result2) // throw new error
})();
```

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by Gabriel-403** [comment]
> @Zxilly @Gabriel-403

Looking for problems

**Comment by Zxilly** [comment]
@Gabriel-403 () in js didn't create an array. And includes function didn't exist. That's the problem.

**Comment by lantu-group** [comment]
So ~ Are you ready this project for production ?

**Comment by Zxilly** [comment]
@lantu-group This library is production-ready. But there are some missing documents.
In this issue, you should use in on a js array. like `['root', 'guest']`

**Comment by Gabriel-403** [comment]
@lantu-group We will try our best to solve this problem, but it will take some time

**Comment by lantu-group** [comment]
> @lantu-group We will try our best to solve this problem, but it will take some time

OK~ Just do it.
