### ISSUE TITLE
[Bug] A matcher with multiple eval() doesn't work

### ISSUE THREAD

**Issue by JoshuaCWebDeveloper** [casbin/node-casbin#315]
A matcher with multiple eval() statements only calls the first eval(), caching the results.

This is likely the same issue as https://github.com/casbin/casbin/issues/619, which was fixed in that repo, but apparently not in this one. There are also several people experiencing this issue here: http://disq.us/p/2g9ubnp (although they didn't say which language).

I'm experiencing this issue in node-casbin; however, I can also reproduce it in the online editor: https://casbin.org/casbin-editor/#6FGL6FCSV (not sure which language it uses). In this example, I would expect the result to be false:
 - The array is evaluated, and the first element picked is > 10
 - However, the second call to `eval()` should evaluate `10 > 18`, however, it instead evaluates the first result again (the array) which is truthy.

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by Zxilly** [comment]
working on this
