### ISSUE TITLE
BatchEnforce

### ISSUE THREAD

**Issue by fahussain** [casbin/node-casbin#321]
I don't see the BatchEnforce API(https://casbin.org/docs/ja/data-permissions) for the coreEnforcer. Is it not available yet?

**Comment by Zxilly** [comment]
This will be implement in casbin.js

**Comment by Shivansh-yadav13** [comment]
> This will be implement in next-version casbin.js: https://github.com/casbin/casbin.js/tree/v1

So, all the functions which are not in this are present on casbin.js?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 can you make a PR?

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 can you make a PR?

@hsluoyz  for ?

**Comment by Zxilly** [comment]
@Shivansh-yadav13 We have a WIP PR,currently not merged

**Comment by Shivansh-yadav13** [comment]
I would love to contribute but @Zxilly sorry, not able to understand what you mean 😅 but for what purpose @hsluoyz is asking me to make a pr.

**Comment by Shivansh-yadav13** [comment]
> > This will be implement in next-version casbin.js: https://github.com/casbin/casbin.js/tree/v1
> 
> So, all the functions which are not in this are present on casbin.js?

I wanted to ask that do we have batchEnforce on casbin.js

**Comment by Zxilly** [comment]
> > > This will be implement in next-version casbin.js: https://github.com/casbin/casbin.js/tree/v1
> > 
> > So, all the functions which are not in this are present on casbin.js?
> 
> I wanted to ask that do we have batchEnforce on casbin.js

As for now, no

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 can you make a PR?

were you asking me to make a pr for BatchEnforce?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 yes, if `BatchEnforce()` is not available for Node.js, add it by making a PR.

**Comment by Shivansh-yadav13** [comment]
I wanted to confirm that `batchEnforce` has to be in `coreEnforcer.ts` and its test in `enforcer.test.ts`, right?

@hsluoyz @Zxilly

**Comment by Alec-Bailey** [comment]
@Shivansh-yadav13 I would be interested in this functionality, if you are going to be adding it I will not do it myself.

@Zxilly No pressure, simply trying to weight my options - but is there an ETA this WIP pr?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 similar to Go

**Comment by hsluoyz** [comment]
@Alec-Bailey there's no PR yet. You can also make a PR. We will merge a suitable PR to add this feature.
