### ISSUE TITLE
Synchronizing issues when several instances

### ISSUE THREAD

**Issue by ghaiklor** [casbin/node-casbin#33]
Does casbin support working in several application instances or does it provide an interface to implement such?

### Problem

Let us say we have 2 instances of API: `API 1` and `API 2`.
Each of these instances have casbin enforcer inside the application.
So, we have `casbin 1` in `API 1` and `casbin 2` in `API 2`.

Each of them are looking in the same collection in database.
But, considering the implementation of casbin, it stores permissions/roles in memory.

It leads to the problem that can be reproduced by the following scenario:

- Developer grants a role to a user via API call to `API 1`.
- `API 1` does make changes in `casbin 1` instance and adapter stores the changes in database
- Though, `API 2` and `casbin 2` know nothing about recent change and use an out-of-date information from `casbin 2` memory.

Any assumptions how it can be resolved?

**Comment by hsluoyz** [comment]
You need to use the "Watcher" mechanism to keep policy consistence among multiple Casbin enforcer instances. See: https://github.com/casbin/casbin#policy-consistence-between-multiple-nodes. Like Adapter, a Watcher can be backended by KV stores like Redis, ZooKeeper, etc.

However, those watchers are written in Go and will be used by Golang's Casbin instead of Node-Casbin. So what backend do you want to use for the Node.js watcher?

**Comment by ghaiklor** [comment]
We are using MongoDB as a storage, unfortunately node-casbin does not have adapter for Mongoose at the moment, so we have implemented our own. It does work with single instance, but have issues with multiple.

As a watcher I thought about MongoDB collection stream - https://docs.mongodb.com/manual/changeStreams/#watch-collection-database-deployment. In case it will not be applicable, we can use RabbitMQ as another option to notify about changes.

**Comment by hsluoyz** [comment]
> We are using MongoDB as a storage, unfortunately node-casbin does not have adapter for Mongoose at the moment, so we have implemented our own. It does work with single instance, but have issues with multiple.

In fact, we have ``Waterline Adapter`` and ``TypeORM Adapter`` which both support MongoDB, if you do not insist in using Mongoose. And even for Mongoose, we are already working on the ``Mongoose Adapter``. See: https://github.com/casbin/node-casbin#policy-persistence.

And of course, we welcome third-party contribution on new adapters. So we could add your adapter to our list if it's open source :)

> As a watcher I thought about MongoDB collection stream - https://docs.mongodb.com/manual/changeStreams/#watch-collection-database-deployment. In case it will not be applicable, we can use RabbitMQ as another option to notify about changes.

I'm not a MongoDB expert. Would you like to implement the watcher? I think the etcd watcher is a great place to start: https://github.com/casbin/etcd-watcher

**Comment by ghaiklor** [comment]
BTW, are there any chances to tell casbin not to use in-memory ? So, when enforcer got `can()` call, it uses not the in-memory storage, but database. Somehow to force casbin to use database for policy decision.

**Comment by hsluoyz** [comment]
Even if Casbin doesn't use in-memory policy, the policy rules also have to be loaded into memory from DB first before policy enforcement. The possible issue here is how to load the policy from DB. In my view, there are three options:

1. Refresh all policy rules from DB before every decision. This will be no difference with manually calling ``LoadPolicy()`` then ``Enforce()`` in current implementation.
2. Only refresh the updated policy rules from DB. Synchronize with DB. Add missing rules, delete rules that are not in DB anymore. Update fields for modified rules. But this sync mechanism will be very complicated. And I don't know if it will be efficient. As the 1st solution (load all rules from beginning) can use batch operations, it will be actually very fast.
3. Only refresh a portion of policy rules from DB based on filters. For example, if you want to check the permission for ``alice``, then you only need to load the rules the subject of which is ``alice``. You can use ``loadFilteredPolicy()`` call to do this.

Simply modifying Casbin to not use memory doesn't avoid the above issue. You have to decide which way to go.

**Comment by ghaiklor** [comment]
Thanks for a great explanation. I came up with the similar approach you describe at point 3.

The main reason we can't use watcher for policy refreshing is - eventually consistent. Our business requirements does not allow to have "eventual consistency", so we'd like to go with `loadFilteredPolicy()`.

I already made a PR, making `loadFilteredPolicy()` an async function, so waiting for an update in npm.

P.S. I will talk with our CTO regard to open-source our mongoose filtered adapter, hope he give me a permission for that. I saw mongoose adapter from README and AFAIU it does nothing with mongoose and does not implement casbin interface.

**Comment by ghaiklor** [comment]
@hsluoyz I got a permission from our CTO to publish an adapter. The adapter I wrote fully tested and already being used in production. Though, we can do that somewhere in January, I need time for cleaning up the code, make required preparations for open-source it.

**Comment by hsluoyz** [comment]
That's good news! Thank you for your support on Casbin :)
