### ISSUE TITLE
Retrieve a list of objects based on roles and permisstions of a user

### ISSUE THREAD

**Issue by dipeshhkc** [casbin/node-casbin#334]
Hello developers. I am kind of using casbin in a project for the first time and got into a strange situation 😅. I appreciate the help from this community. Thanks :bow: 

Let us suppose we have this policy
```
p editor team1  profile1 write
p editor team1  profile2 read
p admin  team1  profile3 write
g user1  editor team1
g user1  admin  team2
```
**Problem:** _I want get the list of profiles(object) where user1 has (read/write) permission_

**I expect this result**
```
profile1
profile2
```
It would be a great help if someone can give me ideas regarding solving this problem. And also let me know if I need to change the design of the policy to achieve this or if this is not what casbin is used for :pray:

**Comment by hsluoyz** [comment]
@dipeshhkc see: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

And thanks for writing so many Casbin articles!

**Comment by dipeshhkc** [comment]
@hsluoyz Thank you for your quick reply. I had no idea about Implicit permission and it is actually a deal-breaker for my use case:exploding_head: 
One Query about its usage is 
```
await enforcer.getImplicitPermissionsForUser(
    "user1",
    "team1"
  );
```
Is there any way to denote **any team**  instead of mentioning a **single team** in the 2nd parameter so that I get all the permissions he has in any team?

Otherwise as a workaround, I need to do the following steps

1. **teams** = get all the teams he is part of
2. and loop following code for each team
```
for (let i = 0; i < teams.length; i++) {
   await enforcer.getImplicitPermissionsForUser(
      "user1",
      teams[i]
   );
}
```

**Comment by dipeshhkc** [comment]
Hello @hsluoyz , I just want to make sure I am doing things in a correct manner. Please have a look at the following code when you are available and please let me know if I am doing good or if there are better ways of achieving this.

**Thing I am trying to achieve**: I want to show the list of profiles the logged-in user has access to (his own created profiles or the profiles created by any team members he is part of) 

**Step1**. get all the permissions he has in a team
```
const results = await enforcer.getImplicitPermissionsForUser(
    "user1",
    "team1"
  );
```
_Output: results_
```
[
   [ 'editor', '28', 'profile/12', 'write' ],
   [ 'editor', '28', 'domain/12', 'write' ]
 ]
```
Here, we get two permissions. But I am currently interested only in the profile object. So I will filter results in step 2.
**Step2**
```
const filteredResult = results.filter((result) => {
    const obj = result[2];  // profile/12
    return obj.indexOf("profile") != -1; 
  });

```
_Output: filteredResult_

`[ [ 'editor', '28', 'profile/12', 'write' ] ]`

**Step3**: I now query **profiles** table to get full records of that profile along with the **permission** I got from **casbin** table.
  ```
const response = [];
  for (let i = 0; i < filteredResult.length; i++) {
    const obj = filteredResult[i][2]; // profile/12
    const permission = filteredResult[i][3]; // write
    const profileId = obj.split("/")[1]; // 12
    const profile = [db_query profiles table for profile id of **12**]
    response.push({
      ...profile,
      permission,
    });
  }

```
_Output: response_
```
  [
    {
      profile_table_row1_data
      permission: "write",
    },
    {
      profile_table_row2,data
      permission: "write",
    },
  ];
```
 It would be a great help if you could provide your suggestion in the above code. Looking forward to your response. Thanks :bow:

**Comment by hsluoyz** [comment]
@dipeshhkc define another column as "'editor', '28', 'profile', 'profile/12', 'write'", so you can do filtering with Casbin API.

**Comment by dipeshhkc** [comment]
@hsluoyz Thank you, this will reduce some lines of code. :bow

Regarding [this](https://github.com/casbin/node-casbin/issues/334#issuecomment-1003573108) can you please confirm that using single team in 2nd parameter is intended and need to follow my  workaround I mentioned to get the permissions he has for all the domains. Thanks

**Comment by hsluoyz** [comment]
@dipeshhkc `getImplicitPermissionsForUser()` only supports one team.
