### ISSUE TITLE
Use Regex to match any column while using Filtered API

### ISSUE THREAD

**Issue by dipeshhkc** [casbin/node-casbin#335]
Hello Developers 😁

Let us suppose this is a policy list.

```
p editor team1  profile:1 write
p admin  team1  domain:1 write
p editor team1  domain:2 read
p admin  team1  profile:2 write
```
If I want to load policy only containing object-related to profile (which means I need to exclude domains). Do we have something like below(using regex) or similar to obtain the desired result?

`enforcer.getFilteredPolicy(2,"/^profile/")`

_Desired Result_

```
p editor team1  profile:1 write
p admin  team1  profile:2 write
```
I am looking for any opinions, guidance, or suggestions. Thanks :pray:

**Comment by hsluoyz** [comment]
@dipeshhkc no, you can write SQL with regex directly: https://casbin.org/docs/en/policy-storage#database-storage-format
