### ISSUE TITLE
CasbinJsGetPermissionForUser's Test Failing 

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/node-casbin#339]
CasbinJsGetPermissionForUser's Test Failing in frontend.test.ts
![testfail](https://user-images.githubusercontent.com/87603425/150356840-a54c6618-020d-40ae-b6aa-d4feccb70a6c.PNG)

**Comment by Shivansh-yadav13** [comment]
@hsluoyz do you know why is this happening?

**Comment by hsluoyz** [comment]
@Gabriel-403 @Zxilly @kingiw @nodece

**Comment by Zxilly** [comment]
@Shivansh-yadav13 The main reason is git checkout the source files line break to `crlf (\r\n)`, but unit test hardcored `\n`.
Since old casbin.js has been deprecated, I didn't fix it.

**Comment by Shivansh-yadav13** [comment]
@Zxilly  Should I close this issue since it happened with me only on another system

**Comment by Zxilly** [comment]
@Shivansh-yadav13 This is indeed a bug, but clearly not of high priority. Maybe it will be fixed later and we can use this issue to track it.
