### ISSUE TITLE
Adapter error in removePolicies() for node.js

### ISSUE THREAD

**Issue by Harizriz** [casbin/node-casbin#346]
I got this error when trying to use the removePolicies() for casbin API to remove multiple policies.

```InvalidAdapterTypeError: removePolicies is only supported by SyncedAdapter. See newSyncedAdapter```

The code I used is shown below which I refer to the Casbin API docs. https://casbin.org/docs/en/management-api#:~:text=Copy-,RemovePolicies(),-RemovePolicies%20removes%20authorization

```
await this._enforcer.removePolicies([
      ['Marketing Group', 'default', 'test', '*'],
      ['Marketing Group', 'default', 'test2', 'read'],
    ]);
```

The adapter I am currently using right now is the latest ```MongooseAdapter```

```
try {
    const model = path.resolve(__dirname, './utils/model.conf');
    const adapter = await MongooseAdapter.newAdapter(mongoUrl);
    return newEnforcer(model, adapter);
  } catch (err) {
    return Promise.reject(err);
  }
```

I tried to find SyncedAdapter in this repo as well as the MongooseAdapter repo https://github.com/Sefriol/casbin-mongoose-adapter/tree/feature-synced-adapter but I couldn't find it. As seen in the Mongoose repo link, it's stated that the name of the branch is ```feature-synced-adapter```. Does anyone know why is this happening?

**Comment by hsluoyz** [comment]
@nodece @fabian4 @Zxilly

**Comment by Zxilly** [comment]
@Harizriz What you want is https://github.com/node-casbin/mongoose-adapter/blob/26c051cc2720071533e1cb50140180111dd109c6/src/adapter.ts#L152-L154
It use transaction for remove action.

**Comment by Zxilly** [comment]
@hsluoyz This is a issue of https://github.com/node-casbin/mongoose-adapter
