### ISSUE TITLE
bug: util.hasEval keeps RegExp state between invocations ('eval' is not detected'

### ISSUE THREAD

**Issue by grzegorz-kap** [casbin/node-casbin#348]
![image](https://user-images.githubusercontent.com/6129035/154477764-48f6af7c-00c6-45c9-9295-15791e0be69b.png)

```
const exp = "eval('true')"
hasEval(exp) -> true
hasEval(exp) -> false
hasEval(exp) -> true
....
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

![image](https://user-images.githubusercontent.com/6129035/154477375-e6cf5e16-be8d-4f38-b3f4-c315438dd1e7.png)

This is causing the following error:
![image](https://user-images.githubusercontent.com/6129035/154481427-2ce55f03-9588-4ed1-a0b5-936309200b73.png)

**Comment by Shivansh-yadav13** [comment]
@grzegorz-kap can you give any matcher example where it might not be detecting

**Comment by Shivansh-yadav13** [comment]
I think there is no problem with detecting `eval`, it is because some funcs in the matcher are not returning the type number or boolean due to which this error is occurring. I have made a PR [here](#347) to fix this, please add a review if more changes are required.

**Comment by Shivansh-yadav13** [comment]
@grzegorz-kap can you review #347, resetting the index manually
