### ISSUE TITLE
 O(1) time to query the RBAC tree

### ISSUE THREAD

**Issue by kerituni12** [casbin/node-casbin#350]
Follow the document of Casbin :

>  Casbin's RBAC is implemented by a role inheritance tree (as a cache). So given a user like Alice, Casbin only uses O(1) time to query the RBAC tree for role-user relationship and do enforcement.

as image below, i wonder why it goes through all the policies instead of just two policy data2_admin

![](https://i.ibb.co/hDjhLCd/Screenshot-from-2022-03-01-15-25-44.png)

**Comment by hsluoyz** [comment]
@nodece @Zxilly @fabian4

**Comment by Zxilly** [comment]
> Casbin's RBAC is implemented by a role inheritance tree (as a cache). So given a user like Alice, Casbin only uses O(1) time to query the RBAC tree for role-user relationship and do enforcement.

means `g()` function has `O(1)` time complexity, which means the number of `g policies` won't be a big problem to calculate result for they has been built as a role tree. But for all other `p policies` and the custom function, casbin need iterate through all policies, which is `O(n)`.

**Comment by kerituni12** [comment]
If i use custom function with p policies , it's actually O(n) but with g polices I think it's more than O(n)

https://casbin.org/casbin-editor/#BH4TYYEJ2


![](https://i.ibb.co/xCQL3CQ/Screenshot-from-2022-03-02-01-52-46.png)

**Comment by Zxilly** [comment]
For each policy, `g()` is `O(1)`. We have to iterate all policies so `enforce()` is always `O(n)`.
