### ISSUE TITLE
Node-Casbin@6 planning

### ISSUE THREAD

**Issue by nodece** [casbin/node-casbin#352]
Node-Casbin@6 full-support any JavaScript platform like React Native, Electron, and so on.

Branch: https://github.com/casbin/node-casbin/tree/beta

I make some planning  for this version:

- [x] Only support pass the `Model` instance, `Adapter` instance and `enableLog`  to `newEnforcer()`, avoid confusing that use path or text
- [x] Cleanup the code with "path", "file" 
- [ ] Collect the breaking changes, which is used to make a migrate doc

**Comment by nodece** [comment]
Yes, but some parameters are optional, so like:
```
newEnforcer(model)
newEnforcer(model, adapter)
newEnforcer(model, adapter, true)

// Not sure if is correct behavior.
newEnforcer(model, true)
```

We can open this issue for a while to discuss.

**Comment by Shivansh-yadav13** [comment]
ohk then I guess for a request like this 
```
newEnforcer(model, true)
```
we can maybe keep `...params: any[]` in the `newEnforcer()` and then pass them in a fixed manner in `newEnforcerWithClass(model, adapter, true)`

**Comment by nodece** [comment]
Both `newEnforcer()` and `newEnforcerWithClass` params need to changes.

**Comment by Shivansh-yadav13** [comment]
@nodece, there are no breaking changes on params change in the tests at least.

**Comment by nodece** [comment]
We remove some API with fs or path, this is breaking changes.

**Comment by hsluoyz** [comment]
We don't have the ability to control the damage caused by the breaking changes based on our developer resources. So we don't accept any kind of breaking changes.

**Comment by wittech** [comment]
how to config muti policies?

**Comment by Shivansh-yadav13** [comment]
@wittech if you have a question, you can ask in the Gitter channel https://gitter.im/casbin/Lobby

**Comment by nodece** [comment]
Migrating to https://github.com/casbin/casbin-core for this thing.
