### ISSUE TITLE
Wrong method in multiline parsing

### ISSUE THREAD

**Issue by moshekar** [casbin/node-casbin#354]
Hi,

Multiline parsing in config.ts is using .includes(), but should use .endsWith(), as the multiline separator is valid only at the end of the line.
https://github.com/casbin/node-casbin/blob/7803ccbd4cc25e2faac9b508ef57ebee2f8d5750/src/config.ts#L127

Thanks.

**Comment by hsluoyz** [comment]
@moshekar can you make a PR to fix it?

**Comment by moshekar** [comment]
> @moshekar can you make a PR to fix it?

Done: [PR #355](https://github.com/casbin/node-casbin/pull/355)
Thanks.

**Comment by Shivansh-yadav13** [comment]
@moshekar maybe create a pr again? as you may already know semantic pr was required for release.

**Comment by PrathamJaiswal001** [comment]
@hsluoyz can I make PR to this issue, is it still open?

**Comment by hsluoyz** [comment]
@PrathamJaiswal001 sure
