### ISSUE TITLE
Filter Policies

### ISSUE THREAD

**Issue by Gumplefik** [casbin/node-casbin#356]
I am using RBAC with resource.
Is there any better ways to find which sub has permission for specified object and action.
Same as find which object can be access for specified sub and action.

**Comment by Gumplefik** [comment]
```conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _
g2 = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && g2(r.obj, p.obj) && (p.act == '*' || r.act == p.act)
```

**Comment by hsluoyz** [comment]
@tangyang9464 @nodece @Zxilly

**Comment by Shivansh-yadav13** [comment]
@Gumplefik you can use `getFilteredPolicy` where you can do something like

```ts
const result = await e.getFilteredPolicy(1, obj, act) // according to your policy definition
```
result will be something like 
```ts
[ [ 'alice', 'data1', 'read' ], [ 'bob', 'data1', 'read' ] ]
``` 
and then maybe you can loop over the result

**Comment by Gumplefik** [comment]
@Shivansh-yadav13 if I have many user group. how do you solve this question. First you need to get groups. Then find their members. Finally Merge result. maybe it is too complex

**Comment by Shivansh-yadav13** [comment]
@Gumplefik we can add such feature, should be discussed with maintainers.

**Comment by hsluoyz** [comment]
@Gumplefik you can use BatchEnforce(): https://casbin.org/docs/en/data-permissions#2-use-batchenforce

**Comment by Shivansh-yadav13** [comment]
@hsluoyz Ig @Gumplefik is trying to get a list of all the subjects plus all the grouped subjects, not sure how BatchEnforce is going to help in this case? he is trying to sort of find a way to simplify it, without using multiple methods. please correct me if I'm worng @Gumplefik

**Comment by hsluoyz** [comment]
You can iterate on all subjects with BatchEnforce()
