### ISSUE TITLE
Policy effect allow-and-deny not return reason in EnforceEx

### ISSUE THREAD

**Issue by kerituni12** [casbin/node-casbin#362]
### Current behavior

Using policy effect allow-and-deny  `some(where (p.eft == allow)) && !some(where (p.eft == deny))` , reason not include in result when has allow matched

### Expected behavior

Return allow reason if there is at least one policy matched and no deny policy 

If matched deny return deny reason 

Other case return [] for reason mean not match allow and deny

**Comment by hsluoyz** [comment]
@kerituni12 does Golang Casbin return the reason you want?

**Comment by kerituni12** [comment]
Sorry I don't have much experience with golang

**Comment by hsluoyz** [comment]
@tangyang9464 @Shivansh-yadav13

**Comment by Shivansh-yadav13** [comment]
In Golang Casbin works and returns the deny reason, that needs to be added in node-casbin

**Comment by Shivansh-yadav13** [comment]
@hsluoyz not sure of go
Go Casbin I'm receiving some unexpected return.
like for policy `alice, data/1, read, allow` `e.EnforceEx("alice", "data/1", "read")`
`false [] invalid policy size: expected 4, got 3, pvals: [bob data/2 read]`

**Comment by Shivansh-yadav13** [comment]
we need to return allow reason, go-casbin works fine.

**Comment by Shivansh-yadav13** [comment]
please review #363
