### ISSUE TITLE
ESM import error

### ISSUE THREAD

**Issue by joel611** [casbin/node-casbin#365]
Hi,

When i add casbin into my project using SST, the error shows up on build process in typescript.
```
 Consider changing "picomatch" to a default import instead:
    node_modules/casbin/lib/esm/util/builtinOperators.js:15:7:
      15 │ import * as picomatch from 'picomatch';

Consider changing "parse" to a default import instead:
    node_modules/casbin/lib/esm/persist/helper.js:1:7:
      1 │ import * as parse from 'csv-parse/lib/sync';
```

Suggest to use default import on both file:
import picomatch from 'picomatch';
import parse from 'csv-parse/lib/sync';

**Comment by hsluoyz** [comment]
@Shivansh-yadav13

**Comment by Shivansh-yadav13** [comment]
> Hi,
> 
> When i add casbin into my project using SST, the error shows up on build process in typescript.
> 
> ```
>  Consider changing "picomatch" to a default import instead:
>     node_modules/casbin/lib/esm/util/builtinOperators.js:15:7:
>       15 │ import * as picomatch from 'picomatch';
> 
> Consider changing "parse" to a default import instead:
>     node_modules/casbin/lib/esm/persist/helper.js:1:7:
>       1 │ import * as parse from 'csv-parse/lib/sync';
> ```
> 
> **Suggest to use default import on both file**: import picomatch from 'picomatch'; import parse from 'csv-parse/lib/sync';

IG then we would need to change it for every file?

**Comment by hsluoyz** [comment]
@tangyang9464 @nodece @abichinger

**Comment by nodece** [comment]
I submitted #366 to fix this issue, could you review this PR?
