### ISSUE TITLE
Sequelize - PostgreSQL - Adapter

### ISSUE THREAD

**Issue by dograshvili** [casbin/node-casbin#367]
Hello,

I am using node-casbin with [casbin-sequelize-adapter
](https://www.npmjs.com/package/casbin-sequelize-adapter) with PostgreSQL. When i initialize the adapter, it creates a table in my database with the necessary fields (as it says on the documentation). What i want is to disable this functionality. I don't want a table to be created, i want to specify a table (for my case a view or a materialized view) of my choice (which i can through the options object), but NOT create the table. Dose anyone faced anything like this ? 

![casbin_create_tbl_stmt](https://user-images.githubusercontent.com/25210207/169520017-1b8f3c4a-1f9b-4010-b6b8-442021567dde.png)

**Comment by Shivansh-yadav13** [comment]
@dograshvili in the options you can pass in `tableName`

**Comment by dograshvili** [comment]
@Shivansh-yadav13 yes you can pass the tableName, but it doesn't solve the problem that the adapter will create the tableName you passed in the options. As i mentioned above what i want it to pass a view or materialized view in the tableName, but i don't want to create that table. I want to load the policy from the view or the mat view

**Comment by nodece** [comment]
@dograshvili Sorry, this feature is not supported, which is too flexible, and not easy to manage, you can fork this repository to adapt your project.

**Comment by hsluoyz** [comment]
Agreed with @nodece , closed here
