### ISSUE TITLE
[Enhancement] Mongo Change Stream Watcher

### ISSUE THREAD

**Issue by Sefriol** [casbin/node-casbin#382]
@hsluoyz @nodece Interested to put this under `node-casbin`? https://github.com/Sefriol/casbin-mongo-changestream-watcher/pull/1

**Comment by hsluoyz** [comment]
@Sefriol it looks great! New project is always welcome! Plz start a migration to `node-casbin` org

**Comment by Sefriol** [comment]
@hsluoyz I finalized the initial version. For `node-casbin` some minor things need to addressed in README. Main workflow's release script actually already points to `node-casbin/mongo-changestream-watcher`.

Some things like the NPM repository etc need to be created.

Shall I create the repository under `node-casbin`? Is the name ok?

**Comment by hsluoyz** [comment]
@Sefriol created here: https://github.com/node-casbin/mongo-changestream-watcher , you can make a PR to it.

The NPM name can be either `mongo-changestream-watcher` or `casbin-mongo-changestream-watcher`. You can setup the GitHub Actions CI and semantic-release like other repos, so it will automatically push to NPM.js
