### ISSUE TITLE
using with react (vite)

### ISSUE THREAD

**Issue by meodemsao** [casbin/node-casbin#386]
I have problem when using node-casbin with react

```typescript
import { newModel, Enforcer, newEnforcer } from 'casbin'
import { AuthActionVerb, AuthPossession, CustomAuthActionVerb } from 'constants/enum/auth'
import { ExecutionContext } from 'graphql/execution/execute'

import storage from './storage'

export type Permission = {
  resource: string
  action: AuthActionVerb | CustomAuthActionVerb
  possession?: AuthPossession
}

export const loadModel = () => {
  // rbac model
  const model = `
	[request_definition]
	r = sub, obj, act

	[policy_definition]
	p = sub, obj, act

	[role_definition]
	g = _, _

	[policy_effect]
	e = some(where (p.eft == allow))

	[matchers]
	m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act`

  const m = newModel()
  m.loadModelFromText(model)
  return m
}

export const loadPermissions = async (enforcer: Enforcer) => {
  const permissions = storage.getPermissions()
  await Promise.all([
    ...permissions.map((permission: any) => {
      return enforcer.addPolicy(permission[0], permission[1], permission[2])
    }),
  ])
}

export const initEnforcer = async (): Promise<Enforcer | null> => {
  const m = loadModel()

  const enforcer = await newEnforcer(m)

  await loadPermissions(enforcer)

  return enforcer
}
```

![Screen Shot 2022-09-13 at 4 18 16 PM](https://user-images.githubusercontent.com/570103/189863742-d30f6bdc-6e81-4659-a1cc-95f43d527686.png)

**Comment by hsluoyz** [comment]
@meodemsao did you try: https://github.com/casbin-js/react-authz ?

**Comment by Shivansh-yadav13** [comment]
@meodemsao you can try [ReactAuthz](https://github.com/casbin-js/react-authz), [Casbin-core](https://github.com/casbin/casbin-core), [Casbin.js](https://github.com/casbin/casbin.js), node-casbin is not really for frontend javascript

**Comment by nodece** [comment]
This looks like a dependency issue, @Shivansh-yadav13 Could you work on this?

**Comment by Shivansh-yadav13** [comment]
> This looks like a dependency issue, @Shivansh-yadav13 Could you work on this?

Ohk, I'll look into it.

**Comment by meodemsao** [comment]
> @meodemsao did you try: https://github.com/casbin-js/react-authz ?

i don't know how to use this, don't have any doc

**Comment by meodemsao** [comment]
> @meodemsao you can try [ReactAuthz](https://github.com/casbin-js/react-authz), [Casbin-core](https://github.com/casbin/casbin-core), [Casbin.js](https://github.com/casbin/casbin.js), node-casbin is not really for frontend javascript

i will try https://github.com/casbin/casbin-core

node-casbin work if i use with webpack, i have issue with vite

**Comment by Shivansh-yadav13** [comment]
@nodece @meodemsao  I feel the code is running in browser, that's why we are getting this error, do you think there could be a bug?

**Comment by nodece** [comment]
> @nodece @meodemsao I feel the code is running in browser, that's why we are getting this error, do you think there could be a bug or dependency error?

Looks like a dependency error, could you testing the the https://vitejs.dev/guide/ ?

**Comment by meodemsao** [comment]
@Shivansh-yadav13 @nodece i use casbin-core i work well

**Comment by nodece** [comment]
Because I use the minimatch instead of the picomatch.

**Comment by meodemsao** [comment]
> Because I use the minimatch instead of the picomatch.

thanks u

**Comment by Shivansh-yadav13** [comment]
> Because I use the minimatch instead of the picomatch.

@nodece should we do that in node-casbin also?

**Comment by ItsKDaniel** [comment]
This does not work with Vue + Vite as well. I am getting the same error when I tried using [vue-authz](https://github.com/casbin-js/vue-authz), or [casbin.js](https://github.com/casbin/casbin.js).

The issue is with polyfills for Node is not available in the main casbin npm package (node-casbin). Since casbin.js and the wrappers like react-authz, vue-authz are browser targeting libraries, we would require node polyfills to be available for the libraries to work.

**Comment by hsluoyz** [comment]
@imp2002 @Shivansh-yadav13 @nodece

**Comment by hsluoyz** [comment]
@ItsKDaniel casbin.js and the wrappers like react-authz are for browser only. It's not for Node.js . If you have other questions, please create new issue. Closed here.
