### ISSUE TITLE
add flag for errors from adapter in internal api

### ISSUE THREAD

**Issue by Shivansh-yadav13** [casbin/node-casbin#388]
@nodece has suggested to add a flag for getting a `not-implemented` error from the adapter.

I have a suggestion, add a flag for receiving all errors, meas if `true` we will throw errors even if it's a `not-implemented` error.

need a discussion on this.

_Originally posted by @nodece in https://github.com/casbin/node-casbin/pull/384#discussion_r967673880_

**Comment by ANUSHRAV01** [comment]
hello,I am new to this platform and interested in contributing as this seems fun .CAN u assign me and guide me to work on this issue
