### ISSUE TITLE
does the node-casbin support `subjectPriority`?

### ISSUE THREAD

**Issue by vaseala** [casbin/node-casbin#389]
This is the doc:  https://casbin.org/docs/priority-model#load-policy-with-priority-based-on-role-and-user-hierarchy
Then I place the demo code to the online editor: https://casbin.org/casbin-editor/#53YFYAD7M
When I click `RUN THE TEST` button, it throw `unsupported effect`!

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 plz implement it in Node-Casbin

/cc @nodece

**Comment by PrathamJaiswal001** [comment]
@hsluoyz sure, can you please provide some information regarding how to start solving it and where should I include the function of subjectPriority Hierarchy like in enforcer.ts file or somewhere else?

**Comment by hsluoyz** [comment]
@PrathamJaiswal001 refer to:

- Code: https://github.com/casbin/casbin/search?q=subjectPriority&type=issues
- Docs: https://casbin.org/docs/syntax-for-models#policy-effect:~:text=Priority-,subjectPriority,-(p.eft)

Refer to how Go Casbin implements it
