### ISSUE TITLE
e.SetFieldIndex() not available in node SDK 

### ISSUE THREAD

**Issue by elenasch** [casbin/node-casbin#390]
According to these docs, Golang SDK has the ability to configure field's index and allow for a different index on domain filed. NodeJS SDK however is missing this API 

Please add it to match Golang library

**Comment by Shivansh-yadav13** [comment]
@elenasch there is no `FieldIndexMap` in node-casbin

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 can you make a PR to add it?

**Comment by hsluoyz** [comment]
@imp2002 @Shivansh-yadav13
