### ISSUE TITLE
Ways to improve policy parsing times in an RBAC with domain model and filtered enforcer 

### ISSUE THREAD

**Issue by elenasch** [casbin/node-casbin#392]
I'm using the RBAC with domain model like below that would be loaded into a filtered enforcer (filtering by domain). 
Did some perf testing and majority of the time is being spent in parsing the rows into memory. Load times from data source seem to not be significant. The times rise as number of rows needing to be parsed grows.

I have a somewhat large number of policy rows to parse. Roughly 1000, and that is due to users being added to a domain. Currently testing with 500 users per domain, and multiple roles in a domain. Each role has several different capabilities . The example of policy below is to demo the structure of the policies and roles

Not sure there is much I can do to improve here, but wondering if there is any suggestion from your team for performance improvements I could look into 

**request example**
```
user:1, domain:1, draw_pictures, view
```

**policy**
```
# User roles in domain:1
# ----------------------------
p, general_users, domain:1, subscription:1, view
p, viewer, domain:1, general_users, view
p, editor, domain:1, viewer, view
p, admin, domain:1, editor, view

# domain:1 capabilities
# ------------------------------
p, general_users, domain:1, draw_pictures, view
p, general_users, domain:1, write_documents, view
p, editor, domain:1, write_emails, edit

# groups hierarchy in domain:1
# ---------------------------------
g, plan:1, general_users, domain:1
g, viewer, general_users, domain:1
g, editor, viewer, domain:1
g, admin, editor, domain:1

# users in user roles for domain:1
# -------------------------------------
g, user:1, admin, domain:1
g, user:2, general_users, domain:1
g, user:3, editor, domain:1


# features available to users roles in domain:1
# -------------------------------------------------
g2, write_documents, general_users, domain:1

# domain:1 plan features
g2, draw_pictures, plan:1, domain:1
g2, write_documents, plan:1, domain:1
g2, write_emails, plan:1, domain:1

```

**model**
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _
g2 = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, p.dom) && g2(r.obj, p.obj, p.dom) && r.act == p.act && r.dom == p.dom
```

**Comment by hsluoyz** [comment]
@imp2002 @Shivansh-yadav13 

/cc @nodece

**Comment by imp2002** [comment]
Time spent in parsing the rows into memory? Does it need to be loaded every time for authentication? Isn't it only loaded once when the application starts? Sorry, I don't know much about node applications, but in java, it only loads at startup and if you use distributed, you can also use watcher to avoid loading each time authentication. 👀

**Comment by hsluoyz** [comment]
@elenasch what Node.js web framework do you use?

**Comment by elenasch** [comment]
> @elenasch what Node.js web framework do you use?

just running a CLI for now, no frameworks, but just testing out node-casbin library ... NodeJS `v16.13.2`

**Comment by elenasch** [comment]
@imp2002 the idea is to load a filtered subset of policy for every request that would be coming in. Each request would contain information about which domain to use, and I'd want to load only the subset for that domain for faster lookups and enforce evaluations. 
As the number of domains/tenants grows loading everything in memory would also likely be an issue

**Comment by hsluoyz** [comment]
@elenasch you should keep cache (subset rules) in memory, this is how Casbin is designed to use.
