### ISSUE TITLE
Problem in Safari, v5.19.1

### ISSUE THREAD

**Issue by IonVillarreal** [casbin/node-casbin#395]
hello, since version 5.19.1, it cannot be executed in Safari (attached a screenshot)

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/12217695/198851313-fb0c8898-7e95-4c35-bb31-92c165fe4b61.png">

It seems that the problem is incompatibility with 'regex lookbehind' for Safari

https://caniuse.com/js-regexp-lookbehind

I don't have the error in version 5.19.0, I think the problem was added in the commit https://github.com/casbin/node-casbin/commit/5a339d858a9cfb7d8899355cbd179ec962b43cfa

for now, i will use v5.19.0

**Comment by hsluoyz** [comment]
@imp2002 

/cc @nodece

**Comment by und3fined** [comment]
Any fix for it?

**Comment by und3fined** [comment]
I have manual patch with
```javascript
function escapeAssertion(s) {
    s = s.replace(/\(r\./g, '(r_');
    s = s.replace(/ r\./g, ' r_');
    s = s.replace(/\(p\./g, '(p_');
    s = s.replace(/ p\./g, ' p_');
    return s;
}
```

**Comment by nodece** [comment]
> I have manual patch with
> 
> ```js
> function escapeAssertion(s) {
>     s = s.replace(/\(r\./g, '(r_');
>     s = s.replace(/ r\./g, ' r_');
>     s = s.replace(/\(p\./g, '(p_');
>     s = s.replace(/ p\./g, ' p_');
>     return s;
> }
> ```

It looks like a good idea, could you make a PR?
