### ISSUE TITLE
[Feature Request] separating packages

### ISSUE THREAD

**Issue by AtarisMio** [casbin/node-casbin#40]
It is recommended that separating packages to implement core functions and configuration/policy reads to facilitate multi-environment (e.g. web front-end) usage.

**Comment by hsluoyz** [comment]
@AtrisMio It current form unacceptable? Node-Casbin is mostly a backend project, because doing authorization in front-end is useless, the client-side can always be hacked. Or do you have specific feature requests about improvement for Casbin on client-side?

**Comment by hsluoyz** [comment]
This is something we already discussed about and indeed very useful. But we still did not start to do it. Do you have any suggestions on how to do it?

**Comment by hsluoyz** [comment]
Hi @AtrisMio we have started the front-end version Casbin named ``casbin.js``, see: https://github.com/casbin/casbin.js For further issues, please raise issue in that repo.

**Comment by nodece** [comment]
This is very good idea. I think it can be part of GSoC. 

Let's keep it open, I want to see other comments.

**Comment by hsluoyz** [comment]
OK. It can be part of this: https://github.com/casbin/SummerOfCode2020#casbinjs

**Comment by hsluoyz** [comment]
Casbin.js is already finished its first version, see:

https://casbin.org/docs/en/frontend
https://github.com/casbin/node-casbin/blob/27005f85829f11193cb4ecfd14be5ed6e64ad63c/test/frontend.test.ts
