### ISSUE TITLE
Upgrade CI Nodejs version to 14, 16, 18

### ISSUE THREAD

**Issue by hsluoyz** [casbin/node-casbin#408]
Node.js LTS is now 18: https://nodejs.org/en/ , which should be tested. 12 is too old and we can drop it to keep the list short. This is why we want to change to 14, 16, 18

![image](https://user-images.githubusercontent.com/3787410/210130686-dab488bf-7188-4ce0-85da-f6bf543cb899.png)

**Comment by saiwali** [comment]
@hsluoyz  I want to contribute but it seems there are no good first issues . Could you please help me how could I contribute to the community and get started ??

**Comment by hsluoyz** [comment]
@saiwali this issue is simple and seems to be a good first issue to work on

**Comment by PrathamJaiswal001** [comment]
@hsluoyz It looks like it is already using a version of Node.js that is compatible with the requirements of the casbin project. The project requires a version of Node.js that is greater than or equal to 14, and you are using version 16.14.2, which is higher than 14. Therefore, you should not need to upgrade the Node.js version used in the CI environment.

If you are having issues with the CI environment or with the build process, there may be other factors at play. If the build tests for Node.js versions 12, 14, and 16 are stuck in progress, it is possible that there is a problem with the test suite or with the CI environment. Also please elaborate the issue if you can.

**Comment by hsluoyz** [comment]
Node.js LTS is now 18: https://nodejs.org/en/ , which should be tested. 12 is too old and we can drop it to keep the list short. This is why we want to change to 14, 16, 18
