### ISSUE TITLE
Missing support of setNamedRoleManager()

### ISSUE THREAD

**Issue by JianhaoZhang** [casbin/node-casbin#413]
Related document link: [https://casbin.org/docs/rolemanager-api](https://casbin.org/docs/rolemanager-api)
It seems that node-casbin doesn't support `setNamedRoleManager()` as of now.
After going over the source code of CoreEnforcer, it seems to me supporting this API is likely a trivial effort?
Or am I overlooking some potential dependency issues?

I run into a model that requires changing maxHierarchyLevel of RoleManager for grouping rules other than the default rule 'g' so the API will comes in handy. 
Currently I am circumventing this issue in a tricky way and hope someone could shed some light on this.

**Comment by hsluoyz** [comment]
@JianhaoZhang hi, can you make a PR to add it?

**Comment by JianhaoZhang** [comment]
> @JianhaoZhang hi, can you make a PR to add it?

Yes I’d like to.
