### ISSUE TITLE
[RFC] Add a cli to generate type hint from model file.

### ISSUE THREAD

**Issue by Zxilly** [casbin/node-casbin#414]
As for now, node-casbin has api like

https://github.com/casbin/node-casbin/blob/a704ebb9f560c024643a468cbefc39fe80c5b484/src/coreEnforcer.ts#L566-L568

and

https://github.com/casbin/node-casbin/blob/a704ebb9f560c024643a468cbefc39fe80c5b484/src/coreEnforcer.ts#L599-L601

These api's always assume that the parameters are arrays of indefinite length and `any` type.

With a cli codegen, we can generate a type hint file like

```typescript
import { Enforcer } from "casbin";

declare module "casbin" {
    interface Enforcer {
        enforce(sub: string, obj: string, act: string): Promise<boolean>;
    }
}
```

from the model

```
[request_definition]
r = sub, obj, act
```

And we can get 

![image](https://user-images.githubusercontent.com/31370133/213469235-5caaaef0-c501-4a98-8deb-db04e1bf5fac.png)

while we use the api.

Some api like 

- `public getPolicy(sec: string, key: string): string[][]`
- `public addPolicy(sec: string, key: string, rule: string[]): boolean`
- ...

can also benefit from this.

If we go deeper into the parse of the matcher, we can build some utility types too.
For example, if a `subject` only be used in `ipMatch` function, we can use

```typescript
type ip = `${number}.${number}.${number}.${number}`
```

to help user get warning.

**Comment by perminder-17** [comment]
declare module "casbin" {
  interface Enforcer {
    enforce(sub: string, obj: string, act: string): Promise<boolean>;
    enforce(rvals: any[]): Promise<boolean>;
  }
}

public enforceSync(sub: string, obj: string, act: string): boolean;
public enforceSync(rvals: any[]): boolean;
public enforceSync(...rvals: any[]): boolean {
  return generatorRunSync(this.privateEnforce(false, false, ...rvals));
}

public async enforce(sub: string, obj: string, act: string): Promise<boolean>;
public async enforce(rvals: any[]): Promise<boolean>;
public async enforce(...rvals: any[]): Promise<boolean> {
  return generatorRunAsync(this.privateEnforce(true, false, ...rvals));
} 
please tell me about my solution
