### ISSUE TITLE
Using a readonly data source: Can you skip creation of the data source?

### ISSUE THREAD

**Issue by rogersgt** [casbin/node-casbin#418]
Hi Casbin community,

My company and I are using casbin in a service-oriented architecture where there are multiple applications reading the casbin_rule table on an RDS Aurora cluster in AWS (MySQL-compatible). We have one permissions API that is responsible for writing the policies to the casbin_rule table, and ideally we would allow other services to have a read only connection to the database cluster for reading the casbin policies. We use the https://www.npmjs.com/package/casbin-sequelize-adapter. The reason for wanting to use a read only connection for services not responsible for writing the data, is so that we can scale out horizontally with a loadbalanced cluster of read replica databases. This would be a huge performance gain when scaling enterprise software. However we are not able to do this because the sequelize adapter calls `CasbinRule.sync()` on `open()` which in turn runs `CREATE TABLE IF NOT EXISTS` every time we try and read the table. Not only does this error out on a read only connection in SQL, this also seems excessive to check this every single time. We handle creating our database and table via a migration outside of the application itself. 

Looking through the adapter code as well as other casbin adapters, it seems that this is a casbin pattern; and not necessarily a SQL adapter pattern. Is there a casbin way of not creating the data source every time we connect to the database? I was thinking of forking the sequelize adapter code and making a configuration option, but was curious if there was already a plan or pattern in place that I should reference.

Thanks in advance for any help!

**Comment by AbhinayPoloju** [comment]
You can modify the adapter code or extend it to add a configuration option to control the behavior of calling CasbinRule.sync() on open(). This way, you can avoid calling CREATE TABLE IF NOT EXISTS every time you connect to the database, which should solve the problem of the read-only connection error and the excessive table creation checks.

Alternatively, you can also consider using another Casbin adapter that supports read-only connections, such as the Casbin adapter for databases with read-only support.

**Comment by AbhinayPoloju** [comment]
Here is an example of how you can modify the sequelize-adapter to add a configuration option to control the behavior of CasbinRule.sync() on open():

javascript


const Sequelize = require('sequelize');
const casbin = require('casbin');

class CustomSequelizeAdapter extends casbin.SequelizeAdapter {
  constructor(options) {
    super(options);

    this.skipSync = options.skipSync || false;
  }

  async open() {
    await super.open();
    if (!this.skipSync) {
      await this.casbinRule.sync();
    }
  }
}

// Use the custom adapter in your Casbin enforcer:
const enforcer = await new casbin.Enforcer(modelPath, new CustomSequelizeAdapter(sequelizeOptions, { skipSync: true }));
In this example, you can pass { skipSync: true } in the sequelizeOptions to skip the call to CasbinRule.sync() on open().

Note that this is just a sample code and may need to be adapted to your specific use case.

**Comment by AbhinayPoloju** [comment]
Here's an example of how you can modify the sequelize-adapter in Node.js to add a configuration option to control the behavior of CasbinRule.sync() on open():

javascript

const Sequelize = require('sequelize');
const casbin = require('casbin');

class CustomSequelizeAdapter extends casbin.SequelizeAdapter {
  constructor(options) {
    super(options);

    this.skipSync = options.skipSync || false;
  }

  async open() {
    await super.open();
    if (!this.skipSync) {
      await this.casbinRule.sync();
    }
  }
}

// Use the custom adapter in your Casbin enforcer:
const enforcer = await new casbin.Enforcer(modelPath, new CustomSequelizeAdapter({
  ...sequelizeOptions,
  skipSync: true
}));
In this example, you can pass { skipSync: true } in the options object to skip the call to CasbinRule.sync() on open().

Note that this is just a sample code and may need to be adapted to your specific use case.

**Comment by hsluoyz** [comment]
@AbhinayPoloju the automatic replies have been removed. please don't use AI like ChatGPT to reply to issues again.

**Comment by Ra007hul** [comment]
Hey I am new in open source, can someone please help me to start
