### ISSUE TITLE
Some broken links in readme

### ISSUE THREAD

**Issue by judahb** [casbin/node-casbin#43]
Please fix these broken links in the readme

https://github.com/casbin/node-casbin/blob/master/src/main/java/org/casbin/node-casbin/main/Enforcer.java

https://github.com/casbin/node-casbin/blob/master/src/test/java/org/casbin/node-casbin/main/RbacAPIUnitTest.java

**Comment by nodece** [comment]
@judahb Thanks

**Comment by hsluoyz** [comment]
@judahb It has been fixed in: https://github.com/casbin/node-casbin/commit/bc30d3142171dbbb43d27e8b2e4820a0d59bfc39
