### ISSUE TITLE
Problem in ESM with Require function, v5.24.0

### ISSUE THREAD

**Issue by IonVillarreal** [casbin/node-casbin#434]
hi I have a warning when using node-casbin with ESM in NextJS in the file `./node_modules/casbin/lib/esm/index.js`

_Critical dependency: require function is used in a way in which dependencies cannot be statically extracted_

<img width="888" alt="Captura de pantalla 2023-02-23 a la(s) 11 02 11" src="https://user-images.githubusercontent.com/12217695/220944703-863f5f43-57ca-48d6-afb9-e76b2ad40aff.png">

The change was included in this pull request

https://github.com/casbin/node-casbin/pull/430

for now, i will use v5.23.2

**Comment by nodece** [comment]
Does v5.24.0 not work?

**Comment by IonVillarreal** [comment]
yes, in v5.24.0 I have the same warning

in version v5.23.2 that message does not appear

**Comment by hsluoyz** [comment]
@nodece given this issue is caused by: https://github.com/casbin/node-casbin/pull/430 , can you fix it?

**Comment by nodece** [comment]
Hi @IonVillarreal, could you check the https://github.com/casbin/node-casbin/pull/435?

**Comment by IonVillarreal** [comment]
Hi @nodece I just tried it, it works, the warning no longer appears 🙌
