### ISSUE TITLE
`RBAC with Domains API` # `e.getUsersForRoleInDomain` doesn't work.

### ISSUE THREAD

**Issue by vaseala** [casbin/node-casbin#445]
### model config file:
```
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

### enforcer
```
const storage = await TypeORMAdapter.newAdapter({
    type: 'postgres',
    host: 'xxxxxxxx',
    port: 5432,
    username: 'postgres',
    password: 'yyyyyyyy',
    database: 'zzzzzzzz',
  });
  // config file of model
  const conf = resolve(__dirname, '../../models/rbac.conf');
  const enforcer = await newEnforcer(conf, storage);
```

### the program code:
```
async function foo () {
    const policy = await enforcer.getPolicy();
    console.log('policy: ', policy);
    const roles = await enforcer.getRolesForUserInDomain('alice', 'org1');
    console.log('roles: ', roles);
}

```

### and the result, which does not return the roles in the domain:
![image](https://user-images.githubusercontent.com/12792057/229130909-84874d0a-46ea-4217-8b86-79f7761577e6.png)

**Comment by hsluoyz** [comment]
@vaseala 

1. Plz provide a full example code, which is able to run directly and reproduce your issue
2. Use the built-in CSV file adapter if this is not a TypeORMAdapter only issue.
3. Provide "what you got" and "what you expected" in the code comment

**Comment by vaseala** [comment]
> @vaseala
> 
> 1. Plz provide a full example code, which is able to run directly and reproduce your issue
> 2. Use the built-in CSV file adapter if this is not a TypeORMAdapter only issue. (otherwise, this issue should be fired at TypeORMAdapter's repo)
> 3. Provide "what you got" and "what you expected" in the code comment

Sorry, I found it was my fault, I mistook roles for permissions.
