### ISSUE TITLE
FileAdapter doesn't escape values when saving policy

### ISSUE THREAD

**Issue by pzet123** [casbin/node-casbin#448]
When loading in a policy CSV file using `FileAdapter` and attempting to save the policies back to the CSV file any values which were previously escaped using double quotes are no longer escaped.

Hence the policy which is initially stored as
`p, PolicyName, group, "regexMatch(r.act, ""(view)"")"`
gets saved as
`p, PolicyName, group, regexMatch(r.act, "(view)")`
after savePolicy is called.

This causes an issue as the `,` character in `regexMatch(r.act, "(view)")` is now treated as a delimiter since the value is no longer escaped. This causes an error upon attempting to load the policy from the file again.

I've created a temporary ad-hoc savePolicy function which surrounds the value in double quotes and replaces any instance of `"` with `""` within the value itself however it would be nice if `FileAdapter` was adapted to fully support escaping CSV values.

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by pzet123** [comment]
Any plans to fully support escaped values in CSV files?

**Comment by hsluoyz** [comment]
@pzet123 hi, can you make a PR?

**Comment by pzet123** [comment]
@hsluoyz Sure, I'll make a PR sometime this week.

**Comment by SnowingFox** [comment]
you mean we can provide an interface for users so that they can decide the action of escape character?

**Comment by hsluoyz** [comment]
@pzet123 fixed by: https://github.com/casbin/node-casbin/commit/17c542ad894cc19b592e3c54495fb05eff02f215
