### ISSUE TITLE
[question] enforcer api

### ISSUE THREAD

**Issue by dreamdevil00** [casbin/node-casbin#45]
`public async deleteRole(role: string): Promise<void>`
Why not return `Promise<boolean>` ?

`public async deleteRolesForUser(user: string): Promise<boolean> ` 
Why not add `domain` param

**Comment by dreamdevil00** [comment]
What would happen if there was two same username in different domain when I call `deleteRolesForUser()`

**Comment by nodece** [comment]
It will deletes all roles

**Comment by dreamdevil00** [comment]
I mean that I want to delete all roles for user in domain A not domain B(two usernames are same), is it possible? If there is something wrong, correct me please, Thank you

**Comment by nodece** [comment]
`deleteRolesForUser` will delete user in domain A and B(two usernames are same), so You should call `deleteRoleForUser()` specify `domain` param.

**Comment by dreamdevil00** [comment]
Got it! Thanks.
Why not make it `public async deleteRolesForUser(user: string, domain?:string): Promise<boolean> ` 

If the domain not provided, then delete all roles for a user(or users with the same name in different domain), otherwise delete all roles for a user in the domain

**Comment by hsluoyz** [comment]
@dreamdevil00 , about ``deleteRole()``'s returning boolean, it's a little complicated. In fact it has called two functions:

https://github.com/casbin/node-casbin/blob/10b28babccbe38686466c889d88919e22edb5431/src/enforcer.ts#L184-L192

Both ``removeFilteredGroupingPolicy()`` and ``removeFilteredPolicy()`` return boolean, it's not possible to return these two boolean values in one function return. So probably you should just call these two functions by yourself and check the two return values as you want.

**Comment by dreamdevil00** [comment]
@hsluoyz It seems no error with `deleteRolesForUser`

**Comment by hsluoyz** [comment]
Closed as resolved.
