### ISSUE TITLE
Casbin Watcher for Prisma ORM

### ISSUE THREAD

**Issue by Sedhupathi1411** [casbin/node-casbin#455]
I'm using Casbin with [Prisma adaptor](https://github.com/node-casbin/prisma-adapter) in my server (ExpressJS) code.
When I run multiple instances of the server, changes made my one instance is unaware on another instance.

[By this comment](https://github.com/casbin/node-casbin/issues/180#issuecomment-672565799), I came to know I have to add Watchers. But there are none for Prisma.

> Techs I'm using --> ExpressJS + Typescript + Casbin + Prisma ORM + PostgreSQL

Could you guys please help me?

**Comment by hsluoyz** [comment]
@Sedhupathi1411 AFAIK, Prisma is a ORM, not a messaging system. Can a watcher be made from it?

You should take a look at existing watchers: https://github.com/node-casbin?q=watcher&type=all&language=&sort=

**Comment by Sedhupathi1411** [comment]
No, prisma1 supported it, but prisma2+removed it (now it's version is 5x)
There's none for PostgreSQL in the watchers list you sent.

I found this (https://github.com/mcollina/casbin-pg-watcher) from the [Casbin website](https://casbin.org/docs/watchers/).
This might work for me.

**Comment by hsluoyz** [comment]
@Sedhupathi1411 yes, please try that one: https://github.com/mcollina/casbin-pg-watcher

Closed here for now
