### ISSUE TITLE
expression-eval@5.0.1: The expression-eval npm package is no longer maintained

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [casbin/node-casbin#459]
I get this error while installing casbin:
```
npm WARN deprecated expression-eval@5.0.1: The expression-eval npm package is no longer maintained. The package was originally published as part of a now-completed personal project, and I do not have incentives to continue maintenance.
```
I think that dependency should be upgraded.

**Comment by giovanni-bertoncelli** [comment]
Any thoughts on this? @nodece @hsluoyz 
We have production code running on this

**Comment by hsluoyz** [comment]
Forking `expression-eval` is the last resort. Because we don't have that many developers to focus on maintaining it at the same time. What about switching to: https://github.com/silentmatt/expr-eval ?
