### ISSUE TITLE
RoleManager interface return type

### ISSUE THREAD

**Issue by dreamdevil00** [casbin/node-casbin#46]
I see that the return type of function signature in `interface RoleManager` are not async value.
In fact, all functions related to IO operation in JavaScript should be async, for example: 

`getRoles(name: string, ...domain: string[]): string[];` 
Perhaps it will query database
So it should be

`getRoles(name: string, ...domain: string[]): Promise<string[]>`

for compatibility, maybe it can be 
`getRoles(name: string, ...domain: string[]): Promise<string[]> | string[]`

thoughts?

@nodece @hsluoyz

**Comment by nodece** [comment]
I agree with you point, but getRoles get data from cache in casbin, so return `string[]`.

**Comment by hsluoyz** [comment]
@dreamdevil00 currently, only one class: ``DefaultRoleManager`` implements the ``RoleManager`` interface. And ``DefaultRoleManager`` involves no IO operations like querying DB. Do you say that you have implemented a ``RoleManager`` that accesses DB? If yes, we can discuss about how to solve it.

**Comment by dreamdevil00** [comment]
Havn't but plan to. 

As the document says, 
`The role manager is used to manage the RBAC role hierarchy (user-role mapping) in node-Casbin. A role manager can retrieve the role data from node-Casbin policy rules or external sources such as LDAP, Okta, Auth0, Azure AD, etc.`

At my first glance,  database maybe in the `etc`, so role manager can retrieve  the role data from database and `getRoles(name: string, ...domain: string[]): string[];` is for it.

**Comment by dreamdevil00** [comment]
The return value of other functions in `RoleManager`(except `printRoles()`) maybe  async too, since they probably interact with database.

**Comment by hsluoyz** [comment]
I have changed those functions to async: https://github.com/casbin/node-casbin/commit/e40a13ffd8fbb2d924f36541beb24b3a02593261

But it seems to have bugs, because a lot of tests failed. I didn't find the cause. I'm not a JS expert actually. Can you help me find them? @dreamdevil00 @nodece

**Comment by hsluoyz** [comment]
It seems that the expression eval library ([expression-eval](https://github.com/donmccurdy/expression-eval) & [jsep](https://github.com/soney/jsep))  we used doesn't support to execute async functions. I have created issues to ask their authors:

1. https://github.com/donmccurdy/expression-eval/issues/22
2. https://github.com/soney/jsep/issues/97

**Comment by dreamdevil00** [comment]
Yes, please checkout esprima parse [demo page](http://esprima.org/demo/parse.html#)

**Comment by hsluoyz** [comment]
But it is a parser instead of an expression executor? I didn't find information about how to eval an expression with it.

**Comment by hsluoyz** [comment]
@dreamdevil00 , first thanks! Very impressive work!

I'm OK with the breaking change in ``enforce()``. But can you make your commit a PR and submit it to origin? Better let them publish a new release on NPM. Because it's good practice for Casbin to always follow official libraries, not a fork from third-party.

**Comment by dreamdevil00** [comment]
@hsluoyz expression-eval v2.0 has been published. check out here [npm link](https://www.npmjs.com/package/expression-eval/v/2.0.0)

**Comment by nodece** [comment]
Thanks, we will refactor as soon as possible.

**Comment by surgentt** [comment]
Hey interest in this fix as well. Please let me know if there is anything I can do to assist.

**Comment by nodece** [comment]
@dreamdevil00 @surgentt new version has been refactor in [here](https://github.com/nodece/node-casbin/commits/async_rolemanager).
please let me know if there is have any issue.

**Comment by sbutler** [comment]
Any progress on merging this to master? It's exactly what I need.

**Comment by nodece** [comment]
@sbutler  plan added, next major version.

**Comment by nodece** [comment]
@sbutler @dreamdevil00 
Hi, we has been publish a beta version to npm, call `yarn add casbin@beta`  install it.
