### ISSUE TITLE
[bug] When using ‘watcherEx’, deletion does not trigger it; you need to configure a ‘watcher’ for it to work.

### ISSUE THREAD

**Issue by Lce-Lemon** [casbin/node-casbin#465]
The issue is caused by incorrect conditional statements in [this code](https://github.com/casbin/node-casbin/blob/8be61872779729b3c2ca2054a29d24e5a0436349/src/internalEnforcer.ts#L166C7-L166C7
).

see ```removePolicyInternal``` and ```removePoliciesInternal``` 

![image](https://github.com/casbin/node-casbin/assets/26210044/e4ad2b75-618b-4f77-8447-327c64548aa9)

**Comment by hsluoyz** [comment]
@Lce-Lemon fixed in: https://github.com/casbin/node-casbin/releases/tag/v5.28.0
