### ISSUE TITLE
[Bug] The lack of a constructor results in the default configuration not taking effect.

### ISSUE THREAD

**Issue by Lce-Lemon** [casbin/node-casbin#466]
https://github.com/casbin/node-casbin/blob/8be61872779729b3c2ca2054a29d24e5a0436349/src/enforcer.ts#L25

**Comment by hsluoyz** [comment]
@Lce-Lemon why close?

**Comment by Lce-Lemon** [comment]
> @Lce-Lemon why close?

I remember encountering an issue with the ```prisma-adapter``` where automatic saving wasn't working. The documentation states that automatic saving is enabled by default, but I'm not entirely sure. Therefore, I closed this issue.
