### ISSUE TITLE
[Question] Can the cache stored in memory here be placed in Redis?

### ISSUE THREAD

**Issue by Lce-Lemon** [casbin/node-casbin#469]
When there are multiple instances, there are differences in the cache between instances.

Can the cache stored in memory [here](https://github.com/casbin/node-casbin/blob/cbd51ac88c3e185816465894f147dd18833a8cb9/src/model/model.ts#L51C60-L51C60) be placed in Redis?

**Comment by hsluoyz** [comment]
@Lce-Lemon Casbin is memory-first and memory cannot be removed. You need to use watcher to sync between multiple instances: https://casbin.org/docs/watchers/

**Comment by Lce-Lemon** [comment]
> @Lce-Lemon Casbin is memory-first and memory cannot be removed. You need to use watcher to sync between multiple instances: https://casbin.org/docs/watchers/

When using a Watcher in a concurrent environment with frequent permission updates, it may lead to frequent reloading of policy, impacting the performance of the service, especially when there are a large number of policies. In scenarios with concurrent operations and the addition of instances, there might be differences in policy data among multiple instances.
