### ISSUE TITLE
Enforcing with domains and 100k+ policies causing performance issues

### ISSUE THREAD

**Issue by jimcamut** [casbin/node-casbin#471]
We're experiencing CPU issues with over 100K+ policies/roles. Our setup is MongoDB with the suggested Typeorm adapter. 

According to @hsluoyz, "... you should keep cache (subset rules) in memory, this is how Casbin is designed to use." https://github.com/casbin/node-casbin/issues/392#issuecomment-1259549016

When using domains/tenants, how are we supposed to leverage Casbin in a more performant way? There aren't many examples.  `loadFilteredPolicy()` seems like it would be the solution, but it's not clear how this should be used?

Any suggestions? Much thanks!

**Comment by hsluoyz** [comment]
@jimcamut see performance optimization docs: https://casbin.org/docs/performance

**Comment by hsluoyz** [comment]
@jimcamut you mean you are loading rules from DB for 13 seconds? Then you need to consider it like reading DB slow. Like loading smaller size data, or make your DB near to your application, etc.
