### ISSUE TITLE
Fix: Discrepancy between `getAllNamedRoles` function implementation and comments

### ISSUE THREAD

**Issue by divyank-sc** [casbin/node-casbin#476]
Title: Discrepancy between `getAllNamedRoles` function implementation and comments

**Body:**

Hello,

I was going through the `getAllNamedRoles` function in the `managementEnforcer.ts` file and noticed a discrepancy between the function's implementation and the comments.

According to the comments, the function is supposed to collect the 0-index elements of the policy rules. However, in the implementation, it seems to be collecting the 1-index elements instead:

`  public async getAllNamedRoles(ptype: string): Promise<string[]> {
    return this.model.getValuesForFieldInPolicy('g', ptype, 1);
  }`

Could you please clarify if this is the intended behavior or if it's a mistake in the comments or the implementation?

In the meantime, could you suggest any alternative function that collects the 0-index elements as described in the comments?

Thank you for your time and for maintaining this project.

Best regards, 
Divyank

**Comment by hsluoyz** [comment]
@divyank-sc see Go Casbin

**Comment by divyank-sc** [comment]
The node implementation has comment stating that it fetches 0-index element. In go there isn't any such comment but underlying implementation seems same in both. Have attached SS below for your ref.

**PS**: Our project in which we are using casbin is in node:
<img width="919" alt="Screenshot 2024-04-28 at 4 18 12 PM" src="https://github.com/casbin/node-casbin/assets/166595131/ccd1965e-7caa-4e91-a284-74a8ab6a68ca">
<img width="707" alt="Screenshot 2024-04-28 at 4 18 20 PM" src="https://github.com/casbin/node-casbin/assets/166595131/476f8bb5-94fd-41b3-a2de-2688ecd876e4">

**Comment by hsluoyz** [comment]
@divyank-sc hi, can you make a PR to fix it?

**Comment by divyank-sc** [comment]
Have raised the PR, please let me know of PR semantics related if any in the raised PR.

**Comment by hsluoyz** [comment]
Closed, see: https://github.com/casbin/node-casbin/pull/477#issuecomment-2082355776
