### ISSUE TITLE
keyMatch2('/abc', '/') must return false

### ISSUE THREAD

**Issue by murzatayev** [casbin/node-casbin#48]
There is currently an issue in the way keyMatch2 is working. I think this expression `keyMatch2('/abc', '/') must return `false`.

This could be related to this issue recently fixed in go version https://github.com/casbin/casbin/issues/199

**Comment by hsluoyz** [comment]
@murzatayev it has been fixed in: https://github.com/casbin/node-casbin/commit/5335c3e24126f321a24a911816b3154976ba83af
