### ISSUE TITLE
How I have to start casbin with nodejs

### ISSUE THREAD

**Issue by Jagadhissh** [casbin/node-casbin#49]
Hi sir
Iam new to Nodejs casbin how can I proceed with this
Simply
I have 3 defrent roles
1.admin
2. interviewer
3.candidate
Each and every person has his individual permissions to acces his data how can do this using Nodejs casbin
Please suggest me... With examples 
Thanks in advance

**Comment by hsluoyz** [comment]
@Jagadhissh please look at these issues related to RBAC: https://github.com/casbin/casbin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+rbac

You will find the answer probably.

**Comment by Jagadhissh** [comment]
Sorry.. Iam unable to understand that...
Can u give some examples using casbin Nodejs sir

**Comment by Jagadhissh** [comment]
That no queries related to me sir

**Comment by nodece** [comment]
Here have a repo [https://github.com/nodece/casbin-examples](https://github.com/nodece/casbin-examples), maybe can help you.

**Comment by hsluoyz** [comment]
Closed as stale.
