### ISSUE TITLE
Policies consistency

### ISSUE THREAD

**Issue by lucasrolim-intuitive** [casbin/node-casbin#52]
I'm having some issues of inconsistency when updating my table rules directly from the database. If I change some data in my database it only reflects on casbin after restarting the application.

I'm using the Sequelizer adapter at the moment.

What is the optimal way to solve this?

**Comment by hsluoyz** [comment]
Hi @lucasrolim-intuitive , the question here would be how you want to notify Casbin to load your new policy rules? There can several ways:

1. Periodically load the rules: https://github.com/casbin/casbin/#multi-threading
2. Use messaging system to notify: https://github.com/casbin/casbin/#policy-consistence-between-multiple-nodes
3. Or you can customize a mechanism to call ``LoadPolicy()`` in Casbin, like finding some sort of way to detect changes of DB, then call it.

**Comment by hsluoyz** [comment]
Closed as stale.
