### ISSUE TITLE
Using "keyMatch" in the "g" function

### ISSUE THREAD

**Issue by brandonjparrott** [casbin/node-casbin#53]
I was wondering if it's possible to use the keyMatch function within the g function? 

I am attempting to use the domain/tenant as an account and a user could have a role per account or a role for all accounts. 

My Model:

```
[request_definition]
r = subject, resource, action, account

[policy_definition]
p = subject, resource, action, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.subject, p.subject, r.account) && keyMatch(r.action, p.action) && (r.resource == p.resource)
```

My Policies:

```
p, role:tester, resource, read:*, allow
g, user:1, role:tester, account:*
g, user:2, role:tester, account:21
```
User 1 has access to the role tester for all accounts. User 2 has access to the role tester for only account 21. 

I have tried doing something along to the lines of this but it doesn't seem to work.

```
m = g(r.subject, p.subject, keyMatch(r.account, p.account) && keyMatch(r.action, p.action) && (r.resource == p.resource)
```

**Comment by nodece** [comment]
You can try implements `RoleManager` interface then call `setRoleManager` and `buildRoleLinks` method in Enforcer.

**Comment by nodece** [comment]
Hi @brandonjparrott 
If you have any questions, please reopen it.
