### ISSUE TITLE
where can I get a complete API reference ?

### ISSUE THREAD

**Issue by zhaochy1990** [casbin/node-casbin#54]
I went over the official docs, but only found this https://casbin.org/docs/en/api

Is there anywhere to get a Node.js version API reference?

**Comment by nodece** [comment]
Node.js version API
https://github.com/casbin/node-casbin/blob/master/src/managementEnforcer.ts
https://github.com/casbin/node-casbin/blob/master/src/enforcer.ts

**Comment by nodece** [comment]
please reopen it  if you have any questions.

**Comment by dreamdevil00** [comment]
It would be better to have api docs on official website. It's more obvious. What do you think? @nodece

**Comment by nodece** [comment]
Great! We are migrating documents.

**Comment by hsluoyz** [comment]
@zhaochy1990 @dreamdevil00 the API docs is finished by @nodece , see:

https://casbin.org/docs/en/management-api
https://casbin.org/docs/en/rbac-api
