### ISSUE TITLE
Documentation has two broken links @ "See here for examples."

### ISSUE THREAD

**Issue by cube-dan** [casbin/node-casbin#57]
Heads up!

On this page: https://github.com/casbin/node-casbin#policy-management, under the **Policy Management** header, the links to your examples for 1) **Management API**, and 2) **RBAC API** are returning 404. 

Specifically, the links have the word _here_ linked in the sentence "See _here_ for examples."
The two urls set on the word here are, respectively:
1. https://github.com/casbin/node-casbin/blob/master/src/test/java/org/casbin/node-casbin/main/ManagementAPIUnitTest.java
2. https://github.com/casbin/node-casbin/blob/master/src/test/java/org/casbin/node-casbin/main/RbacAPIUnitTest.java
...which point to .java files instead of {.js|.jsx|.ts} files?

Thanks for your time.

-Dan

**Comment by nodece** [comment]
Thanks, now it is fixed.
