### ISSUE TITLE
Multiline matchers support

### ISSUE THREAD

**Issue by sarneeh** [casbin/node-casbin#59]
Golang's `casbin` [supports](https://github.com/casbin/casbin#how-it-works) multiline matchers, but this does not seem to work in the node version (I'm getting a `Error: Unexpected "\" at ...`).

It would be great to support this use case.

**Comment by nodece** [comment]
Thanks, Added plan.

**Comment by nodece** [comment]
@sarneeh We have released a new version to npm, you try install new version.

**Comment by sarneeh** [comment]
Thank you!
