### ISSUE TITLE
All policies getting deleted from the database

### ISSUE THREAD

**Issue by pspani** [casbin/node-casbin#61]
Issue:
All the policies in the casbin_rules DB are getting cleared when we try adding a new policy to the DB. 

Description:
The casbin library is being used in an authorizer function that's being executed in a lambda function on AWS. After a certain number of policies in the DB, when we try adding a new policy, it looks like the node-casbin library is truncating the table and then adds the new policy. 
I am using a mysql db with the typeorm adapter. 

The [code](https://github.com/tmobile/jazz/blob/d50c4aa5c9d714bb550dd5eb168b3b6faa8b2562/core/jazz_acl/components/casbin.js#L175)

Any help would be greatly appreciated.

**Comment by nodece** [comment]
Yes. first delete all policy then renew add all policy.

**Comment by pspani** [comment]
Appreciate the quick response. I didn't understand your comment. On the adapter level, I see whenever we save policy we delete all the policies and add the polices again. But on the node-casbin level, after we create a new enforcer we only need to do an add policy and then a save policy. 

In the code, we are saving the policy whenever we do add policy.

**Comment by nodece** [comment]
casbin enable autosave by default. 
Call `addPolicy()` method then casbin will add a new policy to DB. 
`savePolicy()` method will delete all policy then save all policy.

**Comment by devsatishm** [comment]
@nodece  When we add a new policy, should we avoid calling `savePolicy()` after `addPolicy()`  - To avoid cleanup of entries each time?

**Comment by hsluoyz** [comment]
Hi @devsatishm @pspani , when ``AutoSave`` feature is supported and enabled on the adapter, you don't need to call ``savePolicy()`` manually, your policy will be automatically saved from local enforcer memory to the remote DB each time you call ``addPolicy()``. See: https://casbin.org/docs/en/adapters#autosave

As far as I know, all our Node.js adapters support ``AutoSave``.

**Comment by devsatishm** [comment]
@hsluoyz Cool, thanks for the reply! We've just tested by removing the call to savePolicy() and it seems to work as you've mentioned.

Good work on the project, we have started using casbin for implementing the ACL/Permission model in our opensource project - https://github.com/tmobile/jazz. Also, we're thinking of contributing back by putting together DynamoDB adapter in NodeJs.

**Comment by hsluoyz** [comment]
Good to hear it works! I have added your project to our site: https://casbin.org/ Let us know if you have more questions and welcome contributing back :)
