### ISSUE TITLE
RBAC filtering roles based on domain

### ISSUE THREAD

**Issue by zmilan** [casbin/node-casbin#62]
Hi,

I have set up "Role definition with domains tenants" model and it works well when I use enforce() to check user permission per domain. But is there an option to filter role listing per domain? getAllRoles() return all roles for all domains and I didn't find any other way that can return me filtered roles.

**Comment by nodece** [comment]
@zmilan  Please call [`getFilteredPolicy`](https://casbin.org/docs/en/management-api#getfilteredpolicy) or [`getFilteredGroupingPolicy `](https://casbin.org/docs/en/management-api#getfilteredgroupingpolicy).

**Comment by zmilan** [comment]
Hi, @nodece, 

Thanks for helping me. I have called them too, but the result is not exactly what I expected. Here are some examples:

getAllRoles() result:
0: "Section1Admin"
1: "Section2Admin"
2: "Section3Admin"
3: "Section4Admin"
4: "Section5Admin"
5: "Section6Admin"
6: "DomainAdmin"
7: "DomainUser"
In this result records from 0-6 are records that exist on all domains, but record 7 exists only on domain2.

getFilteredGroupingPolicy(2, 'domain1')
0: (3) ["DomainAdmin", "Section1Admin", "domain1"]
1: (3) ["DomainAdmin", "Section2Admin", "domain1"]
2: (3) ["DomainAdmin", "Section3Admin", "domain1"]
3: (3) ["DomainAdmin", "Section4Admin", "domain1"]
4: (3) ["DomainAdmin", "Section5Admin", "domain1"]
5: (3) ["DomainAdmin", "Section6Admin", "domain1"]
6: (3) ["u1", "DomainAdmin", "domain1"]
In this result I have got right roles for only one domain, except that they are not in easy read format like result from getAllRoles(), but the record 6 is actually user assignment, which is not role ["u1", "DomainAdmin", "domain1"]...

getFilteredPolicy(1, 'domain1')
0: (5) ["Section1Admin", "domain1", "accessToSection1", "*", "allow"]
1: (5) ["Section2Admin", "domain1", "accessToSection2", "*", "allow"]
2: (5) ["Section3Admin", "domain1", "accessToSection3", "*", "allow"]
3: (5) ["Section4Admin", "domain1", "accessToSection4", "*", "allow"]
4: (5) ["Section5Admin", "domain1", "accessToSection5", "*", "allow"]
5: (5) ["Section6Admin", "domain1", "accessToSection6", "*", "allow"]
In this result I have got exactly what I wish but that are policies not role list, since *DomainAdmin* are omited since there is no direct policy assigned to it, it only inherit policy trough sub roles...

I have also try to use different naming for named grouping, for example, to add domain id like g1, g2, etc... so I would be able to list them based on that parameter, but in that case, enforce() doesn't work... 

Am I doing something wrong here?

**Comment by nodece** [comment]
@zmilan Can you provide a minimal reop and write some test code?

**Comment by hsluoyz** [comment]
> In this result I have got right roles for only one domain, except that they are not in easy read format like result from getAllRoles(), but the record 6 is actually user assignment, which is not role ["u1", "DomainAdmin", "domain1"]...

Casbin doesn't distinguish between user and role, see: https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user

> In this result I have got exactly what I wish but that are policies not role list, since DomainAdmin are omited since there is no direct policy assigned to it, it only inherit policy trough sub roles...

To query implicit roles or permissions, you have to use two "implicit" API functions. All other functions (except ``Enforce()``) can only see direct roles or permissions. See: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

**Comment by zmilan** [comment]
@hsluoyz thanks for your comment and references... 

> Casbin doesn't distinguish between user and role, see: https://casbin.org/docs/en/rbac#how-to-distinguish-role-from-user

I have already solved it that way, by making distinguish between user and role names... I was just thinking that there is some better way of doing it... especially because with a lot of users filtering roles would get slower...

> To query implicit roles or permissions, you have to use two "implicit" API functions. All other functions (except Enforce()) can only see direct roles or permissions. See: https://casbin.org/docs/en/rbac#how-to-query-implicit-roles-or-permissions

These functions are not implemented in [node](https://casbin.org/docs/en/rbac-api#getimplicitrolesforuser) version of casbin...

@nodece I would like to help, but I'm not totally sure what exactly you are requesting from me. Could you explain it more, thanks...

**Comment by nodece** [comment]
Because I do not understand your commit. 
Good news, Casbin v2.0.3 has been published to npm.
It has been supported getImplicitRolesForUser and getImplicitPermissionsForUser method.

**Comment by zmilan** [comment]
@nodece I'm sorry for the misunderstanding. I wasn't speaking about an issue in these functions (`getFilteredPolicy` or `getFilteredGroupingPolicy`), I was just describing what I'm getting like results and that it is not something that I would think of a like replacement for `getAllRoles`... after @hsluoyz last response it is clear what would be way to get what I need, so I would proceed that way...
And I'm really thankful for supporting `getImplicitRolesForUser` and `getImplicitPermissionsForUser` methods...
