### ISSUE TITLE
keyMatch() matches unwanted policies

### ISSUE THREAD

**Issue by Jarvie8176** [casbin/node-casbin#66]
Hi,

Suppose I have a model and policies defined as:

``` ini
p, obj
r, obj
e, some(where (p.eft == allow))
m, keyMatch(r.obj. p.obj)
```

```
p, alice:*:* 
p, alice:*:A
p, alice:*:B
```

Is it correct for me to expect `keyMatch()` to behave as a glob matching, so that for the request `r, alice:*:A`, only policies `p, alice:*:*` and `p, alice:*:A` would be matched?

## Test case

``` javascript
test('matcherWithGlob', async () => {
  let count: number;
  const cb = (...args: string[]): boolean => {
    console.log(args);
    count += 1;
    return true;
  };
  const m = newModel();
  m.addDef('r', 'r', 'obj');
  m.addDef('p', 'p', 'obj');
  m.addDef('e', 'e', 'some(where (p.eft == allow))');
  m.addDef('m', 'm', 'keyMatch(r.obj, p.obj) && cb(r.obj, p.obj)');
  const e = await newEnforcer(m);
  await e.addPolicy('alice:*:*');
  await e.addPolicy('alice:*:A');
  await e.addPolicy('alice:*:B');
  e.addFunction('cb', cb);

  count = 0;
  await e.enforce('alice:resource1:A'); // cb() should be called twice because of short-circuit evaluation
  expect(count).toEqual(2); 
});
```

## Output

``` bash
  console.log test/enforcer.test.ts:24
    [ 'alice:resource1:A', 'alice:*:*' ]

  console.log test/enforcer.test.ts:24
    [ 'alice:resource1:A', 'alice:*:A' ]

  console.log test/enforcer.test.ts:24
    [ 'alice:resource1:A', 'alice:*:B' ]


Error: expect(received).toEqual(expected)

Expected: 2
Received: 3
Expected :2
Actual   :3
 <Click to see difference>


      39 |   count = 0;
      40 |   await e.enforce('alice:resource1:A');
    > 41 |   expect(count).toEqual(2);
         |                 ^
      42 | });
      43 | 
      44 | function testGetPolicy(e: Enforcer, res: string[][]) {

      at Object.<anonymous> (test/enforcer.test.ts:41:17)
      at fulfilled (test/enforcer.test.ts:17:58)
```

**Comment by nodece** [comment]
YES. It is match all policy.

**Comment by hsluoyz** [comment]
Hi @Jarvie8176 , node-casbin internally uses [expression-eval](https://github.com/donmccurdy/expression-eval) to evaluate the matcher. Probably it doesn't support short-circuit. If you want this feature, you can ask this in their repo's issues.

**Comment by Jarvie8176** [comment]
> Hi @Jarvie8176 , node-casbin internally uses [expression-eval](https://github.com/donmccurdy/expression-eval) to evaluate the matcher. Probably it doesn't support short-circuit. If you want this feature, you can ask this in their repo's issues.

Do you mean `keyMatch()` should match all policies in this case?

**Comment by nodece** [comment]
Casbin need call policy_effect determines the return value after match all polices.

**Comment by Jarvie8176** [comment]
The test would pass if I used `regexMatch()` instead of `keyMatch()`. I think my question is what should `keyMatch("alice:res1:A", "alice:*:B")` return?

**Comment by hsluoyz** [comment]
Hi @Jarvie8176 , ``keyMatch("alice:res1:A", "alice:*:B")`` should return false. See:

https://github.com/casbin/casbin/blob/9814ac94c19c922c0afd5c2f34255e0d543ef372/util/builtin_operators.go#L25-L37

**Comment by Jarvie8176** [comment]
I wrote a failing test here: https://github.com/Jarvie8176/node-casbin/commit/d66e4a151a2f7e7d0c41ea6152f67922b598c54b

It looks like `keyMatch()`'s precondition is that the wildcard, if exists, should be the last character in `key2` but that is satisfied in this case. To match wildcard probably it probably has to be a DP algorithm.  Would you consider using utility libraries (e.g. [matcher](https://github.com/sindresorhus/matcher) or [minimatch](https://github.com/isaacs/minimatch)) to offload complexity?

**Comment by hsluoyz** [comment]
@Jarvie8176 ``keyMatch()`` assumes that * is the last character of the string. It is not designed to handle cases like ``alice:*:B``. Please use ``regexMatch()`` for your scenario. You can add your own custom function to Casbin too.
