### ISSUE TITLE
escape of '.' or just using '.' in regexMatch fails

### ISSUE THREAD

**Issue by SimonX200** [casbin/node-casbin#71]
```ini
[request_definition]
r = sub, obj, role, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = permitted(r.sub, r.obj, r.role, r.act) && (created(r.sub, r.obj) || owned(r.sub, r.obj) || (isGlobal(r.obj) && regexMatch(r.act, '.*get$') && !regexMatch(r.act, '.user.')))
```

``regexMatch(r.act, '.user.')`` translate to `.user_` which is passed to:

```js
function regexMatch(key1, key2) {
    return new RegExp(key2).test(key1);
}
```

as ``key2``

Trying to use one of:
```js
regexMatch(r.act, '\.user') 
regexMatch(r.act, '\\.user') 
regexMatch(r.act, '\\\.user') 
regexMatch(r.act, '\\\\.user') 
```

Leads to an TypeError.

```js
const expString = this.model.model.get('m').get('m').value
```

```
TypeError: Cannot read property 'get' of undefined
    at Enforcer.<anonymous> (node_modules\casbin\lib\coreEnforcer.js:254:56)
    at Generator.next (<anonymous>)
    at node_modules\casbin\lib\coreEnforcer.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules\casbin\lib\coreEnforcer.js:16:12)
    at Enforcer.enforce (s:\workspace\vsts\boge-connect\server\node_modules\casbin\lib\coreEnforcer.js:239:16)
```
Any suggestions?

**Comment by nodece** [comment]
@SimonX200  It's work when I attempt to get expString from this model. Can you provider a minimal repo?

**Comment by hsluoyz** [comment]
@nodece , I think he means that the ".user." string in ``regexMatch(r.act, '.user.')`` will be escaped to ".user_" string by the ``escapeAssertion()`` function. Because Casbin will do escaping like ``r.sub`` -> ``r_sub``. But obviously, the ".user." string in this issue is purely from Casbin users and should not be escaped.

https://github.com/casbin/node-casbin/blob/3111163c69bb43ca68a170efef933d2e819ad936/src/util/util.ts#L18-L24

**Comment by hsluoyz** [comment]
Hi @SimonX200 , can you give a minimized working example for this?

**Comment by SimonX200** [comment]
----- test-model.conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = regexMatch(r.act, '.user.')


-----  casbin-test.js

const casbin = require('casbin');
const path = require('path');

(async () => {
  try {
    const model_file = path.join(__dirname, 'test-model.conf');
    const enforcer = await casbin.newEnforcer(model_file);
    const res = await enforcer.enforce('sub', 'obj', 'obj.user.get');
    console.log(res);
  } catch (err) {
    console.log(err.stack || err);
  }
})();

-----

You can play around with the regexp string e.g. by trying to match the "." with "\."

**Comment by nodece** [comment]
@SimonX200 Thanks for the report! I published a new version to npm.

**Comment by nodece** [comment]
@SimonX200  Use `m = regexMatch(r.act, '.user.')` is work.

**Comment by hsluoyz** [comment]
Hi @SimonX200 BTW, I saw you are using single quote ' instead of double quote " in the matcher. This is not following Casbin model grammar. Even if it works now, we may remove its support in future release. Please change to using double quote ".
