### ISSUE TITLE
[Feature Request] Support string policy

### ISSUE THREAD

**Issue by calebfaruki** [casbin/node-casbin#73]
## Problem

This library would be much easier to support and implement against if the expected policy document was a string instead of a file or database connection.

## Question

Is there a way for us to pass the policy document as a string? If so, could you provide an example?

## Context

Using GraphQL, we pass a policy CSV in the context of a request and check authorization against the policy document multiple times. Therefore, it's far better to have the policy in-memory before asserting against it. Moreover, this policy document originates from the database for security reasons as we don't want to expose a user's given role-based policy document.

If we were to pass in a database connection, we would have to do a DB call for every node of the GraphQL request, which means N+1 database calls.

Otherwise, I would have to write a file to the /tmp directory of our server, read file for every node, then garbage collect on it. This is a potential security vulnerability as we don't want a user's RBAC policies exposed in our file system.

## Implementation
```js
const { newEnforcer } = require('casbin')
const isAuthorized = (sub, obj, act) => {
  return rule()(
    async function (parent, args, ctx, info) {
      try {
        const enforcer = await newEnforcer(`${__dirname}/model.conf`, ctx.policy)
        enforcer.enforce(sub, obj, act)
        return enforcer.enforce(sub, obj, act)
      } catch (err) {
        console.error(err)
        return false
      }
    }
  )
}
```

**Comment by calebfaruki** [comment]
I was able to circumvent this problem by ducktyping a so-called StringAdapter in JavaScript.

```js
const { Helper } = require('casbin/lib/persist/helper')

module.exports = class StringAdapter {
  constructor (policyString) {
    console.log('I\'m a string adapter')
    this.policy = policyString
  }
  async loadPolicy (model) {
    if (!this.policy) {
      throw new Error('Invalid policy, policy document cannot be false-y')
    }
    await this.loadRules(model, Helper.loadPolicyLine)
  }

  async loadRules (model, handler) {
    const rules = this.policy.split('\n')
    rules.forEach((n, index) => {
      const line = n.trim()
      if (!line) {
        return
      }
      handler(n, model)
    })
  }
}
```

**Comment by calebfaruki** [comment]
Re-opened in case this is worth discussing.

**Comment by hsluoyz** [comment]
Hi @calebfaruki , I think the StringAdapter way you used is the correct solution. For serving the wider community, would you like to contribute by packaging the StringAdapter into a GitHub repo and uploading it to npm so others can also use it? It will be very helpful.

**Comment by calebfaruki** [comment]
https://github.com/casbin/node-casbin/pull/74

**Comment by hsluoyz** [comment]
Merged: https://github.com/casbin/node-casbin/pull/74
