### ISSUE TITLE
Using enforce on view to show/hide different elements

### ISSUE THREAD

**Issue by krayis** [casbin/node-casbin#75]
I'm doing something along the lines of:
`res.locals.enforcer = enforcer;`

Using ejs for my templating I do something like:
`<% if (enforcer.enforce(sub, obj, act) == true)  { } %>

The problem is ejs render the template synchronously and the method enforce is async and returns a promise.. so this doesn't work.

Apparently theres a frontend implementation which returns synchronously and if I used this instead of the node-casbin to create my enforcer it works: 
https://github.com/casbin/casbin-website/blob/master/website/static/js/casbin.js

But I'm not sure if this is the correct way to show/hide different elements based on their permissions. Is there anyway to use enforce synchronous from this package?

**Comment by nodece** [comment]
You can use node-Casbin v2.x, It's enforce is synchronous.

**Comment by krayis** [comment]
@nodece Thank you that works!
