### ISSUE TITLE
Same calls with different results

### ISSUE THREAD

**Issue by oliujunk** [casbin/node-casbin#83]
node: v10.16.0, casbin: v3.0.3
Policies are stored in mysql, first call console.log(await enforcer.getUsersForRole('consumer')), return [ 'YFKJ187244601', 'test' ], second call console.log(await enforcer.getUsersForRole('consumer')), return [ 'YFKJ187244601', 'test', '7792707', 'bjdxt' ], .....It's different every time.
I am also try  to store policies  in redis, the test result are same.
The policies about 40 items.
![call](https://user-images.githubusercontent.com/19910324/62908386-559db680-bdaa-11e9-92eb-0faccda52f60.jpg)
![return](https://user-images.githubusercontent.com/19910324/62908391-59c9d400-bdaa-11e9-8316-1cbb604d7bda.jpg)
![policy1](https://user-images.githubusercontent.com/19910324/62908394-5c2c2e00-bdaa-11e9-824b-58f678d0b08a.jpg)
![policy2](https://user-images.githubusercontent.com/19910324/62908396-5f271e80-bdaa-11e9-95fc-3a02e8b5d24f.jpg)

**Comment by oliujunk** [comment]
Works well when I use node-casbin v2.0.4

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
@oliujunk Please create minimum reproducible test repo, thanks.

**Comment by nodece** [comment]
@oliujunk Thanks for the report! I submitted a PR: #86
