### ISSUE TITLE
Dead links in readme

### ISSUE THREAD

**Issue by J12934** [casbin/node-casbin#84]
Hi 👋

I've noticed that there are a couple of links pointing to sections in the readme which have recently been deleted.

1. "Persistence" pointing to: https://github.com/casbin/node-casbin#policy-persistence
2. "Policy management APIs" pointing to: https://github.com/casbin/node-casbin#policy-management

These sections appear to have been deleted in https://github.com/casbin/node-casbin/commit/147f1bd8f397f66bfd01c1c8c64a2a4ca826b688#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by hsluoyz** [comment]
Hi @J12934  can you make a PR to fix it? Please refer to the Golang Casbin.

**Comment by J12934** [comment]
> Hi @J12934 can you make a PR to fix it? Please refer to the Golang Casbin.

Yup, I can. At least for Persistence it seems relatively straight forward, as it always just linked to the Web Page.

The "policy management apis" link used to link to a proper subsection, it does so too on the golang casbin. Should I add these section back? (See: https://github.com/casbin/casbin#policy-management)

**Comment by hsluoyz** [comment]
Hi @J12934 , yes, you should add it back, as in: https://github.com/casbin/casbin/commit/6100a6f7a2c4cb5708892f3e6dba55600e405c4a
