### ISSUE TITLE
Upgraded from 2.0.4 to 3.0.4, but all my tests are failing

### ISSUE THREAD

**Issue by shlomi-nx** [casbin/node-casbin#88]
Anything changed to the semantics of model/policy in this version?

**Comment by nodece** [comment]
@shlomi-nx See: https://github.com/casbin/node-casbin/releases/tag/v3.0.0-beta.1

**Comment by shlomi-nx** [comment]
Thank you! I will check these out.

**Comment by shlomi-nx** [comment]
Yep, that was it. Thank you for pointing this out.
