### ISSUE TITLE
I wrote a new Adapter for pure MongoDB

### ISSUE THREAD

**Issue by juicycleff** [casbin/node-casbin#92]
Here is the link https://github.com/juicycleff/casbin-mongodb-adapter

**Comment by hsluoyz** [comment]
@juicycleff Thanks for your contribution to Casbin community :)

Left some comment in: https://github.com/juicycleff/casbin-mongodb-adapter/issues/1

And you can add it to our list: https://casbin.org/docs/en/adapters by making a PR. It can be placed between ORM and NoSQL (aka 1st in NoSQL).

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-website/pull/43
