### ISSUE TITLE
Request definition doesn't work without subject.

### ISSUE THREAD

**Issue by calebfaruki** [casbin/node-casbin#95]
In this first example, the subject is included in the request.

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj == p.obj && r.act == p.act
```

```csv
p, Resource, Read
```

```js
await e.enforce('p', 'Resource', 'Read') // returns true
```

But, if I remove the subject from the request definition, the CSV, and the enforce argument signature, I would expect the result to be the same. However, the coreEnforcer.ts returns an `Indeterminate` result.

```ini
[request_definition]
r = obj, act

[policy_definition]
p = obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.obj == p.obj && r.act == p.act
```

```csv
Resource, Read
```

```js
await e.enforce('Resource', 'Read') // returns false
```

The justification for removing the subject entirely is based on my particular use case. In my case, the policy comes in the form of a merged policy document specific to that user.

Is this a bug or a feature of casbin?

**Comment by nodece** [comment]
Hi @calebfaruki,
The `request_definition` defines the `enforce()` argument, The `policy_definition` defines the policy.

The first example: The first parameter of `enforce` is allowed to be any character, and the policy file has `Resource, Read`, so calling `enforce()` returns `true`. 

The second example: Policy should be `p, Resource, Read` and call `enforce()` will returns `true`.

**Comment by hsluoyz** [comment]
Hi @calebfaruki , I tested your case, the result is true (allowed): https://github.com/hsluoyz/node-casbin/commit/8a8fa92efbb36a0a2e817c413767b76596423b6a

**Comment by hsluoyz** [comment]
Closed as stale.
