### ISSUE TITLE
Suggestion: using standard-version to publish new version and manage changelog

### ISSUE THREAD

**Issue by dreamdevil00** [casbin/node-casbin#99]
It's a common best practice to have a changelog file in the open source repository. 

Using [standard-version](https://github.com/conventional-changelog/standard-version) make it easier to publish new version and manage changelog.

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Good idea, added to plan!

**Comment by hsluoyz** [comment]
We already have auto release now. But changelog is still missing.

**Comment by hsluoyz** [comment]
Can anyone add the changelog via standard-version? @DivyPatel9881 @kingiw @hackerchai

**Comment by hsluoyz** [comment]
@zhmushan can you take this issue?

**Comment by zhmushan** [comment]
There are currently tools that can automatically generate changelogs based on commits. I can do this after completing the exam (2 days later)
